apiVersion: v1
kind: Service
metadata:
  name: frontegg-{{ include "webhook-service.name" . }}
  labels:
    monitoring-metrics: enabled
  {{- include "webhook-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
  {{- include "webhook-service.selectorLabels" . | nindent 4 }}
