# --- BEGIN General Configuration --- #

variable "customer" {
  description = "The customer name for resource names and tagging. This will also be the autogenerated subdomain."
  type        = string
  default     = ""

  validation {
    condition = (
      length(var.customer) == 0 ||
      (length(var.customer) <= 10 &&
        can(regex("^[a-z0-9]", var.customer)) &&
        can(regex("[a-z0-9-]+", var.customer)) &&
        can(regex("[a-z0-9]$", var.customer))
    ))
    error_message = "Subdomain must be empty or between 1 and 10 characters long, start with a letter or digit, contain only lowercase letters, digits, or hyphens, and end with a letter or digit."
  }
}

variable "subdomain_override" {
  description = "For upgrades only, new stacks use `customer`. If the previous version used an identifier but you want the subdomain to be different, add it here."
  type        = string
  default     = ""

  validation {
    condition = (
      length(var.subdomain_override) == 0 ||
      (length(var.subdomain_override) <= 10 &&
        can(regex("^[a-z0-9]", var.subdomain_override)) &&
        can(regex("[a-z0-9-]+", var.subdomain_override)) &&
        can(regex("[a-z0-9]$", var.subdomain_override))
    ))
    error_message = "Subdomain must be empty or between 1 and 10 characters long, start with a letter or digit, contain only lowercase letters, digits, or hyphens, and end with a letter or digit."
  }
}

variable "environment" {
  description = "Environment of the application"
  type        = string
  default     = "dev"

  validation {
    condition     = length(var.environment) <= 5
    error_message = "The length of the Environment must be less than 6 characters."
  }
}

variable "protect_resources" {
  description = "Specifies whether data protection settings are enabled. If true they will prevent stack deletion until protections have been manually disabled."
  type        = bool
  default     = true
}

variable "aws_profile" {
  description = "If running terraform from a workstation, which AWS CLI profile should we use for asset provisioning."
  type        = string
  default     = ""
}

variable "cf_template_version" {
  description = "Version of the CloudFormation template that deployed this stack for validation"
  type        = number
  default     = 0

  validation {
    // Allow for 0 so we can override this check when deploying from workstations or tests.
    condition     = var.cf_template_version == 0 || var.cf_template_version >= 5
    error_message = "CloudFormation template version is out of date. Update your CloudFormation to deploy this version of the infrastructure."
  }
}

variable "subdomain_format" {
  type        = list(string)
  description = "Subdomain format specifying the order and/inclusion of customer, environment, and region (e.g., [%CUSTOMER%, %ENVIRONMENT%, %REGION%])"
  default     = ["%CUSTOMER%", "%ENVIRONMENT%", "%REGION%", "%ACCOUNT%"]

  validation {
    condition     = contains(var.subdomain_format, "%CUSTOMER%")
    error_message = "The subdomain_format list must contain the %CUSTOMER% placeholder."
  }
}

variable "external_fqdn" {
  description = "If an external fqdn is desired for this environment it will be used for certificates instead of auto-generating one."
  type        = string
  default     = ""
}

variable "alarm_email" {
  description = "Email address to send status alarms to."
  type        = string
  default     = ""
}
variable "slack_webhook_url" {
  description = "URL to an optional Slack webhook for SNS alerts."
  type        = string
  default     = ""
}

variable "managed_private_cloud" {
  description = "Whether or not this is a managed private cloud customer."
  type        = bool
  default     = true
}

# --- END General Configuration --- #

# --- BEGIN Network Configuration --- #

variable "vpc_id" {
  description = "The VPC ID where we'll be deploying our resources. (If creating a new VPC leave this field and subnets blank). When using an existing VPC be sure to tag at least 2 subnets with type = public and another 2 with tag type = private"
  type        = string
  default     = ""
}

variable "vpc_cidr" {
  description = "The CIDR block for the VPC"
  type        = string
  default     = "172.16.0.0/16"
}

variable "azs_count" {
  description = "The number of availability zones we should use for deployment."
  type        = number
  default     = 3

  validation {
    condition     = var.azs_count >= 3 && var.azs_count <= 10
    error_message = "AZ count must be between 3 and 10."
  }
}

variable "highly_available_nat_gateway" {
  description = "Should be true if you want to provision a highly available NAT Gateway across all of your private networks"
  type        = bool
  default     = true
}

# --- END Network Configuration --- #

# --- BEGIN Storage Configuration --- #

variable "s3_kms_key_id" {
  description = "AWS KMS key identifier for S3 encryption. The identifier can be one of the following format: Key id, key ARN, alias name or alias ARN"
  type        = string
  default     = ""
}

variable "use_existing_s3_kms" {
  description = "To use the s3_kms_key_id provided for the new s3 buckets as well, set this to true."
  type        = bool
  default     = false
}

variable "s3_existing_buckets" {
  description = "List of the existing Dozuki buckets to use. Do not include the logging bucket."
  type = list(object({
    type        = string
    bucket_name = string
  }))
  default = []

  validation {
    condition     = length(var.s3_existing_buckets) == 0 || length(var.s3_existing_buckets) == 4
    error_message = "You must specify all 4 guide buckets; no logging bucket."
  }

  validation {
    condition     = length(var.s3_existing_buckets) == 0 || sort([for _, bucket in var.s3_existing_buckets : bucket.type]) == tolist(["doc", "image", "obj", "pdf"])
    error_message = "You must include all 4 bucket types and 'type' must be one of 'doc', 'image', 'obj', or 'pdf'."
  }
}

variable "s3_block_public_access" {
  description = "To conform with SCP we can disable adding a public access block to the S3 buckets. This should only be disabled if absolutely necessary."
  type        = bool
  default     = true
}

variable "rds_kms_key_id" {
  description = "AWS KMS key identifier for RDS encryption. The identifier can be one of the following format: Key id, key ARN, alias name or alias ARN"
  type        = string
  default     = "alias/aws/rds"
}

variable "rds_snapshot_identifier" {
  description = "We can seed the database from an existing RDS snapshot in this region. Type the snapshot identifier in this field or leave blank to start with a fresh database. Note: If you do use a snapshot it's critical that during stack updates you continue to include the snapshot identifier in this parameter. Clearing this parameter after using it will cause AWS to spin up a new fresh DB and delete your old one."
  type        = string
  default     = ""
}

variable "rds_preferred_instance_classes" {
  description = "A list of preferred RDS instance classes, the first available in the list will be used. See this page for a breakdown of the performance and cost differences between the different instance types: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html"
  type        = list(string)
  default     = ["db.m5.large", "db.m4.large"]
}

variable "rds_multi_az" {
  description = "If true we will tell RDS to automatically deploy and manage a highly available standby instance of your database. Enabling this doubles the cost of the RDS instance but without it you are susceptible to downtime if the AWS availability zone your RDS instance is in becomes unavailable."
  type        = bool
  default     = true
}

variable "rds_allocated_storage" {
  description = "The initial size of the database (Gb)"
  type        = number
  default     = 100

  validation {
    condition     = var.rds_allocated_storage > 5 && var.rds_allocated_storage < 1000
    error_message = "The RDS allocated storage must be between 5 and 1000 Gb."
  }
}

variable "rds_max_allocated_storage" {
  description = "The maximum size to which AWS will scale the database (Gb)"
  type        = number
  default     = 500

  validation {
    condition     = var.rds_max_allocated_storage > 5 && var.rds_max_allocated_storage < 1000
    error_message = "The RDS max allocated storage must be between 5 and 1000 Gb."
  }
}

variable "rds_backup_retention_period" {
  description = "The number of days to keep automatic database backups. Setting this value to 0 disables automatic backups."
  type        = number
  default     = 30

  validation {
    condition     = var.rds_backup_retention_period >= 0 && var.rds_backup_retention_period <= 35
    error_message = "AWS limits backup retention to 35 days max."
  }
}

variable "rds_engine_version" {
  description = "To support legacy systems on mysql5.7 we allow setting the engine version here. Only 5.7 or 8.0 are allowed."
  type        = string
  default     = "8.0"

  validation {
    condition     = contains(["5.7", "8.0"], var.rds_engine_version)
    error_message = "Only 5.7 or 8.0 are allowed mysql engine versions"
  }
}

variable "enable_bi" {
  description = "This option will spin up a BI slave of your master database and enable conditional replication (everything but the mysql table will be replicated so you can have custom users)."
  type        = bool
  default     = false
}

variable "bi_dms_enabled" {
  description = "If BI is enabled, whether or not to use DMS for conditional replication if true or a basic RDS read replica if false."
  type        = bool
  default     = false
}

variable "bi_public_access" {
  description = "NOTE: This is mutually exclusive with VPN access, both cannot be enabled at the same time. If BI is enabled and you need access to the BI database server from outside the amazon network, set this to true."
  type        = bool
  default     = false
}

variable "bi_vpn_access" {
  description = "NOTE: This is mutually exclusive with public BI access, both cannot be enabled at the same time. If BI is enabled we can create an OpenVPN connection to the BI database for secure internet access to the server."
  type        = bool
  default     = false
}

variable "bi_vpn_user_list" {
  description = "List of users to create OpenVPN configurations for usint mutual authentication."
  type        = list(string)
  default     = ["root"]
}

variable "bi_access_cidrs" {
  description = "If BI and public access is enabled, these CIDRs will be permitted through the firewall to access it. If VPN is enabled, these are the CIDRs that are allowed to connect to the VPN server. If left empty it will default to your VPC CIDR"
  type        = list(string)
  default     = []
}

# --- END Storage Configuration --- #

# --- BEGIN App Configuration --- #

variable "app_public_access" {
  description = "Should the app and dashboard be accessible via a publicly routable IP and domain?"
  type        = bool
  default     = true
}

variable "replicated_ui_access_cidrs" {
  description = "These CIDRs will be allowed to connect to the app dashboard. This is where you upgrade to new versions as well as view cluster status and start/stop the cluster. You probably want to lock this down to your company network CIDR, especially if you chose 'true' for public access."
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "app_access_cidrs" {
  description = "These CIDRs will be allowed to connect to Dozuki. If running a public site, use the default value. Otherwise you probably want to lock this down to the VPC or your VPN CIDR."
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "elasticache_instance_type" {
  type        = string
  default     = "cache.t2.micro"
  description = "Elastic cache instance type"
}

variable "elasticache_cluster_size" {
  type        = number
  default     = 1
  description = "Cluster size"
}

variable "eks_kms_key_id" {
  description = "AWS KMS key identifier for EKS encryption. The identifier can be one of the following format: Key id, key ARN, alias name or alias ARN"
  type        = string
  default     = ""
}

variable "eks_instance_types" {
  description = "The instance type of each node in the application's EKS worker node group."
  // For Govcloud ["m5.large", "m5a.large", "m5d.large", "m5ad.large"]
  default = ["m7i-flex.xlarge", "m7i.xlarge"]
  type    = list(string)
}

variable "eks_volume_size" {
  description = "The amount of local storage (in gigabytes) to allocate to each kubernetes node. Keep in mind you will be billed for this amount of storage multiplied by how many nodes you spin up (i.e. 50GB * 4 nodes = 200GB on your bill). For production installations 50GB should be the minimum. This local storage is used as a temporary holding area for uploaded and in-process assets like videos and images."
  default     = 100
  type        = number

  validation {
    condition     = var.eks_volume_size >= 20
    error_message = "Less than 20GB can cause problems even on testing instances."
  }
}

variable "eks_min_size" {
  description = "The minimum amount of nodes we will autoscale to."
  type        = number
  default     = "3"

  validation {
    condition     = var.eks_min_size >= 1
    error_message = "NodeAutoScalingGroupMinSize must be an integer >= 1."
  }
}

variable "eks_max_size" {
  description = "The maximum amount of nodes we will autoscale to."
  type        = number
  default     = "10"

  validation {
    condition     = var.eks_max_size >= 1
    error_message = "NodeAutoScalingGroupMaxSize must be an integer >= 1\nNodeAutoScalingGroupMaxSize must be >= NodeAutoScalingGroupDesiredCapacity & NodeAutoScalingGroupMinSize."
  }
}

variable "eks_desired_capacity" {
  description = "This is what the node count will start out as."
  type        = number
  default     = "3"

  validation {
    condition     = var.eks_desired_capacity >= 1
    error_message = "NodeAutoScalingGroupDesiredCapacity must be an integer >= 1\nNodeAutoScalingGroupDesiredCapacity must be >= NodeAutoScalingGroupMinSize\nNodeAutoScalingGroupDesiredCapacity must be <= NodeAutoScalingGroupMaxSize."
  }
}

variable "eks_k8s_version" {
  description = "Version of Kubernetes to launch or upgrade to. EKS does not support rolling back versions or upgrade version skipping."
  type        = string
  default     = "1.27"
}

variable "enable_webhooks" {
  description = "This option will spin up a managed Kafka & Redis cluster to support private webhooks."
  type        = bool
  default     = false
}

# --- END App Configuration --- #