# --- BEGIN General Configuration --- #

variable "customer" {
  description = "The customer name for resource names and tagging. This will also be the autogenerated subdomain."
  type        = string
  default     = ""

  validation {
    condition = (
      length(var.customer) == 0 ||
      (length(var.customer) <= 10 &&
        can(regex("^[a-z0-9]", var.customer)) &&
        can(regex("[a-z0-9-]+", var.customer)) &&
        can(regex("[a-z0-9]$", var.customer))
    ))
    error_message = "Subdomain must be empty or between 1 and 10 characters long, start with a letter or digit, contain only lowercase letters, digits, or hyphens, and end with a letter or digit."
  }
}

variable "subdomain_override" {
  description = "For upgrades only, new stacks use `customer`. If the previous version used an identifier but you want the subdomain to be different, add it here."
  type        = string
  default     = ""

  validation {
    condition = (
      length(var.subdomain_override) == 0 ||
      (length(var.subdomain_override) <= 10 &&
        can(regex("^[a-z0-9]", var.subdomain_override)) &&
        can(regex("[a-z0-9-]+", var.subdomain_override)) &&
        can(regex("[a-z0-9]$", var.subdomain_override))
    ))
    error_message = "Subdomain must be empty or between 1 and 10 characters long, start with a letter or digit, contain only lowercase letters, digits, or hyphens, and end with a letter or digit."
  }
}

variable "environment" {
  description = "Environment of the application"
  type        = string
  default     = "dev"

  validation {
    condition     = length(var.environment) <= 5
    error_message = "The length of the Environment must be less than 6 characters."
  }
}

variable "protect_resources" {
  description = "Specifies whether data protection settings are enabled. If true they will prevent stack deletion until protections have been manually disabled."
  type        = bool
  default     = true
}

variable "db_apply_immediately" {
  description = <<-EOT
    Whether database modifications apply immediately instead of waiting for the next
    maintenance window. Applies to the Aurora cluster, the RDS instance, the BI replica and
    the Aurora DR secondary.

    Leave null (the default) to keep the historical behaviour, which is !protect_resources:
    production stacks defer to the maintenance window and disposable ones apply at once.

    Set true on a production stack when a change has to land inside a scheduled window
    rather than at preferred_maintenance_window (sun:19:00-sun:23:00). Without it, an apply
    that modifies the database returns green having only SCHEDULED the change, which is
    especially misleading during a migration cutover: the run succeeds and nothing has
    happened yet.

    This does not make a change safe, it makes it prompt. An immediate modification can
    still be disruptive, so treat true as an in-window setting rather than a default.
  EOT
  type        = bool
  default     = null
}

variable "aws_profile" {
  description = "If running terraform from a workstation, which AWS CLI profile should we use for asset provisioning."
  type        = string
  default     = ""
}

variable "cf_template_version" {
  description = "Version of the CloudFormation template that deployed this stack for validation"
  type        = number
  default     = 0

  validation {
    // Allow for 0 so we can override this check when deploying from workstations or tests.
    condition     = var.cf_template_version == 0 || var.cf_template_version >= 5
    error_message = "CloudFormation template version is out of date. Update your CloudFormation to deploy this version of the infrastructure."
  }
}

variable "subdomain_format" {
  type        = list(string)
  description = "Subdomain format specifying the order and/inclusion of customer, environment, and region (e.g., [%CUSTOMER%, %ENVIRONMENT%, %REGION%])"
  default     = ["%CUSTOMER%", "%ENVIRONMENT%", "%REGION%", "%ACCOUNT%"]

  validation {
    condition     = contains(var.subdomain_format, "%CUSTOMER%")
    error_message = "The subdomain_format list must contain the %CUSTOMER% placeholder."
  }
}

variable "external_fqdn" {
  description = "If an external fqdn is desired for this environment it will be used for certificates instead of auto-generating one."
  type        = string
  default     = ""
}

variable "alarm_email" {
  description = "Email address to send status alarms to."
  type        = string
  default     = ""
}
variable "slack_webhook_url" {
  description = "URL to an optional Slack webhook for SNS alerts. Prefer slack_bot_token + slack_channel_id: webhook posts have a synthetic author no token can delete or edit, and the URL sits in the lambda's plaintext env."
  type        = string
  default     = ""
}

variable "slack_bot_token" {
  description = "Slack bot token (chat:write) for SNS alerts via chat.postMessage. Stored as an SSM SecureString the lambda reads at runtime; takes precedence over slack_webhook_url when set together with slack_channel_id."
  type        = string
  default     = ""
  sensitive   = true

  validation {
    condition     = (var.slack_bot_token == "") == (var.slack_channel_id == "")
    error_message = "slack_bot_token and slack_channel_id must be set together (or both left empty)."
  }
}

variable "slack_channel_id" {
  description = "Slack channel ID the bot-token alerts post to. Required alongside slack_bot_token. The bot must be a member of this channel (invite it, or grant chat:write.public for public channels) or every delivery fails not_in_channel at runtime."
  type        = string
  default     = ""
}

variable "managed_private_cloud" {
  description = "Whether or not this is a managed private cloud customer."
  type        = bool
  default     = true
}

# --- END General Configuration --- #

# --- BEGIN Network Configuration --- #

variable "vpc_id" {
  description = "The VPC ID where we'll be deploying our resources. (If creating a new VPC leave this field and subnets blank). When using an existing VPC be sure to tag at least 2 subnets with type = public and another 2 with tag type = private"
  type        = string
  default     = ""
}

variable "vpc_cidr" {
  description = "The CIDR block for the VPC"
  type        = string
  default     = "172.16.0.0/16"
}

variable "highly_available_nat_gateway" {
  description = "Should be true if you want to provision a highly available NAT Gateway across all of your private networks"
  type        = bool
  default     = true
}

# --- END Network Configuration --- #

# --- BEGIN Storage Configuration --- #

variable "s3_kms_key_id" {
  description = "AWS KMS key identifier for S3 encryption. The identifier can be one of the following format: Key id, key ARN, alias name or alias ARN"
  type        = string
  default     = ""
}

variable "use_existing_s3_kms" {
  description = "To use the s3_kms_key_id provided for the new s3 buckets as well, set this to true."
  type        = bool
  default     = false
}

variable "s3_existing_buckets" {
  description = "List of the existing Dozuki buckets to use. Do not include the logging bucket."
  type = list(object({
    type        = string
    bucket_name = string
  }))
  default = []

  validation {
    condition     = length(var.s3_existing_buckets) == 0 || length(var.s3_existing_buckets) == 4
    error_message = "You must specify all 4 guide buckets; no logging bucket."
  }

  validation {
    condition     = length(var.s3_existing_buckets) == 0 || sort([for _, bucket in var.s3_existing_buckets : bucket.type]) == tolist(["doc", "image", "obj", "pdf"])
    error_message = "You must include all 4 bucket types and 'type' must be one of 'doc', 'image', 'obj', or 'pdf'."
  }
}

variable "s3_block_public_access" {
  description = "To conform with SCP we can disable adding a public access block to the S3 buckets. This should only be disabled if absolutely necessary."
  type        = bool
  default     = true
}

variable "rds_kms_key_id" {
  description = "AWS KMS key identifier for RDS encryption. The identifier can be one of the following format: Key id, key ARN, alias name or alias ARN"
  type        = string
  default     = "alias/aws/rds"
}

variable "rds_snapshot_identifier" {
  description = "We can seed the database from an existing RDS snapshot in this region. Type the snapshot identifier in this field or leave blank to start with a fresh database. Note: If you do use a snapshot it's critical that during stack updates you continue to include the snapshot identifier in this parameter. Clearing this parameter after using it will cause AWS to spin up a new fresh DB and delete your old one."
  type        = string
  default     = ""
}

variable "rds_preferred_instance_classes" {
  description = "A list of preferred RDS instance classes, the first available in the list will be used. See this page for a breakdown of the performance and cost differences between the different instance types: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html"
  type        = list(string)
  default     = ["db.m5.large", "db.m4.large"]
}

variable "rds_multi_az" {
  description = "If true we will tell RDS to automatically deploy and manage a highly available standby instance of your database. Enabling this doubles the cost of the RDS instance but without it you are susceptible to downtime if the AWS availability zone your RDS instance is in becomes unavailable."
  type        = bool
  default     = true
}

variable "rds_allocated_storage" {
  description = "The initial size of the database (Gb)"
  type        = number
  default     = 100

  validation {
    condition     = var.rds_allocated_storage > 5 && var.rds_allocated_storage < 1000
    error_message = "The RDS allocated storage must be between 5 and 1000 Gb."
  }
}

variable "rds_max_allocated_storage" {
  description = "The maximum size to which AWS will scale the database (Gb)"
  type        = number
  default     = 500

  validation {
    condition     = var.rds_max_allocated_storage > 5 && var.rds_max_allocated_storage < 1000
    error_message = "The RDS max allocated storage must be between 5 and 1000 Gb."
  }
}

variable "rds_backup_retention_period" {
  description = "The number of days to keep automatic database backups. Setting this value to 0 disables automatic backups."
  type        = number
  default     = 30

  validation {
    condition     = var.rds_backup_retention_period >= 0 && var.rds_backup_retention_period <= 35
    error_message = "AWS limits backup retention to 35 days max."
  }
}

variable "rds_engine_family" {
  description = "Parameter-group family for the provisioned RDS primary and the legacy BI instance. Tracks rds_engine_version's major.minor; 8.4 by default now that 8.0 is past end of standard support. An existing 8.0 stack either pins \"8.0\" or migrates to Aurora before it takes this release. Aurora derives its own family from aurora_engine_version."
  type        = string
  default     = "8.4"

  validation {
    condition     = contains(["5.7", "8.0", "8.4"], var.rds_engine_family)
    error_message = "Only 5.7, 8.0 or 8.4 are allowed mysql engine families"
  }
}
variable "rds_engine_version" {
  description = <<-EOT
    MySQL engine version for the PROVISIONED RDS primary (db_engine = "rds") and its read
    replica. Legacy path: db_engine defaults to "aurora", so a new stack never creates one.

    Defaults to an 8.4 version. RDS for MySQL 8.0 left standard support on 2026-07-31, so
    anything still on it is auto-enrolled in RDS Extended Support and billed per vCPU-hour -
    the codebase should not be handing that to a new stack by default.

    Not every existing 8.0 stack pins it, so do not assume this default is inert. A major
    version change plans an in-place upgrade, which is NOT how the remaining 8.0 instances get
    fixed: they are either Aurora-migration rollback anchors headed for deletion, or live
    primaries whose route to 8.4 is the Aurora migration itself. Neither wants a major upgrade
    triggered by a module default. The rule for an unpinned 8.0 stack is therefore to migrate
    it to Aurora before it takes this release; pin "8.0" only to hold one in place meanwhile.

    Prefer the bare family ("8.4") over an exact minor where you can: AWS resolves it to the
    latest matching minor, so auto_minor_version_upgrade drift never shows up as a diff.
  EOT
  type        = string
  default     = "8.4"

  validation {
    condition     = startswith(var.rds_engine_version, "5") || startswith(var.rds_engine_version, "8")
    error_message = "Only 5.7 or 8.x are allowed mysql engine versions"
  }
}

variable "bi_db_engine" {
  description = <<-EOT
    Engine for the BI database that DMS replicates into: "aurora" (Aurora MySQL Serverless v2)
    or "rds" (provisioned RDS MySQL, the legacy path).

    Aurora is what new stacks should use, for two reasons. The BI database was pinned to MySQL
    "8.0" with no way to change it, so every stack got one even when its primary was Aurora 8.4
    - and 8.0 left standard support on 2026-07-31, so those instances bill RDS Extended Support
    indefinitely. And BI is idle most of the time: Serverless v2 scales down to
    bi_aurora_min_acu between queries, where a provisioned instance bills flat.

    The DEFAULT is nonetheless "rds", and deliberately so. Every stack that has a BI database
    today is on the provisioned path and none of them pin this variable, so defaulting to
    "aurora" would flip all six the moment they bumped infra_version - turning a routine module
    bump into a database replacement nobody asked for in that run. db-replace-guard would catch
    it (the plan fails rather than the data going away), but a fleet of failing plans is not a
    good default either. New stacks get Aurora from _templates/env.hcl instead, which is where
    a new-stack default belongs; the code default only decides what happens to stacks that
    predate the variable, and for those the right answer is "keep what you have".

    Switching an existing stack REPLACES the BI database. It is a rebuildable DMS target - a
    full load repopulates it - so the flip is safe to schedule, just not to do by accident.
    Separately, and regardless of this variable: the first apply that picks up the DMS
    Serverless release replaces the provisioned replication task with a replication config.
    No manual pre-step is required - the provider stops the old task before deleting it. The
    only wrinkle is ordering: nothing sequences the old task's destroy against the new
    config's create, so the full load can start while the old task is still stopping. BI is
    rebuildable and the load wins, so it is untidy rather than harmful; pre-stopping with
    util/dms-stop.sh avoids the overlap if you want a clean sequence.

    Terraform cannot sequence it on its own: DMS refuses to modify an endpoint while the
    replication is running, so it has to be stopped first, and the new empty cluster then
    needs reload-target to repopulate. Order is: stop-replication and wait for Stopped, clear
    deletion protection on the outgoing RDS BI instance, apply with the allow-db-replace
    label, then start-replication with reload-target and confirm the full load.

    The deletion-protection step is not optional. The instance is created with
    deletion_protection = var.protect_resources, the switch takes its count to 0, and RDS
    refuses DeleteDBInstance on a protected instance - so without the pre-step the apply dies
    mid-way, after the Aurora cluster exists and with the replication already stopped against
    the 48h clock. Terraform cannot clear the flag itself: the same apply removes the
    instance from config, so the changed attribute is never applied before the delete. Run it
    out-of-band (a destroy does not diff against state, the drift is harmless):
      aws rds modify-db-instance --db-instance-identifier <id>-dms-replica \
        --no-deletion-protection --apply-immediately
    Do NOT flip protect_resources stack-wide instead; that drops protection on the primary
    and flips skip_final_snapshot everywhere.

    The restart is the operator's job, not the layer's. The switch modifies the target
    ENDPOINT in place (server_name/username/password are not ForceNew), so the endpoint ARN
    and the replication config are both unchanged, the dms_replication_generation hash does
    not move, and no fresh dms-start Job is created to pick the replication back up. Anything
    that does restart it without reload-target makes it worse: resume-processing takes CDC
    from the last checkpoint against an empty cluster, and the replication then reports
    Running while holding no historical data. Check TablesLoaded against the previous table
    count, not the status. Do not leave it stopped for 48 hours - a serverless replication is
    deprovisioned at that point and cannot be resumed, only recreated. Cheapest moment is
    alongside that env's primary KMS key swap, since both replace a database in the same
    window.
  EOT
  type        = string
  default     = "rds"

  validation {
    condition     = contains(["rds", "aurora"], var.bi_db_engine)
    error_message = "bi_db_engine must be 'rds' or 'aurora'."
  }
}

variable "bi_dms_min_dcu" {
  description = <<-EOT
    Minimum DMS capacity units the BI serverless replication scales down to (1 DCU = 2 GB RAM).
    This is the floor that bills continuously while the replication runs, so it is the number
    that decides steady-state cost - max only bills when a burst uses it.

    2 by default. The 3M BI replications measured under 5% CPU for 92-100% of hours, so the
    floor carries the ongoing CDC and full loads scale up from there. Raise it for a busy
    source: too low a floor means DMS is still provisioning when a spike arrives, and a
    sustained CapacityUtilization at max can fail the replication outright.
  EOT
  type        = number
  default     = 2
}

variable "bi_dms_max_dcu" {
  description = <<-EOT
    Maximum DMS capacity units the BI serverless replication can scale up to. Sized for the
    full load, which is far heavier than steady-state CDC. You only pay for capacity actually
    used, so AWS guidance is to set this generously rather than tightly.
  EOT
  type        = number
  default     = 32
}

variable "bi_aurora_min_acu" {
  description = "Minimum Aurora Serverless v2 capacity for the BI database. 0.5 by default: BI is queried in bursts and idles between them, which is the whole reason for moving it off a provisioned instance. Ignored unless bi_db_engine = \"aurora\"."
  type        = number
  default     = 0.5
}

variable "bi_aurora_max_acu" {
  description = "Maximum Aurora Serverless v2 capacity for the BI database. Sized for the DMS full load, which is heavier than steady-state BI querying. Ignored unless bi_db_engine = \"aurora\"."
  type        = number
  default     = 16
}


variable "enable_bi" {
  description = "This option will spin up a BI slave of your master database and enable conditional replication (everything but the mysql table will be replicated so you can have custom users)."
  type        = bool
  default     = false
}

variable "bi_dms_enabled" {
  description = "If BI is enabled, whether or not to use DMS for conditional replication if true or a basic RDS read replica if false."
  type        = bool
  default     = false
}

variable "bi_public_access" {
  description = "NOTE: This is mutually exclusive with VPN access, both cannot be enabled at the same time. If BI is enabled and you need access to the BI database server from outside the amazon network, set this to true."
  type        = bool
  default     = false
}

variable "bi_vpn_access" {
  description = "NOTE: This is mutually exclusive with public BI access, both cannot be enabled at the same time. If BI is enabled we can create an OpenVPN connection to the BI database for secure internet access to the server."
  type        = bool
  default     = false
}

variable "bi_vpn_user_list" {
  description = "List of users to create OpenVPN configurations for usint mutual authentication."
  type        = list(string)
  default     = ["root"]
}

variable "bi_access_cidrs" {
  description = "If BI and public access is enabled, these CIDRs will be permitted through the firewall to access it. If VPN is enabled, these are the CIDRs that are allowed to connect to the VPN server. If left empty it will default to your VPC CIDR"
  type        = list(string)
  default     = []
}

# --- END Storage Configuration --- #

# --- BEGIN App Configuration --- #

variable "app_public_access" {
  description = "Should the app and dashboard be accessible via a publicly routable IP and domain?"
  type        = bool
  default     = true
}

variable "app_access_cidrs" {
  description = "These CIDRs will be allowed to connect to Dozuki. If running a public site, use the default value. Otherwise you probably want to lock this down to the VPC or your VPN CIDR."
  type        = list(string)
  default     = ["0.0.0.0/0"]
}



variable "eks_kms_key_id" {
  description = "AWS KMS key identifier for EKS encryption. The identifier can be one of the following format: Key id, key ARN, alias name or alias ARN"
  type        = string
  default     = ""
}

variable "eks_k8s_version" {
  description = "Kubernetes version override. Leave null to let EKS Auto Mode manage the version. Set explicitly only to pin a specific version."
  type        = string
  default     = null
}

variable "eks_enabled_log_types" {
  description = "EKS control-plane log types to stream to CloudWatch Logs. Defaults to all 5 (audit, api, authenticator, controllerManager, scheduler) for compliance (SOC2 / Vanta require audit logs at minimum). Set to [] to disable cluster logging entirely (not recommended)."
  type        = list(string)
  default     = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
}

variable "vault_endpoint_service_name" {
  description = "VPC Endpoint Service name for the Vault PrivateLink service (e.g. com.amazonaws.vpce.us-east-1.vpce-svc-xxx). Deploy vault-privatelink-service first."
  type        = string
}

variable "sso_admin_role_arn" {
  description = "Exact IAM role ARN for the SSO AdministratorAccess permission set in this account. Required for kubectl/Lens access from workstations. Find it via: aws iam list-roles --query \"Roles[?contains(RoleName,'AWSReservedSSO_AWSAdministratorAccess')].Arn\""
  type        = string
  default     = ""
}

variable "enable_dr" {
  description = "Enable the always-on cross-region DR data-protection layer (RDS automated-backup replication + S3 CRR). On by default; ephemeral/dev stacks may set false."
  type        = bool
  default     = true
}

variable "dr_region" {
  description = "The DR region (concrete value). Normally injected by the Spacelift admin layer via TG_AWS_DR_REGION; may be set explicitly to override. Never auto-derived in workload TF."
  type        = string
  default     = ""
}

variable "dr_vpc_cidr" {
  description = "CIDR for the minimal DR-region VPC that hosts the headless Aurora global-database secondary (private subnets only; no NAT/IGW). Must not overlap the primary VPC. Only used when the Aurora DR secondary is created (aurora engine + enable_dr)."
  type        = string
  default     = "10.99.0.0/20"
}

variable "operations_owner" {
  description = "Which on-call owns this stack's DR page: 'dozuki' (Dozuki 24/7 on-call, the MPC posture) or 'customer' (the customer's named on-call runs the failover, Dozuki advisory). Empty derives it from managed_private_cloud. Stamped into the page so the receiver knows whether they are the actor or the advisor."
  type        = string
  default     = ""

  validation {
    condition     = contains(["", "dozuki", "customer"], var.operations_owner)
    error_message = "operations_owner must be \"dozuki\", \"customer\", or empty (derive from managed_private_cloud)."
  }
}

variable "dr_paging_endpoint" {
  description = "Compatibility override for the DR dead-man HTTPS paging endpoint. Prefer victorops_cloudwatch_endpoint_template, which derives the mpc-dr endpoint from the shared Splunk On-Call integration. Empty falls back to VictorOps and then email."
  type        = string
  default     = ""

  validation {
    condition     = var.dr_paging_endpoint == "" || startswith(var.dr_paging_endpoint, "https://")
    error_message = "dr_paging_endpoint must be an https:// URL (or empty)."
  }
}

variable "victorops_cloudwatch_endpoint_template" {
  description = "Shared Splunk On-Call AWS CloudWatch HTTPS endpoint ending in the literal $routing_key placeholder. The write-only Spacelift context supplies it fleet-wide."
  type        = string
  default     = ""
  sensitive   = true

  validation {
    condition = (
      contains(["", "CHANGE_ME"], var.victorops_cloudwatch_endpoint_template) ||
      (
        startswith(var.victorops_cloudwatch_endpoint_template, "https://") &&
        endswith(var.victorops_cloudwatch_endpoint_template, "$routing_key")
      )
    )
    error_message = "victorops_cloudwatch_endpoint_template must be empty, CHANGE_ME during bootstrap, or an https:// URL ending in the literal $routing_key placeholder."
  }
}

variable "victorops_dr_routing_key" {
  description = "Splunk On-Call routing key used for DR dead-man alarm and recovery events."
  type        = string
  default     = "mpc-dr"

  validation {
    condition     = can(regex("^[A-Za-z0-9_-]+$", var.victorops_dr_routing_key))
    error_message = "victorops_dr_routing_key may contain only letters, numbers, hyphens, and underscores."
  }
}

variable "rds_adopt_dr_cmk" {
  description = <<-EOT
    Whether the database is encrypted with a Terraform-managed customer KMS key. True is the
    default and there is no longer any other gate on it: DR does not have to be enabled, and
    there is no separate opt-in. A fresh stack gets a CMK.

    The name is historical (the key was originally introduced for DR) and reads narrower than
    what this actually controls, which is the database's encryption key. Read it as "adopt a
    customer-managed key", not "only when DR is on".

    Set false ONLY on a stack whose database already exists on the AWS-managed key. That is
    what the flag is for: the KMS key is immutable on RDS and Aurora, so such a database can
    adopt a CMK only by being REPLACED, and false is what holds it flat. Pinning
    rds_kms_key_id to an already-adopted CMK has the same effect.

    The db-replace-guard PLAN policy blocks an unintended replacement (its safe list is
    added/changed/moved and it requires the allow-db-replace stack label otherwise), so
    getting this wrong fails closed rather than losing data.
  EOT
  type        = bool
  default     = true
}

variable "db_engine" {
  description = "Database engine for this stack: 'rds' (provisioned RDS MySQL) or 'aurora' (Aurora MySQL 8.4 Serverless v2). Default 'aurora' for new stacks. EXISTING rds stacks must pin db_engine='rds' in env.hcl, or a deploy will try to replace the DB — the Spacelift db-replace-guard plan policy blocks that accidental rds->aurora switch (override per stack with the allow-db-replace label for a deliberate migration)."
  type        = string
  default     = "aurora"

  validation {
    condition     = contains(["rds", "aurora"], var.db_engine)
    error_message = "db_engine must be 'rds' or 'aurora'."
  }
}

variable "aurora_min_acu" {
  description = "Aurora Serverless v2 minimum capacity (ACUs)."
  type        = number
  default     = 0.5
}

variable "aurora_max_acu" {
  description = "Aurora Serverless v2 maximum capacity (ACUs)."
  type        = number
  default     = 16
}

variable "aurora_engine_version" {
  description = "Aurora MySQL engine version, full aws RDS format (e.g. 8.4.mysql_aurora.8.4.7 — the bare 8.4.7 is rejected with 'Cannot find version'). Fresh cluster: an 8.4 version. Snapshot-restore migration: an 8.0-compatible version first, then upgrade."
  type        = string
  default     = "8.4.mysql_aurora.8.4.7"
}

variable "aurora_snapshot_identifier" {
  description = "Optional RDS DB snapshot ARN to restore the Aurora cluster from (migration path). Empty = fresh cluster."
  type        = string
  default     = ""
}

variable "aurora_migration_state" {
  description = <<-EOT
    RDS -> Aurora DMS migration state machine (aurora-migration.tf). off = no
    migration (default). provision = Aurora comes up empty alongside the live RDS,
    guarded to DMS+bastion, with the DMS rig created but not started. cutover =
    connection facts (secret/outputs/BI DMS/bastion) flip to Aurora and the app SG
    path opens - apply only at the migration runner's go-live gate. cleanup = the
    DMS rig is removed; Aurora stays primary, the RDS survives as the fail-forward
    net until the env's final db_engine="aurora" flip. Only meaningful while
    db_engine="rds".
  EOT
  type        = string
  default     = "off"
  validation {
    condition     = contains(["off", "provision", "cutover", "cleanup"], var.aurora_migration_state)
    error_message = "aurora_migration_state must be one of: off, provision, cutover, cleanup."
  }
  validation {
    condition     = var.aurora_migration_state == "off" || var.db_engine == "rds"
    error_message = "aurora_migration_state is only meaningful while db_engine=\"rds\" (it migrates RDS to Aurora)."
  }
}

variable "aurora_migration_dms_instance_type" {
  # xlarge default: c5.large (4GB) OOM-crash-looped apac's full load AND
  # OOM-killed latam's fence validation epoch mid-cutover (source fenced,
  # customers waiting on the resize). The bigger box costs cents per soak day.
  description = "Replication instance class for the Aurora migration DMS rig."
  type        = string
  default     = "dms.c5.xlarge"
}

variable "aurora_migration_dms_storage" {
  description = "Allocated storage (GB) for the Aurora migration DMS replication instance."
  type        = number
  default     = 100
}

variable "aurora_migration_dms_engine_version" {
  description = "Pinned DMS engine version for the migration rig (run-to-run reproducibility; 3.6.1 = the rehearsal-proven version)."
  type        = string
  default     = "3.6.1"
}

variable "aurora_migration_source_fenced" {
  description = <<-EOT
    Cutover write-fence for the RDS source during an Aurora migration. When true,
    read_only=1 is injected into the RDS parameter group AS CONFIG, so the fence
    is Terraform-owned: no concurrent or subsequent apply can silently revert it
    (an out-of-band fence would be reset by any refreshed apply mid-cutover).
    Set true (gated apply) at the runner's fence step; back to false only on a
    pre-cutover abort. On RDS MySQL 8.0.36+ read_only=1 is a complete fence for
    every customer account - no grantable privilege bypasses it.
  EOT
  type        = bool
  default     = false
  validation {
    condition     = !var.aurora_migration_source_fenced || var.aurora_migration_state != "off"
    error_message = "aurora_migration_source_fenced requires an active aurora_migration_state."
  }
  validation {
    # Once cutover is applied the app writes to Aurora; unfencing the RDS then
    # would split-brain. The fence stays on through cutover and cleanup - the
    # RDS unfreezes only at its final retirement (db_engine flip).
    condition     = var.aurora_migration_source_fenced || !contains(["cutover", "cleanup"], var.aurora_migration_state)
    error_message = "aurora_migration_source_fenced must remain true while aurora_migration_state is cutover or cleanup (unfencing a replaced source would split-brain)."
  }
}


variable "delete_after" {
  description = "Optional RFC3339 timestamp. When set, every resource is tagged deleteAfter=<value> so the ResourceReaper janitor can purge it after that time if teardown fails. Empty = no tag (normal deploys)."
  type        = string
  default     = ""
}

# --- END App Configuration --- #

variable "rds_log_exports" {
  description = "Database log types exported to CloudWatch Logs (365-day retention). Aurora supports all four; provisioned RDS instances export the subset possible without an option group (audit needs the MariaDB audit plugin option). All four are on by default, general included: house stance is log everything, storage cost accepted (general records every statement, so query text lands in CloudWatch)."
  type        = list(string)
  default     = ["audit", "error", "general", "slowquery"]

  validation {
    condition     = alltrue([for l in var.rds_log_exports : contains(["audit", "error", "general", "slowquery"], l)])
    error_message = "rds_log_exports entries must be among: audit, error, general, slowquery."
  }
}
