kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "api-gateway.fullname" . }}-configmap
  labels:
  {{- include "api-gateway.labels" . | nindent 4 }}
data:
  FRONTEGG_HYBRID_MODE: "true"
  {{- with .Values.network }}
  FRONTEGG_ADMINS_SERVICE_URL: {{ required "A valid .Values.network.adminsServiceUrl entry required!" .adminsServiceUrl }}
  FRONTEGG_AUDITS_SERVICE_URL: {{ required "A valid .Values.network.auditsServiceUrl entry required!" .auditsServiceUrl }}
  FRONTEGG_AUTHENTICATION_SERVICE_URL: {{ required "A valid .Values.network.authenticationServiceUrl entry required!" .authenticationServiceUrl }}
  FRONTEGG_NOTIFICATION_SERVICE_URL: {{ required "A valid .Values.network.notificationServiceUrl entry required!" .notificationServiceUrl }}
  FRONTEGG_REPORTS_ENGINE_URL: {{ required "A valid .Values.network.reportsEngineUrl entry required!" .reportsEngineUrl }}
  FRONTEGG_REPORTS_SERVICE_URL: {{ required "A valid .Values.network.reportsServiceUrl entry required!" .reportsServiceUrl }}
  FRONTEGG_TEAM_SERVICE_URL: {{ required "A valid .Values.network.teamServiceUrl entry required!" .teamServiceUrl }}
  FRONTEGG_VENDORS_SERVICE_URL: {{ required "A valid .Values.network.vendorsServiceUrl entry required!" .vendorsServiceUrl }}
  FRONTEGG_TENANT_SERVICE_URL: {{ required "A valid .Values.network.tenantsServiceUrl entry required!" .tenantsServiceUrl }}
  FRONTEGG_WEBPUSH_SERVICE_URL: {{ required "A valid .Values.network.webpushServiceUrl entry required!" .webpushServiceUrl }}
  FRONTEGG_FEATURE_FLAGS_SERVICE_URL: {{ required "A valid .Values.network.featureFlagsServiceUrl entry required!" .featureFlagsServiceUrl }}
  FRONTEGG_WEBHOOK_SERVICE_URL: {{ required "A valid .Values.network.webhookServiceUrl entry required!" .webhookServiceUrl }}
  FRONTEGG_EVENT_SERVICE_URL: {{ required "A valid .Values.network.eventsServiceUrl entry required!" .eventsServiceUrl }}
  FRONTEGG_IDENTITY_SERVICE_URL: {{ required "A valid .Values.network.identityServiceUrl entry required!" .identityServiceUrl }}
  FRONTEGG_INTEGRATIONS_SERVICE_URL: {{ required "A valid .Values.network.integrationsServiceUrl entry required!" .integrationsServiceUrl }}
  {{- end}}
  FRONTEGG_AUTH_PUBLIC_KEY: "frontegg-api-key"
  FRONTEGG_ADMINS_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_AUDITS_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_AUTHENTICATION_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_METADATA_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_NOTIFICATION_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_REPORTS_ENGINE_API_KEY: "frontegg-api-key"
  FRONTEGG_REPORTS_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_TEAM_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_VENDORS_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_TENANT_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_WEBPUSH_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_FEATURE_FLAGS_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_WEBHOOK_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_EVENT_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_INTEGRATIONS_SERVICE_API_KEY:  "frontegg-api-key"
  FRONTEGG_IDENTITY_SERVICE_API_KEY: "frontegg-api-key"
  CLOUD_ENVIRONMENT: prod
