repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.15.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./cloudprem/network"]
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./cloudprem/compute"]
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./cloudprem/storage"]
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./cloudprem/app"]
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.51.0"
    hooks:
      - id: terraform_fmt