repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./terraform/physical"]
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./terraform/logical"]
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.62.2"
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--enable-rule=terraform_documented_variables