apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webhook-service.fullname" . }}-secret
  labels:
  {{- include "webhook-service.labels" . | nindent 4 }}
data:
  {{- with .Values.mongo }}
  FRONTEGG_WEBHOOK_SERVICE_MONGODB_URL: {{ required "A valid .Values.mongo.connectionString entry required!" .connectionString | b64enc | quote  }}
  FRONTEGG_WEBHOOK_SERVICE_MONGODB_CONNECTION_RETRY_ATTEMPTS: {{ required "A valid .Values.mongo.retryAttempts entry required!" .retryAttempts | b64enc | quote  }}
  FRONTEGG_WEBHOOK_SERVICE_MONGODB_CONNECTION_RETRY_DELAY: {{ required "A valid .Values.mongo.retryDelay entry required!" .retryDelay | b64enc | quote  }}
  {{- end }}
  {{- with .Values.messageBroker }}
  FRONTEGG_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote }}
  FRONTEGG_EVENTS_PUBSUB_TOPIC: {{ required "A valid .Values.messageBroker.topic entry required!" .topic | b64enc | quote  }}
  {{- end }}
  {{- with .Values.mysql}}
  FRONTEGG_WEBHOOK_MYSQL_DB_NAME: {{ required "A valid .Values.mysql. entry required!" .name | b64enc | quote  }}
  FRONTEGG_WEBHOOK_MYSQL_DB_HOST: {{ required "A valid .Values.mysql. entry required!" .host | b64enc | quote  }}
  FRONTEGG_WEBHOOK_MYSQL_DB_USERNAME: {{ .username | b64enc | quote }}
  FRONTEGG_WEBHOOK_MYSQL_DB_PASSWORD: {{ .password | b64enc | quote }}
  {{- end }}

