kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "event-service.fullname" . }}-configmap
  labels:
  {{- include "event-service.labels" . | nindent 4 }}
data:
  CLOUD_ENVIRONMENT: production
  NODE_ENV: production
  PORT: "3011"
  FRONTEGG_SERVICE_NAME: event-service
  FRONTEGG_EVENT_SERVICE_API_KEY: "frontegg-api-key"
