package harness

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func RenderEnvHCL(inputs map[string]interface{}) string {
	keys := make([]string, 0, len(inputs))
	for k := range inputs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by the upgrade-test harness. Do not edit.\n")
	b.WriteString("locals {\n")
	for _, k := range keys {
		b.WriteString("  " + k + " = " + hclValue(inputs[k]) + "\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func hclValue(v interface{}) string {
	switch t := v.(type) {
	case bool:
		return fmt.Sprintf("%t", t)
	case string:
		return fmt.Sprintf("%q", t)
	case int:
		return fmt.Sprintf("%d", t)
	case int64:
		return fmt.Sprintf("%d", t)
	case float64:
		// YAML decodes unquoted numbers as float64; render whole numbers
		// without a trailing .0 so they remain valid HCL numbers.
		if t == float64(int64(t)) {
			return fmt.Sprintf("%d", int64(t))
		}
		return strconv.FormatFloat(t, 'f', -1, 64)
	default:
		return fmt.Sprintf("%q", fmt.Sprintf("%v", t))
	}
}

func WriteEnvHCL(envDir string, inputs map[string]interface{}) error {
	if err := os.MkdirAll(envDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(envDir, "env.hcl"), []byte(RenderEnvHCL(inputs)), 0o644)
}
