
webhook-service:
  mongo:
    connectionString: "mongodb://frontegg-documents-mongodb/webhooks"

integrations-service:
  mongo:
    connectionString: "mongodb://frontegg-documents-mongodb/integrations"
  frontegg:
    slack:
      encryptionKey: "dummyval"

event-service:
  redis:
    host: "frontegg-kvstore-redis-master"
    tls: "false"
  frontegg:
    sync:
      enabled: "false"
    authenticationUrl: "https://api.frontegg.com/auth/vendor"

connectors-worker:
  redis:
    host: "frontegg-kvstore-redis-master"
    tls: "false"
  frontegg:
    channels: "slack"
    emails:
      provider: "sendgrid"
      sendgrid:
        apiKey: "dummyval"