#!/usr/bin/env bash
# MPC Azure deploy driver. Usage: ./bootstrap.sh init|physical|logical|status|all
# shellcheck disable=SC1091  # libs are checked separately via shellcheck -x
set -euo pipefail
cd "$(dirname "$0")"
source lib/common.sh
source lib/tools.sh
source lib/auth.sh
source lib/state.sh

PHYS_TFVARS="${KIT_ROOT}/physical.tfvars"
LOG_TFVARS="${KIT_ROOT}/logical.tfvars"

usage() { die "usage: $0 init|physical|logical|status|all"; }

# Set MPC_AUTO_APPROVE=1 to skip interactive confirmation (unattended runs).
_confirm_apply() { # description
  [[ "${MPC_AUTO_APPROVE:-0}" == "1" ]] && return 0
  local reply
  read -r -p "Apply the $1 plan shown above? Type yes to continue: " reply
  [[ "$reply" == "yes" ]] || die "aborted by operator"
}

_load_config() {
  need_file "$PHYS_TFVARS" "physical.tfvars not found - copy physical.tfvars.example and fill it in"
  need_file "$LOG_TFVARS"  "logical.tfvars not found - copy logical.tfvars.example and fill it in"
  SUBSCRIPTION="$(tfvar "$PHYS_TFVARS" subscription_id)"
  AZ_ENV="$(tfvar "$PHYS_TFVARS" azure_environment)"
  TENANT="$(tfvar "$PHYS_TFVARS" tenant_id)"
  CUSTOMER="$(tfvar "$PHYS_TFVARS" customer)"
  ENVIRONMENT="$(tfvar "$PHYS_TFVARS" environment)"
  LOCATION="$(tfvar "$PHYS_TFVARS" location)"
  [[ -n "$SUBSCRIPTION" && -n "$CUSTOMER" && -n "$LOCATION" ]] \
    || die "physical.tfvars is missing required values (subscription_id, customer, location)"
}

# True if KEY in FILE is a non-empty list (operator set explicit values).
_tfvar_list_set() { # file key
  grep -E "^[[:space:]]*$2[[:space:]]*=" "$1" | grep -vE '=\s*\[\s*\]\s*(#.*)?$' | grep -q .
}

phase_init() {
  _load_config
  ensure_tools
  azure_login "$SUBSCRIPTION" "$AZ_ENV" "$TENANT"

  # Refresh deployer egress IP into the firewall allowlists (idempotent),
  # unless the operator set explicit allowlists in physical.tfvars.
  local ip
  if _tfvar_list_set "$PHYS_TFVARS" kv_allowed_cidrs || _tfvar_list_set "$PHYS_TFVARS" aks_api_allowed_cidrs; then
    log "allowlists set in physical.tfvars - skipping egress IP auto-detection"
    rm -f "${STATE_DIR}/deployer.auto.tfvars"
  elif ip="$(egress_ip)"; then
    log "deployment egress IP: ${ip}"
    mkdir -p "${STATE_DIR}"
    cat > "${STATE_DIR}/deployer.auto.tfvars" <<EOF
# Generated by bootstrap.sh init - do not edit.
kv_allowed_cidrs      = ["${ip}"]
aks_api_allowed_cidrs = ["${ip}"]
EOF
  else
    warn "could not detect egress IP - set kv_allowed_cidrs in physical.tfvars manually"
  fi

  ensure_state_backend "$CUSTOMER" "$ENVIRONMENT" "$LOCATION" "$AZ_ENV"
  write_aws_stub
  log "init complete"
}

_tf() { # dir args...
  local dir="$1"; shift
  terraform -chdir="$dir" "$@"
}

phase_physical() {
  _load_config
  _tf "$PHYSICAL_DIR" init -upgrade -input=false
  local extra=()
  [[ -f "${STATE_DIR}/deployer.auto.tfvars" ]] && extra+=(-var-file="${STATE_DIR}/deployer.auto.tfvars")
  _tf "$PHYSICAL_DIR" plan -input=false -out=tfplan -var-file="$PHYS_TFVARS" "${extra[@]}"
  _confirm_apply "physical"
  _tf "$PHYSICAL_DIR" apply -input=false tfplan
  rm -f "${PHYSICAL_DIR}/tfplan"
  log "physical layer applied"
}

# Wire physical outputs into the logical layer (replaces terragrunt's
# dependency block on AWS).
_write_wiring() {
  local out="${STATE_DIR}/logical.physical.auto.tfvars"
  mkdir -p "${STATE_DIR}"
  o() { _tf "$PHYSICAL_DIR" output -raw "$1" 2>/dev/null || printf ''; }
  cat > "$out" <<EOF
# Generated by bootstrap.sh from physical outputs - do not edit.
eks_cluster_id               = "$(o cluster_name)"
azure_resource_group         = "$(o resource_group_name)"
azure_key_vault_id           = "$(o key_vault_id)"
azure_key_vault_uri          = "$(o key_vault_uri)"
azure_tenant_id              = "$(o tenant_id)"
azure_eso_identity_client_id = "$(o eso_identity_client_id)"
s3_images_bucket             = "$(o guide_images_bucket)"
s3_objects_bucket            = "$(o guide_objects_bucket)"
s3_pdfs_bucket               = "$(o guide_pdfs_bucket)"
s3_documents_bucket          = "$(o documents_bucket)"
EOF
  grep -q 'eks_cluster_id               = ""' "$out" \
    && die "physical outputs missing (cluster_name empty) - did the physical phase complete?"
  log "wired physical outputs -> ${out}"
}

# Chart + images pull directly from GHCR; one credential file feeds the helm
# registry login and the cluster's image pull secret (TF_VARs below).
_ghcr_helm_login() {
  local env_file="${KIT_ROOT}/ghcr.env"
  need_file "$env_file" "ghcr.env not found - copy ghcr.env.example and fill in the credentials provided by Dozuki"
  # shellcheck disable=SC1090
  source "$env_file"
  [[ -n "${GHCR_USER:-}" && -n "${GHCR_TOKEN:-}" ]] || die "GHCR_USER / GHCR_TOKEN not set in ghcr.env"
  printf '%s' "$GHCR_TOKEN" | helm registry login ghcr.io --username "$GHCR_USER" --password-stdin >/dev/null
  export TF_VAR_ghcr_pull_username="$GHCR_USER"
  export TF_VAR_ghcr_pull_token="$GHCR_TOKEN"
  log "ghcr credentials loaded for ${GHCR_USER}"
}

phase_logical() {
  _load_config
  _write_wiring
  _ghcr_helm_login
  export VAULT_ADDR="${VAULT_ADDR:-http://vault.invalid}"
  _tf "$LOGICAL_DIR" init -upgrade -input=false
  _tf "$LOGICAL_DIR" plan -input=false -out=tfplan \
    -var-file="$LOG_TFVARS" -var-file="${STATE_DIR}/logical.physical.auto.tfvars"
  _confirm_apply "logical"
  _tf "$LOGICAL_DIR" apply -input=false tfplan
  rm -f "${LOGICAL_DIR}/tfplan"
  log "logical layer applied"
  phase_status
}

phase_status() {
  _load_config
  "${KIT_ROOT}/status.sh"
}

case "${1:-}" in
  init)        phase_init ;;
  physical)    phase_init; phase_physical ;;
  logical)     phase_init; phase_logical ;;
  status)      phase_status ;;
  all)         phase_init; phase_physical; phase_logical ;;
  *)           usage ;;
esac
