#!/usr/bin/env bash
# CloudPrem Azure deploy driver. Usage: ./bootstrap.sh init|physical|sync-images|logical|status|all
# shellcheck disable=SC1091  # libs are checked separately via shellcheck -x
set -euo pipefail
cd "$(dirname "$0")"
source lib/common.sh
source lib/tools.sh
source lib/auth.sh
source lib/state.sh

PHYS_TFVARS="${KIT_ROOT}/physical.tfvars"
LOG_TFVARS="${KIT_ROOT}/logical.tfvars"

usage() { die "usage: $0 init|physical|sync-images|logical|status|all"; }

_load_config() {
  need_file "$PHYS_TFVARS" "physical.tfvars not found - copy physical.tfvars.example and fill it in"
  need_file "$LOG_TFVARS"  "logical.tfvars not found - copy logical.tfvars.example and fill it in"
  SUBSCRIPTION="$(tfvar "$PHYS_TFVARS" subscription_id)"
  AZ_ENV="$(tfvar "$PHYS_TFVARS" azure_environment)"
  CUSTOMER="$(tfvar "$PHYS_TFVARS" customer)"
  ENVIRONMENT="$(tfvar "$PHYS_TFVARS" environment)"
  LOCATION="$(tfvar "$PHYS_TFVARS" location)"
  [[ -n "$SUBSCRIPTION" && -n "$CUSTOMER" && -n "$LOCATION" ]] \
    || die "physical.tfvars is missing required values (subscription_id, customer, location)"
}

phase_init() {
  _load_config
  ensure_tools
  azure_login "$SUBSCRIPTION" "$AZ_ENV"

  # Refresh deployer egress IP into the firewall allowlists (idempotent).
  local ip
  if ip="$(egress_ip)"; then
    log "deployment egress IP: ${ip}"
    mkdir -p "${STATE_DIR}"
    cat > "${STATE_DIR}/deployer.auto.tfvars" <<EOF
# Generated by bootstrap.sh init - do not edit.
kv_allowed_cidrs      = ["${ip}"]
aks_api_allowed_cidrs = ["${ip}"]
EOF
  else
    warn "could not detect egress IP - set kv_allowed_cidrs in physical.tfvars manually"
  fi

  ensure_state_backend "$CUSTOMER" "$ENVIRONMENT" "$LOCATION"
  write_aws_stub
  log "init complete"
}

_tf() { # dir args...
  local dir="$1"; shift
  terraform -chdir="$dir" "$@"
}

phase_physical() {
  _load_config
  _tf "$PHYSICAL_DIR" init -upgrade -input=false
  local extra=()
  [[ -f "${STATE_DIR}/deployer.auto.tfvars" ]] && extra+=(-var-file="${STATE_DIR}/deployer.auto.tfvars")
  _tf "$PHYSICAL_DIR" apply -input=false -var-file="$PHYS_TFVARS" "${extra[@]}"
  log "physical layer applied"
}

# Wire physical outputs into the logical layer (replaces terragrunt's
# dependency block on AWS).
_write_wiring() {
  local out="${STATE_DIR}/logical.physical.auto.tfvars"
  mkdir -p "${STATE_DIR}"
  o() { _tf "$PHYSICAL_DIR" output -raw "$1" 2>/dev/null || printf ''; }
  cat > "$out" <<EOF
# Generated by bootstrap.sh from physical outputs - do not edit.
eks_cluster_id               = "$(o cluster_name)"
azure_resource_group         = "$(o resource_group_name)"
azure_key_vault_id           = "$(o key_vault_id)"
azure_key_vault_uri          = "$(o key_vault_uri)"
azure_tenant_id              = "$(o tenant_id)"
azure_eso_identity_client_id = "$(o eso_identity_client_id)"
s3_images_bucket             = "$(o guide_images_bucket)"
s3_objects_bucket            = "$(o guide_objects_bucket)"
s3_pdfs_bucket               = "$(o guide_pdfs_bucket)"
s3_documents_bucket          = "$(o documents_bucket)"
EOF
  log "wired physical outputs -> ${out}"
}

phase_logical() {
  _load_config
  _write_wiring
  export VAULT_ADDR="${VAULT_ADDR:-http://vault.invalid}"
  _tf "$LOGICAL_DIR" init -upgrade -input=false
  _tf "$LOGICAL_DIR" apply -input=false \
    -var-file="$LOG_TFVARS" -var-file="${STATE_DIR}/logical.physical.auto.tfvars"
  log "logical layer applied"
  phase_status
}

phase_sync_images() {
  _load_config
  "${KIT_ROOT}/sync-images.sh"
}

phase_status() {
  _load_config
  "${KIT_ROOT}/status.sh"
}

case "${1:-}" in
  init)        phase_init ;;
  physical)    phase_init; phase_physical ;;
  sync-images) phase_sync_images ;;
  logical)     phase_init; phase_logical ;;
  status)      phase_status ;;
  all)         phase_init; phase_physical; phase_sync_images; phase_logical ;;
  *)           usage ;;
esac
