{
 "title": "Content Activity",
 "tags": [
  "Content",
  "Content Activity"
 ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "GUIDE_DB", "label": "Guide Database", "query": "mysql" },
   {
    "name": "USERID",
    "label": "User",
    "query": "select  CONCAT(global_users.username, \" — \", \"User ID:\", global_users.userid) AS __text, global_users.userid AS __value from global_users"
   },
   {
    "name": "GUIDE_ID",
    "label": "Guide",
    "query": "select guide_text.guideid AS __value,  CONCAT(guide_text.title, \" — \", \"Guide ID:\", guide_text.guideid) AS __text   from (select max(gt_revisionid) as gt_revisionid, guideid from guide_text group by guideid) x  left join guide_text on guide_text.gt_revisionid=x.gt_revisionid"
   },
   {
    "name": "CATEGORYID",
    "label": "Category",
    "query": "select  \"All Categories\", list.title as \"Category\" from (select distinct title from wikis where wikis.namespace=\"TOPIC\") list order by 'All Categories', title ASC"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "content": "# Content Activity\nUser activity on guides, wikis, and categories."
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 }, "content": "<h1>Monthly Overview\n<hr>" },
  {
   "title": "New Guides This Month",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT -- date(FROM_UNIXTIME(user_history.date)) AS date_group,\n       count(*)\nFROM user_history\n\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \nuser_history.event = 'new_guide'\n\nand year(FROM_UNIXTIME(user_history.date)) = year(CURRENT_TIME)\nand month(FROM_UNIXTIME(user_history.date)) = month(CURRENT_TIME)"
    }
   ]
  },
  {
   "title": "Monthly Guide Views",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(std.value) AS 'Views'\n\nfrom stats_per_day std\t\t\t\t     \nwhere \nstd.key <= DAY(CURRENT_TIME)\nand \nstd.type ='guide'\nORDER BY `Views` DESC\n;"
    }
   ]
  },
  {
   "title": "Monthly Category Views",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(std.value) AS 'Views'\n\nfrom stats_per_day std\t\t\t\t     \nwhere \nstd.key <= DAY(CURRENT_TIME)\nand \nstd.type ='TOPIC'\nORDER BY `Views` DESC\n;"
    }
   ]
  },
  {
   "title": "Monthly Wiki Views",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(std.value) AS 'Views'\n\nfrom stats_per_day std\t\t\t\t     \nwhere \nstd.key <= DAY(CURRENT_TIME)\nand \nstd.type ='wiki'\nORDER BY `Views` DESC\n;"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 }, "content": "<h1>New Guides\n<hr>" },
  {
   "title": "New Guides by Month",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "locale", "label": "New Guides" }
   ],
   "targets": [
    {
     "rawSql": "SELECT user_history.date as time, \n\n \nconcat(monthname(FROM_UNIXTIME(user_history.date)),\" \",year(FROM_UNIXTIME(user_history.date))) as metric,\n       count(historyid) as value\nFROM user_history\n\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \nuser_history.event = 'new_guide'\n\nand\n\nCASE\nWHEN $USERID != 'All Users'\nTHEN user_history.userid = $USERID\nelse 1=1\nend\n\nand\n\nFROM_UNIXTIME(user_history.date) >= $__timeFrom()\n\n\nand \n\nFROM_UNIXTIME(user_history.date) <= $__timeTo()\n\nGROUP BY \n\nyear(FROM_UNIXTIME(user_history.date)), month(FROM_UNIXTIME(user_history.date))\n\n\n\n-- order by \n\n-- year(FROM_UNIXTIME(user_history.date)) asc, month(FROM_UNIXTIME(user_history.date))\n;\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 }, "content": "<hr>" },
  {
   "title": "New Guides by User",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT DATE_FORMAT(FROM_UNIXTIME(user_history.date), \"%M-%Y\") AS date_group, global_users.username, \n       count(historyid) as \"New Guides\"\nFROM user_history\nleft join global_users on global_users.userid = user_history.userid\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \nuser_history.event = 'new_guide'\n-- and\n-- userid= {USERID}\nand\n\nCASE\nWHEN $USERID != 'All Users'\nTHEN user_history.userid = $USERID\nelse 1=1\nend\n\nand\n\n\ndate(FROM_UNIXTIME(user_history.date)) >= $__timeFrom()\n\n\nand \n\n\ndate(FROM_UNIXTIME(user_history.date)) <= $__timeTo()\n\n\nGROUP BY user_history.userid, DATE_FORMAT(FROM_UNIXTIME(user_history.date), \"%M-%Y\")\n\norder by year(FROM_UNIXTIME(user_history.date)) desc, month(FROM_UNIXTIME(user_history.date)) desc, day(date_group) desc, user_history.userid;"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 }, "content": "<h1>Guide Edits\n<hr>" },
  {
   "title": "Guide Edits by Month",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "locale", "label": "Recent Edits to Guides" }
   ],
   "targets": [
    {
     "rawSql": "SELECT gr.date as time_sec, \n\n-- \"Edits\" as metric,\nconcat(monthname(FROM_UNIXTIME(gr.date)),\" \", year(FROM_UNIXTIME(gr.date))) as metric,\n\n       count(gr.guide_revisionid) as value\nFROM guide_revisions gr\n\n-- left JOIN guide_current gc on (gc.guide_revisionid=gr.guide_revisionid)\n-- left JOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid) and (gc.guide_revisionid=gr.guide_revisionid)\n-- left JOIN guide_text gt ON (gt.gt_revisionid = gr.gt_revisionid) and (gc.guide_revisionid=gr.guide_revisionid)\n\n\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \n\n\nCASE\nWHEN $GUIDE_ID != 'All Guides'\nTHEN gr.guideid = $GUIDE_ID\nelse 1=1\nend\n\nand\n\nFROM_UNIXTIME(gr.date) >= $__timeFrom()\n\nand \n\nFROM_UNIXTIME(gr.date) <= $__timeTo()\n\nGROUP BY \n\n\nyear(FROM_UNIXTIME(gr.date)), month(FROM_UNIXTIME(gr.date))\n\n;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 }, "content": "<hr>" },
  {
   "title": "Guide Edits Over Time",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT DATE_FORMAT(FROM_UNIXTIME(gr.date), \"%M-%Y\") AS date_group, \n\nCASE\nWHEN a.guide_revisionid != ''\nTHEN a.title\nelse \"Deleted Guide\"\nend\nas title\n, \n\ngr.guideid as \"Guide ID\",\n       count(gr.guide_revisionid) as Edits\n\n\n\nFROM guide_revisions gr\n\n \n-- left JOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid) and (gc.guide_revisionid=gr.guide_revisionid)\n\nleft join \n(select guide_text.title, \n -- guide_text.gt_revisionid, \nguide_current.guide_revisionid, \n guide_revisions.guideid  \n \n from guide_current\n \nleft join guide_revisions on guide_current.guide_revisionid= guide_revisions.guide_revisionid\n \nleft join guide_text on guide_text.gt_revisionid = guide_revisions.gt_revisionid) \n \n a on a.guideid = gr.guideid\n\t\t   \n\t\t   \n\t\t   \nleft JOIN guide_text gt ON (gt.gt_revisionid = gr.gt_revisionid)\n\n-- left JOIN global_users on gm.userid = global_users.userid\n\n\nwhere \n\nCASE\nWHEN $GUIDE_ID != 'All Guides'\nTHEN gr.guideid = $GUIDE_ID\nelse 1=1\nend\n\n\nand \n\n\ndate(FROM_UNIXTIME(gr.date)) >= $__timeFrom()\n\nand \n\n\ndate(FROM_UNIXTIME(gr.date)) <= $__timeTo()\n\n\n\n\n\n\nGROUP BY gr.guideid,\n\ndate_group\n\norder by year(FROM_UNIXTIME(gr.date)) desc, month(FROM_UNIXTIME(gr.date)) desc\n\n\n\n\n;"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 63 }, "content": "<h1>Content Views\n<hr>" },
  {
   "title": "Total Views by Month",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "locale", "label": "Views" }
   ],
   "targets": [
    {
     "rawSql": "SELECT timestamp(concat(stm.year,\"-\",stm.key,\"-\",\"2\"), \"00:00:00\") as time, \n-- stm.year, stm.key, \nsum(stm.value) AS value, \"Guide Views\" as metric\n\nFROM stats_per_month stm\nWHERE\nmetric = 'hits'\nAND type = 'guide'\n\nAND id IN (\n   SELECT gc.guideid\n   FROM guide_current gc\n   JOIN guide_revisions gr USING (guide_revisionid)\n   JOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\n)\n\nand\n\nstm.year >= year($__timeFrom())\n\nand \n\nstm.year <= year($__timeTo())\n\n-- and\n\n-- CASE \n-- WHEN stm.year = year($__timeTo()) \n-- THEN stm.key <= month($__timeTo())\n-- else 1=1\n-- end\n\n-- and \n\n-- CASE \n-- WHEN stm.year = year($__timeFrom())\n-- THEN stm.key >= month($__timeFrom())\n-- else 1=1\n-- end\n\n\n\nGROUP BY stm.year, stm.key\n"
    },
    {
     "rawSql": "SELECT timestamp(concat(stm.year,\"-\",stm.key,\"-\",\"2\"), \"00:00:00\") as time, \n-- stm.year, stm.key, \nsum(stm.value) AS value, \"Category Views\" as metric\n\nFROM stats_per_month stm\nWHERE\nmetric = 'hits'\nAND type = 'TOPIC'\nAND id IN (\n   SELECT gc.guideid\n   FROM guide_current gc\n   JOIN guide_revisions gr USING (guide_revisionid)\n   JOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\n)\n\nand\n\nstm.year >= year($__timeFrom())\n\nand \n\nstm.year <= year($__timeTo())\n\nand\n\nCASE \nWHEN stm.year = year($__timeTo()) \nTHEN stm.key <= month($__timeTo())\nelse 1=1\nend\n\nand \n\nCASE \nWHEN stm.year = year($__timeFrom())\nTHEN stm.key >= month($__timeFrom())\nelse 1=1\nend\n\n\nGROUP BY stm.year, stm.key\n"
    },
    {
     "rawSql": "SELECT timestamp(concat(stm.year,\"-\",stm.key,\"-\",\"2\"), \"00:00:00\") as time, \n-- stm.year, stm.key, \nsum(stm.value) AS value, \"WIKI Views\" as metric\n\nFROM stats_per_month stm\nWHERE\nmetric = 'hits'\nAND type = 'WIKI'\nAND id IN (\n   SELECT gc.guideid\n   FROM guide_current gc\n   JOIN guide_revisions gr USING (guide_revisionid)\n   JOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\n)\n\nand\n\nstm.year >= year($__timeFrom())\n\nand \n\nstm.year <= year($__timeTo())\n\n\nand\nCASE \nWHEN stm.year = year($__timeTo()) \nTHEN stm.key <= month($__timeTo())\nelse 1=1\nend\n\nand \n\nCASE \nWHEN stm.year = year($__timeFrom())\nTHEN stm.key >= month($__timeFrom())\nelse 1=1\nend\n\nGROUP BY stm.year, stm.key\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 77 }, "content": "<hr>" },
  {
   "title": "Views by Guide",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT\n a.title, a.guideid, concat(MONTHNAME(STR_TO_DATE(stm.key, '%m')),\" , \",stm.year) as \"Month\",\n\n\t   stm.value AS 'Views'\nFROM\n(SELECT gc.guideid, \n \t\tfrom_unixtime(gm.published_date,'%Y-%m-%d') AS 'published_date',\n\t   gm.device,\n \t   group_concat(distinct(if(gt.langid='en',gt.thing,NULL))) AS 'thing',\n\t   group_concat(distinct(if(gt.langid='en',gt.title,NULL))) AS 'title'\nFROM guide_current gc\nJOIN guide_revisions gr on gr.guide_revisionid = gc.guide_revisionid\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nJOIN guide_text gt ON (gt.gt_revisionid = gr.gt_revisionid)\n\nGROUP BY gc.guideid\nORDER BY gc.guideid desc) a\n\nJOIN stats_per_month stm ON (stm.id = a.guideid AND \n\t\t\t\t\t\t     stm.metric='hits' AND stm.type='guide')\n\t\t\t\t\t\t     \nwhere \n\n\nCASE\nWHEN $GUIDE_ID != 'All Guides'\nTHEN a.guideid = $GUIDE_ID\nelse 1=1\nend\n\n\nand \nstm.year >= year($__timeFrom())\n\nand \n\nstm.year <= year($__timeTo())\n\nand \n\nCASE \nWHEN stm.year = year($__timeTo()) \nTHEN stm.key <= month($__timeTo())\nelse 1=1\nend\n\nand \n\nCASE \nWHEN stm.year = year($__timeFrom())\nTHEN stm.key >= month($__timeFrom())\nelse 1=1\nend\n\n\n\n\n\n\nand\n\n-- stm.key <= MONTH(CURRENT_TIME)\n-- and stm.year = Year(CURRENT_TIME)\n-- and \nstm.key <> 0\nand stm.value <> 0\nGROUP BY a.guideid, concat(MONTHNAME(STR_TO_DATE(stm.key, '%m')),\" , \",stm.year) \nORDER BY stm.year desc, stm.key desc, a.guideid\n;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 }, "content": "<hr>" },
  {
   "title": "Views by Category",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "rawSql": "SELECT\nw.title, concat(MONTHNAME(STR_TO_DATE(stm.key, '%m')),\" , \",stm.year) as \"Month\",\n\n\t   stm.value AS 'Views'\nFROM wikis w\nJOIN stats_per_month stm ON (stm.id = w.wikiid AND \n\t\t\t\t\t\t     stm.metric='hits' AND stm.type='topic')\n\t\t\t\t\t\t     \nwhere \nstm.key <> 0\nand stm.value <> 0\n\n\n\nand \nstm.year >= year($__timeFrom())\n\nand \n\nstm.year <= year($__timeTo())\n\nand \n\n\n\nCASE \n\tWHEN concat($CATEGORYID) = 'All Categories'\n\tTHEN 1 = 1 \n\tELSE w.title=$CATEGORYID\nEND\n\nand\n\nCASE \nWHEN stm.year = year($__timeTo()) \nTHEN stm.key <= month($__timeTo())\nelse 1=1\nend\n\nand \n\nCASE \nWHEN stm.year = year($__timeFrom())\nTHEN stm.key >= month($__timeFrom())\nelse 1=1\nend\n\n\nGROUP BY w.wikiid, concat(MONTHNAME(STR_TO_DATE(stm.key, '%m')),\" , \",stm.year) \nORDER BY stm.year desc, stm.key desc, w.wikiid\n;"
    }
   ]
  }
 ]
}