{
 "title": "User Activity",
 "description": "A snapshot of user activity",
 "tags": [
  "User Activity",
  "Site Usage"
 ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "GUIDE_DB", "label": "Guide Database", "query": "mysql" },
   {
    "name": "TEAM",
    "label": "Team",
    "query": " select CONCAT(name, \" — \", \"Team ID:\", teamid) AS __text, teamid AS __value FROM teams"
   },
   {
    "name": "USERID",
    "label": "User",
    "query": "select  CONCAT(global_users.username, \" — \", \"User ID:\", global_users.userid) AS __text, global_users.userid AS __value from global_users where userid in (select userid from user_teams where ($TEAM=teamid or $TEAM='All Teams'))"
   },
   {
    "name": "CATEGORYID",
    "label": "Category",
    "query": "select  \"All Categories\", list.title as \"Category\" from (select distinct title from wikis where wikis.namespace=\"TOPIC\") list order by 'All Categories', title ASC"
   },
   {
    "name": "GUIDE_ID",
    "label": "Guide",
    "query": "select guide_text.guideid AS __value,   CONCAT(guide_text.title, \" — \", \"Guide ID:\",  guide_text.guideid) AS __text    from guide_current \nleft join guide_revisions using(guide_revisionid)\nleft join guide_text using(gt_revisionid)\nleft JOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\n\nwhere device in (select device from guide_meta where ($CATEGORYID=device or $CATEGORYID='All Categories'))\n\n\n"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "description": "User View History is required for any view statistics on these panels. To enable User View History for your account, contact your Customer Success Manager.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# User Activity Report\nA snapshot of user activity"
   },
   "content": "# Site Usage Monitor\nA snapshot of user activity"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 }, "options": { "content": "<h1> User Distribution\n<hr>" }, "content": "<h1> Key Metrics\n<hr>" },
  {
   "title": "Number of Users",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT \r\nCASE p.description \r\n\tWHEN \"Administrator\"\r\n\tTHEN p.description \r\n\tWHEN \"Expert\"\r\n\tTHEN p.description \r\n\tWHEN \"Answers Moderator\"\r\n\tTHEN \"Moderator\"\r\n\tWHEN \"Guide Moderator\"\r\n\tTHEN \"Author\" \r\n\tWHEN \"Full Moderator\"\r\n\tTHEN \"Author & Mod\"\r\n\tWHEN \"Basic Moderator\"\r\n\tTHEN p.description \r\n\tWHEN \"Contributor\"\r\n\tTHEN p.description \r\nEND as \"User Type\", \r\nu.join_date*1000 as time_sec,\r\ncount(*) as \"# of Users\"\r\nFROM global_users u\r\nLEFT JOIN user_privileges up on u.userid = up.userid\r\nLEFT JOIN privileges p on up.privilegeid = p.privilegeid\r\nWHERE up.privilegeid is not null\r\nAND u.enabled = 1\r\nand u.login not like \"%@ifixit.com\"\r\nand u.login not like \"%@dozuki.com\"\r\nand ($TEAM = 'All Teams' OR u.userid in (select userid from user_teams where user_teams.teamid=$TEAM))\r\nand ($USERID = 'All Users' OR u.userid = $USERID)\r\nGROUP BY p.description\r\n\r\nunion all\r\n\r\nSELECT \"Standard User\" as \"User Type\",\r\nu.join_date*1000 as time_sec,\r\ncount(*) as \"# of Users\"\r\nFROM global_users u\r\nLEFT JOIN user_privileges up on u.userid = up.userid\r\nLEFT JOIN privileges p on up.privilegeid = p.privilegeid\r\nWHERE up.privilegeid is null\r\nAND u.enabled = 1\r\nand u.login not like \"%@ifixit.com\"\r\nand u.login not like \"%@dozuki.com\"\r\nand ($TEAM = 'All Teams' OR u.userid in (select userid from user_teams where user_teams.teamid=$TEAM))\r\nand ($USERID = 'All Users' OR u.userid = $USERID)\r\n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM global_users u\nLEFT JOIN user_privileges up on u.userid = up.userid\nLEFT JOIN privileges p on up.privilegeid = p.privilegeid\nWHERE  u.enabled =1\nand ($TEAM = 'All Teams' OR u.userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR u.userid = $USERID)\nand u.login not like \"%@ifixit.com\"\nand u.login not like \"%@dozuki.com\""
    }
   ]
  },
  {
   "title": "New Users",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT u.join_date as time_sec, count(*) as \"New Users\"\nFROM global_users u\nWHERE u.enabled = 1\nand u.login not like \"%@ifixit.com\"\nand u.login not like \"%@dozuki.com\"\nand ($TEAM = 'All Teams' OR u.userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR u.userid = $USERID)\nGROUP BY date_format(from_unixtime(u.join_date), \"%m-%y\")\norder by from_unixtime(u.join_date) asc"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM global_users u\nLEFT JOIN user_privileges up on u.userid = up.userid\nLEFT JOIN privileges p on up.privilegeid = p.privilegeid\nWHERE  u.enabled =0\nand ($TEAM = 'All Teams' OR u.userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR u.userid = $USERID)\nand u.login not like \"%@ifixit.com\"\nand u.login not like \"%@dozuki.com\""
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "Select count(distinct inviteid) from user_invites\nwhere user_invites.email not like \"%dozuki.com%\"\nand user_invites.email not like \"%ifixit.com%\"\n"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 }, "options": { "content": "<h1> Recent Activity\n<hr>" }, "content": "<h1> Recent Activity\n<hr>" },
  {
   "title": "New Guides Last 30 Days",
   "type": "singlestat",
   "description": "Filtered by teams, users, categories, and guides.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(historyid)\nFROM user_history\nleft join (SELECT guideid, revisionid, device, created_date from guide_meta where created_date between (UNIX_TIMESTAMP() - 2629743) and UNIX_TIMESTAMP() ) gm on user_history.docid=gm.revisionid\n\n\nwhere user_history.event = 'new_guide'\nand created_date between (UNIX_TIMESTAMP() - 2629743) and UNIX_TIMESTAMP()\nand ($TEAM = 'All Teams' OR user_history.userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR user_history.userid = $USERID)\nand ($CATEGORYID = 'All Categories' OR gm.device = $CATEGORYID)\nand ($GUIDE_ID = 'All Guides' or gm.guideid = $GUIDE_ID)"
    }
   ]
  },
  {
   "title": "Guide Views Last 30 Days",
   "type": "singlestat",
   "description": "Filtered by teams, users, categories, and guides.",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(historyid)\nFROM user_view_history\nleft join guide_current on guide_current.guideid=user_view_history.docid\nleft join guide_revisions using(guide_revisionid)\nleft join guide_meta on guide_revisions.gtr_revisionid=guide_meta.revisionid\n\n\nwhere \nuser_view_history.doc_type = 'GUIDE'\nand user_view_history.date between (UNIX_TIMESTAMP() - 2629743) and UNIX_TIMESTAMP()\n\nand ($TEAM = 'All Teams' OR user_view_history.userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR user_view_history.userid = $USERID)\nand ($CATEGORYID = 'All Categories' OR guide_meta.device = $CATEGORYID) \nand ($GUIDE_ID = 'All Guides' OR guide_meta.guideid = $GUIDE_ID) "
    }
   ]
  },
  {
   "title": "Category Views Last 30 Days",
   "type": "singlestat",
   "description": "Filtered by teams, users, and categories.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(historyid)\nFROM (select * from user_view_history \nwhere doc_type = 'WIKI'\nand date between (UNIX_TIMESTAMP() - 2629743) and UNIX_TIMESTAMP()\nand ($TEAM = 'All Teams' OR userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR userid = $USERID)\n) uvh\nINNER join (select wikiid as docid, title, namespace from wikis where namespace=\"TOPIC\") w using(docid)\n\n\n\n\nwhere ($CATEGORYID = 'All Categories' OR w.title = $CATEGORYID) \n"
    }
   ]
  },
  {
   "title": "Wiki Views Last 30 Days",
   "type": "singlestat",
   "description": "Filtered by teams, users, and categories.",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(historyid)\nFROM (select * from user_view_history \nwhere doc_type = 'WIKI'  \nand ($USERID = 'All Users' OR userid = $USERID)\nand ($TEAM = 'All Teams' OR userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand date between (UNIX_TIMESTAMP() - 2629743) and UNIX_TIMESTAMP()\n) uvh\n\nINNER join (select wikiid as docid, namespace from wikis where namespace=\"WIKI\") w using(docid)\n\n\nleft join (select wikiid, related_wikiid as docid from wiki_related) wr using(docid)\nleft join (select wikiid, title from wikis where namespace=\"TOPIC\") wt using(wikiid)\n\n\n\nwhere ($CATEGORYID = 'All Categories' OR wt.title = $CATEGORYID)"
    }
   ]
  },
  {
   "title": "Users Editing Content",
   "type": "singlestat",
   "description": "Filtered by teams and users.",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "Select count(distinct a.userid)\n-- ,a.userid, a.username, a.login, from_unixtime(edit_date) \n\nfrom\n\n(select user_history.userid, global_users.username, max(date) as edit_date, global_users.login from user_history  left join global_users on user_history.userid = global_users.userid group by user_history.userid ) a\n\nwhere edit_date BETWEEN '${__from:date:seconds}' AND '${__to:date:seconds}'\n\nand a.login not like \"%dozuki.com%\"\nand a.login not like \"%ifixit.com%\"\nand ($TEAM = 'All Teams' OR a.userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR a.userid = $USERID)\n-- group by userid\norder by userid asc"
    }
   ]
  },
  {
   "title": "Users Viewing Content",
   "type": "singlestat",
   "description": "Filtered by teams and users.",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "Select count(distinct a.userid)\n-- ,a.userid, from_unixtime(view_date) \n\nfrom\n\n(select user_view_history.userid, max(user_view_history.date) as view_date, global_users.login from user_view_history \n\nleft join global_users on user_view_history.userid = global_users.userid \n\nwhere user_view_history.date BETWEEN '${__from:date:seconds}' AND '${__to:date:seconds}'\n\n\ngroup by user_view_history.userid\n\n\n) a\n\nwhere  view_date BETWEEN '${__from:date:seconds}' AND '${__to:date:seconds}'\n\nand a.login not like \"%dozuki.com%\"\nand a.login not like \"%ifixit.com%\"\nand ($TEAM = 'All Teams' OR a.userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR a.userid = $USERID)\n-- group by userid"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 }, "options": { "content": "# User Views and Activity" }, "content": "# User Login History" },
  {
   "title": "User Views Over Time",
   "type": "graph",
   "description": "Filtered by teams, users, category, and date range.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select uvh.date*1000 as time_sec, \"Guide Views\" as metric, count(uvh.historyid) as value\n\n\nfrom (select * from user_view_history \nwhere ($TEAM = 'All Teams' OR userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR userid = $USERID)\nand doc_type=\"GUIDE\" \nand date BETWEEN '${__from:date:seconds}' AND '${__to:date:seconds}'\ngroup by userid, docid, date\n) uvh\n\ninner join \n(select userid, login, username \nfrom global_users \n\nwhere \n($USERID='All Users' or $USERID=userid) \nand login not like \"%dozuki.com%\"\nand login not like \"%ifixit.com%\" \nand ($TEAM = 'All Teams' OR userid in (select userid from user_teams where user_teams.teamid=$TEAM))\n) gu using (`userid`)\nleft join (select guideid as docid, max(revisionid) as maxrev from guide_meta group by guideid) mr using(docid)\nleft join (select guideid as docid, revisionid as maxrev, device from guide_meta group by revisionid) gm using(maxrev)\n\nwhere \n\n\n($CATEGORYID = 'All Categories' OR gm.device = $CATEGORYID)\n\ngroup by date_format(from_unixtime(uvh.date), \"%m-%y\")\n\norder by uvh.date asc\n\n-- left join (select userid, historyid, date from user_view_history group by historyid) uvh on uvh.userid = u.userid"
    },
    {
     "rawSql": "select uvh.date*1000 as time_sec, \"Wiki Views\" as metric, count(uvh.historyid) as value\n\n\nfrom (select * from user_view_history \nwhere ($TEAM = 'All Teams' OR userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR userid = $USERID)\nand doc_type=\"WIKI\" \nand date BETWEEN '${__from:date:seconds}' AND '${__to:date:seconds}'\ngroup by userid, docid, date\n) uvh\n\ninner join \n(select userid, login, username \nfrom global_users \n\nwhere \n($USERID='All Users' or $USERID=userid) \nand login not like \"%dozuki.com%\"\nand login not like \"%ifixit.com%\" \nand ($TEAM = 'All Teams' OR userid in (select userid from user_teams where user_teams.teamid=$TEAM))\n) gu using (`userid`)\n\nINNER join (select wikiid as docid, namespace from wikis where namespace=\"WIKI\") w using(docid)\nleft join (select wikiid, related_wikiid as docid from wiki_related) wr using(docid)\nleft join (select wikiid, title from wikis where namespace=\"TOPIC\") wt using(wikiid)\n\nwhere ($CATEGORYID = 'All Categories' OR wt.title = $CATEGORYID)\n\ngroup by date_format(from_unixtime(uvh.date), \"%m-%y\")\n\norder by uvh.date asc\n\n-- left join (select userid, historyid, date from user_view_history group by historyid) uvh on uvh.userid = u.userid"
    },
    {
     "rawSql": "select uvh.date*1000 as time_sec, \"Category Views\" as metric, count(uvh.historyid) as value\n\n\nfrom (select * from user_view_history \nwhere ($TEAM = 'All Teams' OR userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR userid = $USERID)\nand doc_type=\"WIKI\" \nand date BETWEEN '${__from:date:seconds}' AND '${__to:date:seconds}'\ngroup by userid, docid, date\n) uvh\n\ninner join \n(select userid, login, username \nfrom global_users \n\nwhere \n($USERID='All Users' or $USERID=userid) \n-- and login not like \"%dozuki.com%\"\n-- and login not like \"%ifixit.com%\" \nand ($TEAM = 'All Teams' OR userid in (select userid from user_teams where user_teams.teamid=$TEAM))\n) gu using (`userid`)\n\nINNER join (select wikiid as docid, title, namespace from wikis where namespace=\"TOPIC\") w using(docid)\n\nwhere ($CATEGORYID = 'All Categories' OR w.title = $CATEGORYID) \n\ngroup by date_format(from_unixtime(uvh.date), \"%m-%y\")\n\norder by uvh.date asc\n"
    }
   ]
  },
  {
   "title": "Users Viewing Content",
   "type": "graph",
   "description": "Filtered by teams, users, and date range.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none", "label": "Users Viewing Content" }
   ],
   "targets": [
    {
     "rawSql": "Select view_date*1000 as time_sec, count(distinct userid) as value, \n\nconcat(monthname(from_unixtime(view_date)),\" \",year(from_unixtime(view_date)))  as metric\n\n-- \"Users Viewing Content\" as metric\n\n\n\nfrom (select user_view_history.historyid, user_view_history.userid, user_view_history.date as view_date from user_view_history \n where ($TEAM = 'All Teams' OR userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR userid = $USERID)  group by historyid\n) uvh\n\nleft join global_users gu using(userid)\n\n\n\nwhere\nview_date BETWEEN '${__from:date:seconds}' AND '${__to:date:seconds}'\n\nand gu.login not like \"%dozuki.com%\"\nand gu.login not like \"%ifixit.com%\"\n\n-- group by year(from_unixtime(view_date)), month(from_unixtime(view_date)) order by year(from_unixtime(view_date)), month(from_unixtime(view_date))\n\ngroup by date_format(from_unixtime(uvh.view_date), \"%m-%y\")\norder by view_date asc"
    }
   ]
  },
  {
   "title": "User Activity Over Time",
   "type": "graph",
   "description": "Filtered by teams, users, and date range.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select uh.date*1000 as time, \"Activity\" as metric, count(uh.historyid) as value\n\n\nfrom (select * from user_history where ($TEAM = 'All Teams' OR userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand ($USERID = 'All Users' OR userid = $USERID)) uh\n\n\n\ngroup by date_format(from_unixtime(uh.date), \"%m-%y\")\n\norder by uh.date asc"
    }
   ]
  },
  {
   "title": " User Details",
   "type": "table-old",
   "description": "Filtered by teams and users.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "rawSql": "Select * from (select u.username as \"Username\", u.userid, u.login as \"Email\",\n\nCASE up.privilegeid\n\tWHEN 1 THEN \"Admin\"\n\tWHEN 7 THEN \"Author\"\n\tELSE \"Standard\"\nEND as \"Role\", \n\nu.join_date*1000 as \"Account Created On\", \n-- ses.status, \n\ncase\nwhen u.enabled=1\nthen \"Active\"\nWhen u.enabled=0\nThen \"Disabled\" \nend as \"Status\",  \n\nuh.date*1000 as \"Last Activity\",\nuvh.date*1000 as \"Last View\"\n-- ses.ip, \n\n\n\n\nfrom global_users u\n\n\n\nleft join sessions ses on ses.userid = u.userid and ses.status=\"ACTIVE\"  \n\nleft join user_privileges up on up.userid = u.userid\nleft join (select userid, max(date) as date from user_history group by userid) uh on uh.userid = u.userid\nleft join (select userid, max(date) as date from user_view_history group by userid) uvh on uvh.userid = u.userid\n-- left join user_invites on user_invites.userid\n\n\n\n\n\n\n\n\n\n\n\nunion all\n\nselect \"N/A\" as \"Username\",  \"N/A\" as userid, email as \"Email\", \nCASE privilege\n\tWHEN 1 THEN \"Admin\"\n\tWHEN 7 THEN \"Author\"\n\tELSE \"Standard\"\nEND as \"Role\", \n\"Pending Invite\" as \"Account Created On\", \"Invited\" as \"Status\", \"N/A\" as \"Last Activity\",\n\"N/A\" as \"Last View\"  \nfrom user_invites) t\n\nwhere \n\n\n ( t.`Last Activity` >= '${__from:date:seconds}' or t.`Last View`  >= '${__from:date:seconds}'  or t.`Account Created On` >= '${__from:date:seconds}' )\n\nand \n\n (t.`Last Activity` <= '${__to:date:seconds}' or t.`Last View`  <= '${__to:date:seconds}'  or t.`Account Created On` <= '${__to:date:seconds}' )\nand ($USERID = 'All Users' OR userid = $USERID)\nand ($TEAM = 'All Teams' OR userid in (select userid from user_teams where user_teams.teamid=$TEAM))\nand t.`Email` not like \"%dozuki.com%\"\nand t.`Email` not like \"%ifixit.com%\""
    }
   ]
  }
 ]
}