{{- if .Values.frontegg.images.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
