image:
  repository: grafana/grafana
  tag: "7.5.16"
  pullPolicy: IfNotPresent


## Deployment annotations
# annotations: {}

## Expose the grafana service to be accessed from outside the cluster (LoadBalancer service).
## or access it from within the cluster (ClusterIP service). Set the service type and the port to serve it.
## ref: http://kubernetes.io/docs/user-guide/services/
##
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "cert-issuer"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  path: /dashboards(/|$)(.*)
  hosts:
    - ${hostname}
  tls:
    - secretName: tls-secret
      hosts:
        - ${hostname}

## Still create the pvc even though we don't use it anymore to prevent the init migration script from failing.
## Eventually in the future we will remove it once all existing sqlite grafana instances have been upgraded.
persistence:
  type: pvc
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection

initChownData:
  ## If false, data ownership will not be reset at startup
  ## This allows the prometheus-server to be run with an arbitrary user
  ##
  enabled: false

# Administrator credentials when not using an existing secret (see below)
adminUser: ${admin_user}
envFromSecret: "grafana-config"

## Configure grafana datasources
## ref: http://docs.grafana.org/administration/provisioning/#datasources
##
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: MySQL
      type: mysql
      url: ${database_hostname}:3306
      database: onprem_guide
      user: dozuki
      isDefault: true
      secureJsonData:
        password: ${database_password}

## Pass the plugins you want installed as a list.
##
plugins:
  - grafana-piechart-panel

## Configure grafana dashboard to import
## NOTE: To use dashboards you must also enable/configure dashboardProviders
## ref: https://grafana.com/dashboards
##
## dashboards per provider, use provider name as key.
##
dashboards:
   default:
     comments:
       file: dashboards/comments.json
     content-activity:
       file: dashboards/content-activity.json
     course-completion:
       file: dashboards/course-completion.json
     data-explorer:
       file: dashboards/data-explorer.json
     guide-drafts-and-release-versions:
       file: dashboards/guide-drafts-and-release-versions.json
     guide-flags:
       file: dashboards/guide-flags.json
     new-category-content:
       file: dashboards/new-category-content.json
     new-guide-content:
       file: dashboards/new-guide-content.json
     new-item-content:
       file: dashboards/new-item-content.json
     new-wiki-content:
       file: dashboards/new-wiki-content.json
     process-status:
       file: dashboards/process-status.json
     training-report:
       file: dashboards/training-report.json
     user-activity-report:
       file: dashboards/user-activity-report.json
     user-work-experience:
       file: dashboards/user-work-experience.json
     work-order-history:
       file: dashboards/work-order-history.json
     work-order-signoff-status:
       file: dashboards/work-order-signoff-status.json
     work-order-status:
       file: dashboards/work-order-status.json


extraInitContainers:
  - name: migrate-sqlite-to-mysql
    image: python:3.8-slim
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /tmp/app-packages
        pip install --no-cache-dir --target=/tmp/app-packages pymysql
        export PYTHONPATH=$PYTHONPATH:/tmp/app-packages
        python /scripts/grafana_migrate_sqlite_to_mysql.py
    env:
      - name: MYSQL_HOST
        valueFrom:
          secretKeyRef:
            name: grafana-mysql-credentials
            key: host
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: grafana-mysql-credentials
            key: user
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: grafana-mysql-credentials
            key: password
      - name: MYSQL_DB
        value: grafana
    volumeMounts:
      - name: storage
        mountPath: /sqlite-data
        readOnly: true
      - name: migration-script
        mountPath: /scripts
extraContainerVolumes:
  - name: migration-script
    configMap:
      name: grafana-sqlite-migrate
