#!/usr/bin/env bash
# Remote state: resource group + storage account + backend.tf generation.
# Storage account names: 3-24 chars, lowercase alphanumeric, globally unique.

ensure_state_backend() {
  local customer="$1" environment="$2" location="$3" azure_env="${4:-public}"
  local rg="${customer}-${environment}-tfstate"
  local sa
  sa="mpc$(printf '%s%s' "$customer" "$environment" | tr -cd 'a-z0-9' | cut -c1-12)tf$(az account show --query id -o tsv | tr -d '-' | cut -c1-6)"
  local container="tfstate"

  az group create --name "$rg" --location "$location" --output none
  if ! az storage account show --name "$sa" --resource-group "$rg" >/dev/null 2>&1; then
    log "creating state storage account ${sa}"
    az storage account create --name "$sa" --resource-group "$rg" \
      --location "$location" --sku Standard_GRS --kind StorageV2 \
      --min-tls-version TLS1_2 --allow-blob-public-access false --output none
  fi
  az storage container create --name "$container" --account-name "$sa" \
    --auth-mode login --output none 2>/dev/null \
    || az storage container create --name "$container" --account-name "$sa" --output none

  _write_backend "${PHYSICAL_DIR}/backend_override.tf" "$rg" "$sa" "$container" "physical.tfstate" "$azure_env"
  _write_backend "${LOGICAL_DIR}/backend_override.tf"  "$rg" "$sa" "$container" "logical.tfstate" "$azure_env"
  log "remote state ready: ${sa}/${container}"
}

_write_backend() { # path rg sa container key azure_env
  cat > "$1" <<EOF
# Generated by bootstrap.sh - do not edit.
terraform {
  backend "azurerm" {
    resource_group_name  = "$2"
    storage_account_name = "$3"
    container_name       = "$4"
    key                  = "$5"
    environment          = "$6"
  }
}
EOF
}

# The logical layer's AWS resources are count=0 on Azure, but the provider
# must never attempt real credential resolution. terragrunt generates this on
# AWS; we generate the inert stub here.
write_aws_stub() {
  cat > "${LOGICAL_DIR}/aws_stub_override.tf" <<'EOF'
# Generated by bootstrap.sh - do not edit.
provider "aws" {
  region                      = "us-east-1"
  access_key                  = "deploy-stub"
  secret_key                  = "deploy-stub"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
}
EOF
}
