# Default values for events-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide the amount of pods if HPA is not enabled
##
replicaCount: 2

## Provide the image docker tag default: latest
##
appVersion: latest

## Manage docker image properties
##
image:
  ## Provide docker repository hub
  ##
  repository: frontegg/hybrid-connectors-worker
  ## Provide image pull policy
  ##
  pullPolicy: Always

## Provide secret name for frontegg's repository
##
imagePullSecrets:
  - name: regcred

## Provide a name in place of connectors-worker for `app:` labels
##
nameOverride: ""
## Provide a name in place of {releaseName}-connectors-worker
##
fullnameOverride: ""

## Setup Service properties for team-management-service (open only one port)
##
service:
  ## Set service type
  ##
  type: ClusterIP
  ## Set service port
  ##
  protocol: TCP
  ## Set service target port to map
  ##
  port: 80
  ## Set port protocol default: TCP
  ##
  targetPort: 3015
  ## Set port name
  ##
  name: http

## HPA properties for connectors-worker
## If autoscaling is enabled it will monitor the service and raise or lower pods amount based upon usage
## If autoscaling is disabled team-management-service will be managed by replicaset with `replicaCount` determine pod amount
##
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

## Set connectors-worker resources
##
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 250m
    memory: 512Mi

nodeSelector:
  "beta.kubernetes.io/os": linux

## Provide deployment tolerations
##
tolerations: []

## Provide deployment affinity
##
affinity: {}

configuration:
  secrets: {}
  map: {}

# -- Set Message Broker (Kafka) properties.
messageBroker:
  # -- Set broker list (host)
  brokerList: ""
  # -- Set broker list password
  password: ""

# -- Set Redis properties
redis:
  # -- Set redis host
  host: ""
  # -- Set redis host
  port: "6379"
  # -- Set redis password
  password: ""
  # -- Set redis database index, change only if needed
  index: "7"
  # -- Set tls value (true|false)
  tls: "true"

# -- Set Frontegg's properties
frontegg:
  twilio:
    # -- Set twilio sender number
    sender: ""
    # -- Set twilio token, given buy
    token: ""
    # -- Set twilio account Id given by Frontegg
    accountId: ""
  # -- Set supported channels
  # -- Possible values email | sms | slack
  # -- use comma separated values for example: email,slack,sms
  channels: ""
  # -- Set emails properties for the appropriate provider
  emails:
    # -- Set the email supported provide [ses | sendgrid] default (sendgrid)
    provider: ""
    # -- Set aws SES properties
    aws:
      accessKey: ""
      secretAccess: ""
      region: ""
    # -- Set Sendgrid properties
    sendgrid:
      apiKey: ""
