{
 "title": "Comments Dashboard",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "SITE_NAME", "label": "Site Name", "query": "onprem" },
   { "name": "GUIDE_DB", "label": "Guide Database", "query": "mysql" },
   {
    "name": "USERID",
    "label": "User",
    "query": "select  CONCAT(global_users.username, \" — \", \"User ID:\", global_users.userid) AS __text, global_users.userid AS __value from global_users"
   },
   {
    "name": "CATEGORYID",
    "label": "Category",
    "query": "select  \"All Categories\", list.title as \"Category\" from (select distinct title from wikis where wikis.namespace=\"TOPIC\") list order by 'All Categories', title ASC"
   },
   {
    "name": "TEAM",
    "label": "Team",
    "query": " select CONCAT(name, \" — \", \"Team ID:\", teamid) AS __text, teamid AS __value FROM teams"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "content": "\n# Comments\n\nNew comments on guides, wikis, and forum posts.\n\n\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  { "title": "Comments Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "description": "Existing comments on guides and guide steps.",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 4 },
   "content": "<h3> Guide Comments</h3>\n<hr>",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "type": "text",
   "description": "Existing comments on wikis.",
   "gridPos": { "h": 2, "w": 7, "x": 8, "y": 4 },
   "content": "<h3> Wiki Comments</h3>\n<hr>",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "type": "text",
   "description": "Existing comments on forum questions and answers.",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 4 },
   "content": "<h3>Forum Comments\n<hr>",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Last 7 Days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(commentid) from comments\n\n\nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\n(context = \"step\" or context = \"guide\") and\n\nFROM_UNIXTIME(comments.date) >= SUBDATE(CURDATE(), INTERVAL 7 DAY)\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n;"
    }
   ]
  },
  {
   "title": "Last 30 Days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(commentid) from comments\n\n\nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\n(context = \"step\" or context = \"guide\") and\n\nFROM_UNIXTIME(comments.date) >= SUBDATE(CURDATE(), INTERVAL 30 DAY)\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n;"
    }
   ]
  },
  {
   "title": "Filtered Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(commentid) from comments\n\n\nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\n(context = \"step\" or context = \"guide\") and\n\nFROM_UNIXTIME(comments.date) >= $__timeFrom()\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n;"
    }
   ]
  },
  {
   "title": "Last 7 Days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(commentid) from comments\n\n\nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\ncomments.context = \"wiki\" and\n\nFROM_UNIXTIME(comments.date) >= SUBDATE(CURDATE(), INTERVAL 7 DAY)\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n;"
    }
   ]
  },
  {
   "title": "Last 30 Days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(commentid) from comments\n\n\nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\ncomments.context = \"wiki\" and\n\nFROM_UNIXTIME(comments.date) >= SUBDATE(CURDATE(), INTERVAL 30 DAY)\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n;"
    }
   ]
  },
  {
   "title": "Filtered Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(commentid) from comments\n\n\nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\ncomments.context = \"wiki\" and\n\nFROM_UNIXTIME(comments.date) >= $__timeFrom()\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n;"
    }
   ]
  },
  {
   "title": "Last 7 Days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(commentid) from comments\n\n\nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\ncomments.context = \"post\" and\n\nFROM_UNIXTIME(comments.date) >= SUBDATE(CURDATE(), INTERVAL 7 DAY)\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n;"
    }
   ]
  },
  {
   "title": "Last 30 Days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(commentid) from comments\n\n\nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\ncomments.context = \"post\" and\n\nFROM_UNIXTIME(comments.date) >= SUBDATE(CURDATE(), INTERVAL 30 DAY)\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n;"
    }
   ]
  },
  {
   "title": "Filtered Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(commentid) from comments\n\n\nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\ncomments.context = \"post\" and\n\nFROM_UNIXTIME(comments.date) >= $__timeFrom()\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n;"
    }
   ]
  },
  { "title": "Guide Comments by Month", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "locale", "label": "New Comments" }
   ],
   "targets": [
    {
     "rawSql": "SELECT comments.date as time, \n\n DATE_FORMAT( from_unixtime(comments.date), \"%b %Y\") as metric,\n       count(commentid) as value\nFROM comments\n\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\n(context = \"step\" or context = \"guide\") and\n\nFROM_UNIXTIME(comments.date) >= $__timeFrom()\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n\nGROUP BY \n\ncomments.date\n;\n"
    }
   ]
  },
  { "title": "New Guide Comments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select title, \nhost_guide, commentid, guide_meta.device,\ncontext, \n\ngusers.username, user_privileges.privilegeid, content, \n-- rating, \nstatus, \nCONVERT_TZ(from_unixtime(com.date), @@session.time_zone, '+00:00') as \"Comment Date\", \n\n\ncase\nwhen com.date_mod=0\nthen CONVERT_TZ(from_unixtime(com.date), @@session.time_zone, '+00:00')\nelse\nCONVERT_TZ(from_unixtime(com.date_mod), @@session.time_zone, '+00:00')\nend as \"Date Modified\"\n\n\nfrom\n(select \ntitle,\ncase\nwhen context=\"guide\" then contextid\nwhen context=\"step\" then host.guideid\nEND as host_guide,\ncontext,\nuserid,\ncontent,\nstatus, \ndate,\ncommentid,\ndate_mod\nfrom comments\n\nleft join (select stepid, guideid from guide_step_revisions where guide_step_revisions.type=\"CREATED\" group by stepid) host on host.stepid=comments.contextid\n\nwhere (context = \"step\" or context = \"guide\")\n\n) com\n\n\nleft join (select userid, username from global_users group by userid) \ngusers on gusers.userid=com.userid\n\nleft join user_privileges on user_privileges.userid=gusers.userid\nleft join guide_current on guide_current.guideid=com.host_guide\nleft join guide_revisions on guide_current.guide_revisionid=guide_revisions.guide_revisionid\nleft join guide_meta on guide_revisions.gtr_revisionid=guide_meta.revisionid\n\nwhere \n($USERID = 'All Users' OR com.userid = $USERID) and\n\n($TEAM = 'All Teams' OR gusers.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\n($CATEGORYID = 'All Categories' OR guide_meta.device = $CATEGORYID) and\n\n\nFROM_UNIXTIME(com.date) >= $__timeFrom()\nand \nFROM_UNIXTIME(com.date) <= $__timeTo()\n\n;"
    }
   ]
  },
  { "title": "Wiki Comments by Month", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "locale", "label": "New Comments" }
   ],
   "targets": [
    {
     "rawSql": "SELECT comments.date as time, \n\n DATE_FORMAT( from_unixtime(comments.date), \"%b %Y\") as metric,\n       count(commentid) as value\nFROM comments\n\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\ncomments.context = \"wiki\" and\n\nFROM_UNIXTIME(comments.date) >= $__timeFrom()\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n\nGROUP BY \n\ncomments.date\n;\n"
    }
   ]
  },
  { "title": "New Wiki Comments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "select com.title, \nhost_post,\ncommentid,\nurltitle,\ncontext,\ngusers.username, user_privileges.privilegeid, content, \n-- rating, \nstatus, \nCONVERT_TZ(from_unixtime(com.date), @@session.time_zone, '+00:00') as \"Comment Date\", \n\ncase\nwhen com.date_mod=0\nthen CONVERT_TZ(from_unixtime(com.date), @@session.time_zone, '+00:00')\nelse\nCONVERT_TZ(from_unixtime(com.date_mod), @@session.time_zone, '+00:00')\nend as \"Date Modified\"\n\nfrom\n(select \ntitle, \n\ncase\nwhen parentid is null then contextid\nwhen parentid is not null then parentid\nEND as host_post,\n\ncontext,\nuserid,\ncontent,\nstatus, \ndate,\ncommentid,\ndate_mod\nfrom comments\n\n\n\nwhere context=\"wiki\") com\n\n\nleft join (select userid, username from global_users group by userid) \ngusers on gusers.userid=com.userid\nleft join user_privileges on user_privileges.userid=gusers.userid\nleft join (select wikiid, title as urltitle from wikis) wt on wt.wikiid=com.host_post\n\n\nwhere \n($USERID = 'All Users' OR com.userid = $USERID) and\n\n($TEAM = 'All Teams' OR gusers.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\nFROM_UNIXTIME(com.date) >= $__timeFrom()\nand \nFROM_UNIXTIME(com.date) <= $__timeTo()\n\n\n;"
    }
   ]
  },
  { "title": "Forum Comments by Month", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "locale", "label": "New Comments" }
   ],
   "targets": [
    {
     "rawSql": "SELECT comments.date as time, \n\n DATE_FORMAT( from_unixtime(comments.date), \"%b %Y\") as metric,\n       count(commentid) as value\nFROM comments\n\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \n($USERID = 'All Users' OR comments.userid = $USERID) and\n\n($TEAM = 'All Teams' OR comments.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\ncomments.context = \"post\" and\n\nFROM_UNIXTIME(comments.date) >= $__timeFrom()\nand \nFROM_UNIXTIME(comments.date) <= $__timeTo()\nand comments.status != \"deleted\"\n\nGROUP BY \n\ncomments.date\n;\n"
    }
   ]
  },
  { "title": "New Forum Comments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "select title, \nhost_post,\ncommentid,\ncontext,\ngusers.username, user_privileges.privilegeid, content, \n-- rating, \nstatus, \nCONVERT_TZ(from_unixtime(com.date), @@session.time_zone, '+00:00') as \"Comment Date\", \n\ncase\nwhen com.date_mod=0\nthen CONVERT_TZ(from_unixtime(com.date), @@session.time_zone, '+00:00')\nelse\nCONVERT_TZ(from_unixtime(com.date_mod), @@session.time_zone, '+00:00')\nend as \"Date Modified\"\n\nfrom\n(select \ntitle, \n\ncase\nwhen parentid is null then contextid\nwhen parentid is not null then parentid\nEND as host_post,\n\ncontext,\nuserid,\ncontent,\nstatus, \ndate,\ncommentid,\ndate_mod\nfrom comments\n\n\n\nwhere context=\"post\") com\n\n\nleft join (select userid, username from global_users group by userid) \ngusers on gusers.userid=com.userid\nleft join user_privileges on user_privileges.userid=gusers.userid\n\nwhere \n($USERID = 'All Users' OR com.userid = $USERID) and\n\n($TEAM = 'All Teams' OR gusers.userid in (select userid from user_teams where user_teams.teamid=$TEAM)) and\n\nFROM_UNIXTIME(com.date) >= $__timeFrom()\nand \nFROM_UNIXTIME(com.date) <= $__timeTo()\n\n\n;"
    }
   ]
  }
 ]
}