{
 "title": "Factory View",
 "tags": [
  "Work Orders",
  "Factory View"
 ],
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "GUIDE_DB", "label": "Guide Database", "query": "mysql" },
   { "name": "SITE_NAME", "label": "Site Name", "query": "onprem" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "# Factory View\nThe heartbeat of your processes at a glance"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "content": "<h2>Tracked Processes</h2>\nProcesses with cycle time goals\n<hr>"
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select wl.entryid, wl.guideid, wl.starttime\n, endtime, (wl.endtime - wl.starttime)/60.00 as duration\n, (x.time_required_max -(y.endingtime - wl.starttime))/60.00 as past_due\n, count(distinct wl.entryid) as metric\nfrom work_log wl\n \njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid in (select distinct guideid from work_log \n\t\t\t\t\t where from_unixtime(starttime)>= $__timeFrom()\n\t\t\t\t\t AND \n\t\t\t\t\t CASE \n    \t\t\t\t\tWHEN endtime is NOT NULL \n\t\t\t\t\t \tTHEN from_unixtime(endtime) <= $__timeTo()\n    \t\t\t\t\tELSE 1 != 1\n\t\t\t\t\t END)) x\nusing (guideid)\n \nJOIN (select entryid,\nCASE \n    WHEN endtime is NOT NULL \n\tthen endtime\n    ELSE 1 != 1\nEND as endingtime\nfrom work_log\nwhere guideid in (select distinct guideid \n\t\t\t\t  from work_log \n\t\t\t\t  where from_unixtime(starttime)>= $__timeFrom()\n\t\t\t\t  and from_unixtime(endtime) <= $__timeTo())\nand from_unixtime(starttime)>= $__timeFrom()\nand from_unixtime(endtime) <= $__timeTo()\n\t ) y\nusing (entryid)\n\n\n\n\nwhere from_unixtime(wl.starttime) >= $__timeFrom()\nand from_unixtime(wl.endtime) <= $__timeTo()\nand wl.cancelled != 1\nand (x.time_required_max is not null or x.time_required_max != 0)\nand (x.time_required_min is not null or x.time_required_min != 0)\n"
    }
   ]
  },
  {
   "title": "In Progress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select wl.entryid, wl.guideid, wl.starttime, endtime, \n(wl.endtime - wl.starttime)/60.00 as duration, \n(x.time_required_max -(y.endingtime - wl.starttime))/60.00 as past_due, \ncount(distinct wl.entryid) as metric\nfrom work_log wl\n \njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid in (select distinct guideid from work_log \n\t\t\t\t\t where from_unixtime(starttime)>= $__timeFrom()\n\t\t\t\t\t AND \n\t\t\t\t\t endtime is NULL)) x\nusing (guideid)\n \nJOIN (select entryid,\nCASE \n    WHEN endtime is NULL \n\tthen endtime\n    ELSE 1 != 1\nEND as endingtime\nfrom work_log\nwhere guideid in (select distinct guideid \n\t\t\t\t  from work_log \n\t\t\t\t  where from_unixtime(starttime)>= $__timeFrom()\n\t\t\t\t  and endtime is NULL)\nand from_unixtime(starttime)>= $__timeFrom()\nand endtime is NULL\n\t ) y\nusing (entryid)\n\nwhere from_unixtime(wl.starttime) >= $__timeFrom()\nand wl.endtime is null\nand wl.cancelled != 1\nand (x.time_required_max is not null or x.time_required_max != 0)\nand (x.time_required_min is not null or x.time_required_min != 0)"
    }
   ]
  },
  {
   "title": "Missed Goal",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select wl.entryid, wl.guideid, from_unixtime(wl.starttime), from_unixtime(endtime), \n(wl.endtime - wl.starttime)/60.00 as duration, \n(x.time_required_max -(y.endingtime - wl.starttime))/60.00 as past_due,\ncount(distinct wl.entryid) as metric\n\nfrom work_log wl\n \njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid in (select distinct guideid from work_log \n\t\t\t\t\t where date(from_unixtime(starttime))>= $__timeFrom()\n\t\t\t\t\t AND \n\t\t\t\t\t CASE \n    \t\t\t\t\tWHEN endtime is NOT NULL \n\t\t\t\t\t \tTHEN date(from_unixtime(endtime)) <= $__timeTo()\n    \t\t\t\t\tELSE 1 != 1\n\t\t\t\t\t END)) x\nusing (guideid)\n \nJOIN (select entryid,\nCASE \n    WHEN endtime is NOT NULL \n\tthen endtime\n    ELSE 1 != 1\nEND as endingtime\nfrom work_log\nwhere guideid in (select distinct guideid \n\t\t\t\t  from work_log \n\t\t\t\t  where date(from_unixtime(starttime))>= $__timeFrom()\n\t\t\t\t  and date(from_unixtime(endtime)) <= $__timeTo())\nand date(from_unixtime(starttime))>= $__timeFrom()\nand date(from_unixtime(endtime)) <= $__timeTo()\n\t ) y\nusing (entryid)\nwhere date(from_unixtime(wl.starttime))>= $__timeFrom()\nand wl.cancelled != 1\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\nand (x.time_required_max is not null or x.time_required_max != 0)\nand (x.time_required_min is not null or x.time_required_min != 0)\n\nand (x.time_required_max -(y.endingtime - wl.starttime))/60.00 < 0\n\norder by entryid"
    }
   ]
  },
  {
   "title": "Hit Goal",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select wl.entryid, wl.guideid, from_unixtime(wl.starttime), from_unixtime(endtime), \n(wl.endtime - wl.starttime)/60.00 as duration, \n(x.time_required_max -(y.endingtime - wl.starttime))/60.00 as past_due,\ncount(distinct wl.entryid) as metric\n\nfrom work_log wl\n \njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid in (select distinct guideid from work_log \n\t\t\t\t\t where date(from_unixtime(starttime))>= $__timeFrom()\n\t\t\t\t\t AND \n\t\t\t\t\t CASE \n    \t\t\t\t\tWHEN endtime is NOT NULL \n\t\t\t\t\t \tTHEN date(from_unixtime(endtime)) <= $__timeTo()\n    \t\t\t\t\tELSE 1 != 1\n\t\t\t\t\t END)) x\nusing (guideid)\n \nJOIN (select entryid,\nCASE \n    WHEN endtime is NOT NULL \n\tthen endtime\n    ELSE 1 != 1\nEND as endingtime\nfrom work_log\nwhere guideid in (select distinct guideid \n\t\t\t\t  from work_log \n\t\t\t\t  where date(from_unixtime(starttime))>= $__timeFrom()\n\t\t\t\t  and date(from_unixtime(endtime)) <= $__timeTo())\nand date(from_unixtime(starttime))>= $__timeFrom()\nand date(from_unixtime(endtime)) <= $__timeTo()\n\t ) y\nusing (entryid)\nwhere date(from_unixtime(wl.starttime))>= $__timeFrom()\nand wl.cancelled != 1\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\nand (x.time_required_max is not null or x.time_required_max != 0)\nand (x.time_required_min is not null or x.time_required_min != 0)\n\nand (x.time_required_max -(y.endingtime - wl.starttime))/60.00 > 0\n\norder by entryid"
    }
   ]
  },
  {
   "title": "Goal Efficiency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select a.hits/b.hitsandmisses as metric \n\nfrom (select \nwl.entryid, wl.guideid, from_unixtime(wl.starttime), from_unixtime(endtime), \n(wl.endtime - wl.starttime)/60.00 as duration, \n(x.time_required_max -(y.endingtime - wl.starttime))/60.00 as past_due,\ncount(distinct wl.entryid) as hits\n\nfrom work_log wl\n \njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid in (select distinct guideid from work_log \n\t\t\t\t\t where date(from_unixtime(starttime))>= $__timeFrom()\n\t\t\t\t\t AND \n\t\t\t\t\t CASE \n    \t\t\t\t\tWHEN endtime is NOT NULL \n\t\t\t\t\t \tTHEN date(from_unixtime(endtime)) <= $__timeTo()\n    \t\t\t\t\tELSE 1 != 1\n\t\t\t\t\t END)) x\nusing (guideid)\n \nJOIN (select entryid,\nCASE \n    WHEN endtime is NOT NULL \n\tthen endtime\n    ELSE 1 != 1\nEND as endingtime\nfrom work_log\nwhere guideid in (select distinct guideid \n\t\t\t\t  from work_log \n\t\t\t\t  where date(from_unixtime(starttime))>= $__timeFrom()\n\t\t\t\t  and date(from_unixtime(endtime)) <= $__timeTo())\nand date(from_unixtime(starttime))>= $__timeFrom()\nand date(from_unixtime(endtime)) <= $__timeTo()\n\t ) y\nusing (entryid)\nwhere date(from_unixtime(wl.starttime))>= $__timeFrom()\nand wl.cancelled != 1\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\nand (x.time_required_max is not null or x.time_required_max != 0)\nand (x.time_required_min is not null or x.time_required_min != 0)\n\nand (x.time_required_max -(y.endingtime - wl.starttime))/60.00 > 0\n\norder by entryid) a\n\nleft join \n\n(select \nwl.entryid, wl.guideid, from_unixtime(wl.starttime), from_unixtime(endtime), \n(wl.endtime - wl.starttime)/60.00 as duration, \n(x.time_required_max -(y.endingtime - wl.starttime))/60.00 as past_due,\ncount(distinct wl.entryid) as hitsandmisses\n\nfrom work_log wl\n \njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid in (select distinct guideid from work_log \n\t\t\t\t\t where date(from_unixtime(starttime))>= $__timeFrom()\n\t\t\t\t\t AND \n\t\t\t\t\t CASE \n    \t\t\t\t\tWHEN endtime is NOT NULL \n\t\t\t\t\t \tTHEN date(from_unixtime(endtime)) <= $__timeTo()\n    \t\t\t\t\tELSE 1 != 1\n\t\t\t\t\t END)) x\nusing (guideid)\n \nJOIN (select entryid,\nCASE \n    WHEN endtime is NOT NULL \n\tthen endtime\n    ELSE 1 != 1\nEND as endingtime\nfrom work_log\nwhere guideid in (select distinct guideid \n\t\t\t\t  from work_log \n\t\t\t\t  where date(from_unixtime(starttime))>= $__timeFrom()\n\t\t\t\t  and date(from_unixtime(endtime)) <= $__timeTo())\nand date(from_unixtime(starttime))>= $__timeFrom()\nand date(from_unixtime(endtime)) <= $__timeTo()\n\t ) y\nusing (entryid)\nwhere date(from_unixtime(wl.starttime))>= $__timeFrom()\nand wl.cancelled != 1\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\nand (x.time_required_max is not null or x.time_required_max != 0)\nand (x.time_required_min is not null or x.time_required_min != 0)\n\n\norder by entryid) b on a.entryid=b.entryid"
    }
   ]
  },
  {
   "title": "Cancelled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  wl.entryid, wl.guideid, from_unixtime(wl.starttime), from_unixtime(endtime), \r\n-- (wl.endtime - wl.starttime)/60.00 as duration, \r\n-- (x.time_required_max -(y.endingtime - wl.starttime))/60.00 as past_due, \r\ncount(distinct wl.entryid) as metric\r\nfrom work_log wl\r\n \r\nleft join (select gc.guideid, gm.time_required_max, gm.time_required_min\r\nFROM guide_current gc\r\nJOIN guide_revisions gr USING (guide_revisionid)\r\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\r\n) x\r\nusing (guideid)\r\n \r\n\r\nwhere date(from_unixtime(wl.starttime)) >= $__timeFrom()\r\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\r\nand wl.cancelled = 1\r\nand (x.time_required_max is not null)\r\nand (x.time_required_max != 0)\r\nand (x.time_required_min is not null)\r\nand (x.time_required_min != 0)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "content": "<h2>Untracked Processes</h2>\nProcesses with no cycle time goals\n<hr>"
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select wl.entryid, wl.guideid, wl.starttime\n, endtime, (wl.endtime - wl.starttime)/60.00 as duration\n, (x.time_required_max -(y.endingtime - wl.starttime))/60.00 as past_due\n, count(distinct wl.entryid) as metric\nfrom work_log wl\n \njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid in (select distinct guideid from work_log \n\t\t\t\t\t where from_unixtime(starttime)>= $__timeFrom()\n\t\t\t\t\t AND \n\t\t\t\t\t CASE \n    \t\t\t\t\tWHEN endtime is NOT NULL \n\t\t\t\t\t \tTHEN from_unixtime(endtime) <= $__timeTo()\n    \t\t\t\t\tELSE 1 != 1\n\t\t\t\t\t END)) x\nusing (guideid)\n \nJOIN (select entryid,\nCASE \n    WHEN endtime is NOT NULL \n\tthen endtime\n    ELSE 1 != 1\nEND as endingtime\nfrom work_log\nwhere guideid in (select distinct guideid \n\t\t\t\t  from work_log \n\t\t\t\t  where from_unixtime(starttime)>= $__timeFrom()\n\t\t\t\t  and from_unixtime(endtime) <= $__timeTo())\nand from_unixtime(starttime)>= $__timeFrom()\nand from_unixtime(endtime) <= $__timeTo()\n\t ) y\nusing (entryid)\n\n\n\n\nwhere from_unixtime(wl.starttime) >= $__timeFrom()\nand from_unixtime(wl.endtime) <= $__timeTo()\nand wl.cancelled != 1\nand (x.time_required_max is null or x.time_required_max = 0)\nand (x.time_required_min is null or x.time_required_min = 0)\n"
    }
   ]
  },
  {
   "title": "In Progress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select wl.entryid, wl.guideid, wl.starttime, endtime, \n(wl.endtime - wl.starttime)/60.00 as duration, \n(x.time_required_max -(y.endingtime - wl.starttime))/60.00 as past_due, \ncount(distinct wl.entryid) as metric\nfrom work_log wl\n \njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid in (select distinct guideid from work_log \n\t\t\t\t\t where from_unixtime(starttime)>= $__timeFrom()\n\t\t\t\t\t AND \n\t\t\t\t\t endtime is NULL)) x\nusing (guideid)\n \nJOIN (select entryid,\nCASE \n    WHEN endtime is NULL \n\tthen endtime\n    ELSE 1 != 1\nEND as endingtime\nfrom work_log\nwhere guideid in (select distinct guideid \n\t\t\t\t  from work_log \n\t\t\t\t  where from_unixtime(starttime)>= $__timeFrom()\n\t\t\t\t  and endtime is NULL)\nand from_unixtime(starttime)>= $__timeFrom()\nand endtime is NULL\n\t ) y\nusing (entryid)\n\nwhere from_unixtime(wl.starttime) >= $__timeFrom()\nand wl.endtime is null\nand wl.cancelled != 1\nand (x.time_required_max is null or x.time_required_max = 0)\nand (x.time_required_min is  null or x.time_required_min = 0)"
    }
   ]
  },
  {
   "title": "Cancelled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  wl.entryid, wl.guideid, count(distinct wl.entryid) as metric\r\nfrom work_log wl\r\n \r\nleft join (select gc.guideid, gm.time_required_max, gm.time_required_min\r\nFROM guide_current gc\r\nJOIN guide_revisions gr USING (guide_revisionid)\r\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\r\n) x\r\non x.guideid=wl.guideid\r\n \r\n\r\nwhere date(from_unixtime(wl.starttime)) >= $__timeFrom()\r\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\r\nand wl.cancelled = 1\r\nand (x.time_required_max is null or x.time_required_max = 0)\r\nand (x.time_required_min is null or x.time_required_min = 0)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 }, "content": "<h3>Goal Hits / Misses Trend" },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select y.endingtime as time_sec, count(distinct wl.entryid) as \"Missed Goal\"\r\n-- ,\r\n-- date_format(date(from_unixtime(y.endingtime)), '%c-%d') as finish_date, \r\n-- wl.entryid, wl.guideid, from_unixtime(wl.starttime), \r\n-- (wl.endtime - wl.starttime)/60.00 as duration, \r\n-- (x.time_required_max -(y.endingtime - wl.starttime))/60.00 as past_due\r\nfrom work_log wl\r\n \r\njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\r\nFROM guide_current gc\r\nJOIN guide_revisions gr USING (guide_revisionid)\r\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\r\nwhere gc.guideid in (select distinct guideid from work_log \r\n\t\t\t\t\t where date(from_unixtime(starttime)) >= $__timeFrom()\r\n\t\t\t\t\t AND \r\n\t\t\t\t\t CASE \r\n    \t\t\t\t\tWHEN endtime is NOT NULL \r\n\t\t\t\t\t \tTHEN date(from_unixtime(endtime)) <= $__timeTo()\r\n    \t\t\t\t\tELSE 1 != 1\r\n\t\t\t\t\t END)) x\r\nusing (guideid)\r\n \r\nJOIN (select entryid,\r\nCASE \r\n    WHEN endtime is NOT NULL \r\n\tthen endtime\r\n    ELSE 1 != 1\r\nEND as endingtime\r\nfrom work_log\r\nwhere guideid in (select distinct guideid \r\n\t\t\t\t  from work_log \r\n\t\t\t\t  where date(from_unixtime(starttime)) >= $__timeFrom()\r\n\t\t\t\t  and date(from_unixtime(endtime)) <= $__timeTo())\r\nand date(from_unixtime(starttime)) >= $__timeFrom()\r\nand date(from_unixtime(endtime)) <= $__timeTo()\r\n\t ) y\r\nusing (entryid)\r\n\r\nwhere date(from_unixtime(wl.starttime)) >= $__timeFrom()\r\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\r\nand wl.cancelled != 1\r\nand (x.time_required_max is not null or x.time_required_max != 0)\r\nand (x.time_required_min is not null or x.time_required_min != 0)\r\nand (x.time_required_max -(y.endingtime - wl.starttime))/60.00 < 0\r\ngroup by date_format(FROM_UNIXTIME(y.endingtime),\"%y-%m-%d\")\r\norder by date_format(FROM_UNIXTIME(y.endingtime),\"%y-%m-%d\")"
    },
    {
     "rawSql": "select y.endingtime as time_sec, count(distinct wl.entryid) as \"Hit Goal\"\r\n-- ,\r\n-- date_format(date(from_unixtime(y.endingtime)), '%c-%d') as finish_date, \r\n-- wl.entryid, wl.guideid, from_unixtime(wl.starttime), \r\n-- (wl.endtime - wl.starttime)/60.00 as duration, \r\n-- (x.time_required_max -(y.endingtime - wl.starttime))/60.00 as past_due\r\nfrom work_log wl\r\n \r\njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\r\nFROM guide_current gc\r\nJOIN guide_revisions gr USING (guide_revisionid)\r\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\r\nwhere gc.guideid in (select distinct guideid from work_log \r\n\t\t\t\t\t where date(from_unixtime(starttime)) >= $__timeFrom()\r\n\t\t\t\t\t AND \r\n\t\t\t\t\t CASE \r\n    \t\t\t\t\tWHEN endtime is NOT NULL \r\n\t\t\t\t\t \tTHEN date(from_unixtime(endtime)) <= $__timeTo()\r\n    \t\t\t\t\tELSE 1 != 1\r\n\t\t\t\t\t END)) x\r\nusing (guideid)\r\n \r\nJOIN (select entryid,\r\nCASE \r\n    WHEN endtime is NOT NULL \r\n\tthen endtime\r\n    ELSE 1 != 1\r\nEND as endingtime\r\nfrom work_log\r\nwhere guideid in (select distinct guideid \r\n\t\t\t\t  from work_log \r\n\t\t\t\t  where date(from_unixtime(starttime)) >= $__timeFrom()\r\n\t\t\t\t  and date(from_unixtime(endtime)) <= $__timeTo())\r\nand date(from_unixtime(starttime)) >= $__timeFrom()\r\nand date(from_unixtime(endtime)) <= $__timeTo()\r\n\t ) y\r\nusing (entryid)\r\n\r\nwhere date(from_unixtime(wl.starttime)) >= $__timeFrom()\r\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\r\nand wl.cancelled != 1\r\nand (x.time_required_max is not null or x.time_required_max != 0)\r\nand (x.time_required_min is not null or x.time_required_min != 0)\r\nand (x.time_required_max -(y.endingtime - wl.starttime))/60.00 > 0\r\ngroup by date_format(FROM_UNIXTIME(y.endingtime),\"%y-%m-%d\")\r\norder by date_format(FROM_UNIXTIME(y.endingtime),\"%y-%m-%d\")"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 }, "content": "<h3>Goal Hits / Misses Trend %" },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "select wl.guideid, gt.title as \"Process\",  gm.device as \"Category\", \r\n-- wl.entryid,  \r\n-- from_unixtime(wl.starttime), \r\n-- from_unixtime(endtime), \r\n-- (wl.endtime - wl.starttime)/60.00 as duration, \r\n\r\n\r\n count(x.guideid) as \"Misses\",\r\n count(y.guideid) as \"Hits\",\r\n count(z.guideid) as \"Total\",\r\n count(y.guideid)/count(z.guideid) as \"Percentage\"\r\nfrom work_log wl\r\n \r\n\r\nleft join guide_current gc on (gc.guideid =wl.guideid)\r\nleft JOIN guide_revisions gr on (gr.guide_revisionid=gc.guide_revisionid)\r\nleft JOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\r\nleft JOIN guide_text gt ON (gr.gt_revisionid = gt.gt_revisionid)\r\n\r\nleft JOIN\r\n\r\n(select gc.guideid, gm.time_required_max, gm.time_required_min, gt.title, gm.device\r\nFROM guide_current gc\r\nJOIN guide_revisions gr USING (guide_revisionid)\r\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\r\nJOIN guide_text gt ON (gr.gt_revisionid = gt.gt_revisionid)\r\nwhere gc.guideid in (select distinct guideid from work_log \r\n\t\t\t\t\t where date(from_unixtime(starttime)) >= $__timeFrom()\r\n\t\t\t\t\t AND \r\n\t\t\t\t\t CASE \r\n    \t\t\t\t\tWHEN endtime is NOT NULL \r\n\t\t\t\t\t \tTHEN date(from_unixtime(endtime)) <= $__timeTo()\r\n    \t\t\t\t\tELSE 1 != 1\r\n\t\t\t\t\t END)) x\r\non x.guideid=wl.guideid and (x.time_required_max -(CASE \r\n    WHEN wl.endtime is NOT NULL \r\n\tthen wl.endtime\r\n    ELSE 1 != 1\r\nEND\r\n - wl.starttime))/60.00 <0\r\n\r\n\r\nleft JOIN\r\n\r\n(select gc.guideid, gm.time_required_max, gm.time_required_min, gt.title, gm.device\r\nFROM guide_current gc\r\nJOIN guide_revisions gr USING (guide_revisionid)\r\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\r\nJOIN guide_text gt ON (gr.gt_revisionid = gt.gt_revisionid)\r\nwhere gc.guideid in (select distinct guideid from work_log \r\n\t\t\t\t\t where date(from_unixtime(starttime)) >= $__timeFrom()\r\n\t\t\t\t\t AND \r\n\t\t\t\t\t CASE \r\n    \t\t\t\t\tWHEN endtime is NOT NULL \r\n\t\t\t\t\t \tTHEN date(from_unixtime(endtime)) <= $__timeTo()\r\n    \t\t\t\t\tELSE 1 != 1\r\n\t\t\t\t\t END)) y\r\non y.guideid=wl.guideid and (y.time_required_max -(CASE \r\n    WHEN wl.endtime is NOT NULL \r\n\tthen wl.endtime\r\n    ELSE 1 != 1\r\nEND\r\n - wl.starttime))/60.00 >0\r\n\r\n\r\nleft JOIN\r\n\r\n(select gc.guideid, gm.time_required_max, gm.time_required_min, gt.title, gm.device\r\nFROM guide_current gc\r\nJOIN guide_revisions gr USING (guide_revisionid)\r\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\r\nJOIN guide_text gt ON (gr.gt_revisionid = gt.gt_revisionid)\r\nwhere gc.guideid in (select distinct guideid from work_log \r\n\t\t\t\t\t where date(from_unixtime(starttime)) >= $__timeFrom()\r\n\t\t\t\t\t AND \r\n\t\t\t\t\t CASE \r\n    \t\t\t\t\tWHEN endtime is NOT NULL \r\n\t\t\t\t\t \tTHEN date(from_unixtime(endtime)) <= $__timeTo()\r\n    \t\t\t\t\tELSE 1 != 1\r\n\t\t\t\t\t END)) z\r\non z.guideid=wl.guideid \r\n\r\n\r\n\r\nwhere date(from_unixtime(wl.starttime)) >= $__timeFrom()\r\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\r\nand (gm.time_required_max is not null)\r\nand (gm.time_required_max != 0)\r\nand (gm.time_required_min is not null)\r\nand (gm.time_required_min != 0)\r\nand wl.cancelled != 1\r\n\r\n\r\n-- and \"Past Due\" < 0\r\n\r\n\r\n \r\ngroup by wl.guideid\r\n\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 },
   "content": "<h3>Average Cycle Times (Minutes)"
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "select x.title as \"Process\",  x.device as \"Category\", wl.entryid, wl.guideid, \r\nfrom_unixtime(wl.starttime) as starttime, from_unixtime(wl.endtime) as endtime, \r\navg((wl.endtime - wl.starttime)/60.00) as duration, (x.time_required_max/60.00)-((wl.endtime - wl.starttime)/60.00) as time_to_goal, \r\nx.time_required_max/60.00 as goal_time, (((x.time_required_max)/ABS(wl.endtime - wl.starttime))*100.00) as efficiency\r\nfrom work_log wl\r\n \r\njoin (select gc.guideid, gm.time_required_max, gm.device, gt.title\r\nFROM guide_current gc\r\nJOIN guide_revisions gr USING (guide_revisionid)\r\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\r\nJOIN guide_text gt ON (gr.gt_revisionid = gt.gt_revisionid)\r\nwhere gc.guideid in (\r\nselect distinct guideid \r\nfrom work_log \r\nwhere date(from_unixtime(starttime)) >= $__timeFrom()\r\nand date(from_unixtime(endtime)) <= $__timeTo())\r\n) x\r\nusing (guideid)\r\n \r\nwhere date(from_unixtime(wl.starttime)) >= $__timeFrom()\r\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\r\nand wl.cancelled != 1\r\n\r\ngroup by Process, Category\r\n\r\n"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 }, "content": "<h3>Work Log Details" },
    {
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "select \r\nwork_log.workorderid as \"Workorder ID\",\r\n-- guide_meta.device as \"Category\",\r\nguide_text.title as \"Process Name\",\r\nglobal_users.username as \"Worker\",\r\nFROM_UNIXTIME(work_log.starttime) as \"Start Time\",\r\nFROM_UNIXTIME(work_log.endtime) as \"Finish Time\",\r\nCASE \r\n    WHEN work_log.endtime is NULL then \"In Progress\"\r\n    ELSE SEC_TO_TIME(work_log.endtime - work_log.starttime)\r\nEND as Duration,\r\nCASE \r\n    WHEN work_log.cancelled = 1 then \"Cancelled\"\r\n\tWHEN work_log.endtime is NULL then \"In Progress\"\r\n    ELSE \"Completed\"\r\nEND as Status,\r\nwork_log.guideid as \"Process ID\", \r\nCONCAT('https://','$SITE_NAME','.dozuki.com/Guide/Process/',work_log.guideid) as \"Process Link\"\r\n\r\nFrom work_log\r\n\r\nINNER JOIN global_users on work_log.userid=global_users.userid  \r\n-- INNER JOIN guide_current ON work_log.guideid = guide_current.guideid\r\n\r\n-- JOIN guide_revisions ON guide_revisions.guide_revisionid = guide_current.guide_revisionid\r\n\r\n\r\nINNER JOIN (\r\n    SELECT gtr_revisionid, guideid, MAX(guide_revisionid) AS maxrevision FROM guide_revisions GROUP BY guideid\r\n  ) maxrev ON maxrev.guideid = work_log.guideid \r\n\r\nJOIN guide_revisions ON guide_revisions.guide_revisionid = maxrev.maxrevision\r\n\r\n\r\nJOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\r\nJOIN guide_text ON guide_text.gt_revisionid = guide_revisions.gt_revisionid\r\n\r\n\r\nwhere date(FROM_UNIXTIME(work_log.starttime)) >= $__timeFrom()\r\nand date(FROM_UNIXTIME(work_log.endtime)) <= $__timeTo()\r\n-- and work_log.cancelled <> 1\r\n\r\norder by work_log.starttime desc\r\n"
      }
     ]
    }
   ]
  }
 ]
}