{
 "title": "New Category Content",
 "description": "New category pages.",
 "tags": [
  "Content",
  "New Wiki Content"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "GUIDE_DB", "label": "Guide Database", "query": "mysql" },
   { "name": "SITE_NAME", "label": "Site Name", "query": "onprem" },
   {
    "name": "USERID",
    "label": "Author",
    "query": "select  CONCAT(global_users.username, \" — \", \"User ID:\", global_users.userid) AS __text, global_users.userid AS __value from global_users"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Filtered by date range and user.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "content": "# New Category Content\n*Review new and existing category pages.*"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 }, "content": "<h3>New Category Pages" },
  {
   "title": "All New Categories",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n      count(distinct wikis.wikiid)\n      \nFROM wikis\n\nwhere \n\n($USERID = 'All Users' OR wikis.author = $USERID)\n\nand wikis.namespace='TOPIC'\n\nand FROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(wikis.created_date) <= $__timeTo()"
    }
   ]
  },
  {
   "title": "New Orphan Categories",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n      count(distinct wikis.wikiid)\n      \nFROM wikis\n\nwhere \n\n($USERID = 'All Users' OR wikis.author = $USERID)\n\nand wikis.namespace='TOPIC'\nand wikis.wikiid NOT IN(SELECT wikiid from wiki_areas)\n\nand FROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(wikis.created_date) <= $__timeTo()"
    }
   ]
  },
  {
   "title": "New Categories With Parent Categories",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n      count(distinct wikis.wikiid)\n      \nFROM wikis\n\nwhere \n\n($USERID = 'All Users' OR wikis.author = $USERID)\n\nand wikis.namespace='TOPIC'\nand wikis.wikiid IN(SELECT wikiid from wiki_areas)\n\nand FROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(wikis.created_date) <= $__timeTo()"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 }, "content": "<hr>" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "content": "<h3>New Category Pages by Month"
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "locale", "label": "New Guides" }
   ],
   "targets": [
    {
     "rawSql": "SELECT wikis.created_date as time, \nconcat(monthname(FROM_UNIXTIME(wikis.created_date)),\" \",year(FROM_UNIXTIME(wikis.created_date))) as metric,\n       count(wikis.wikiid) as value\nFROM wikis\n\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \nwikis.namespace = 'TOPIC'\n\nand\n\n($USERID = 'All Users' OR wikis.author = $USERID)\n\nand\n\nFROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\n\n\nand \n\nFROM_UNIXTIME(wikis.created_date) <= $__timeTo()\n\nGROUP BY \n\nyear(FROM_UNIXTIME(wikis.created_date)), month(FROM_UNIXTIME(wikis.created_date))\n\n;\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 }, "content": "<hr>" },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "content": "<h3>New Category Pages by Author"
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT \n      wikis.title, wikis.wikiid,  wa.area as \"Parent Category\", global_users.username as \"Author\", CONVERT_TZ(FROM_UNIXTIME(wikis.created_date), @@session.time_zone, '+00:00') as wiki_date,\n\n      CASE\n      when wikis.text!=\"\"\n      then \"Active\"\n      Else \"Deleted\"\n      end as \"Status\"\n      \nFROM wikis\nleft join global_users on global_users.userid=wikis.author\nleft join wiki_areas wa on wikis.wikiid=wa.wikiid\n\n\nwhere \n\n($USERID = 'All Users' OR wikis.author = $USERID)\n\nand wikis.namespace='TOPIC'\n\nand FROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(wikis.created_date) <= $__timeTo()"
    }
   ]
  }
 ]
}