{
 "title": "New Guide Content",
 "description": "New guides and guide steps.",
 "tags": [
  "Content",
  "New Guide Content"
 ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "GUIDE_DB", "label": "Guide Database", "query": "mysql" },
   { "name": "SITE_NAME", "label": "Site Name", "query": "onprem" },
   {
    "name": "USERID",
    "label": "User",
    "query": "select  CONCAT(global_users.username, \" — \", \"User ID:\", global_users.userid) AS __text, global_users.userid AS __value from global_users"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Filtered by date range and user.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "content": "# New Guide Content\n*New guides and new steps in existing guides.*"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "content": "<h2>New Content Overview</h2>\n<hr>"
  },
  {
   "title": "New Guides",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT -- date(FROM_UNIXTIME(user_history.date)) AS date_group,\n      count(distinct guide_meta.guideid)\n      \n      -- distinct guide_meta.guideid, CURDATE(), guide_meta.created_date\nFROM guide_meta\n\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \n\nCASE\nWHEN $USERID != 'All Users'\nTHEN guide_meta.author = $USERID\nelse 1=1\nend\n\n\n-- and FROM_UNIXTIME(guide_meta.created_date) >= date_sub(CURDATE(),interval 1 month)\nand FROM_UNIXTIME(guide_meta.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(guide_meta.created_date) <= $__timeTo()\n\n-- group by guide_meta.guideid"
    }
   ]
  },
  {
   "title": "New Steps in New Guides",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT -- date(FROM_UNIXTIME(user_history.date)) AS date_group,\n       count(distinct guide_step_revisions.revisionid)\nFROM guide_step_revisions\ninner join guide_meta on guide_step_revisions.guideid=guide_meta.guideid\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \n\nguide_step_revisions.type = 'CREATED'\n\n\n\nand \n\nCASE\nWHEN $USERID != 'All Users'\nTHEN \nguide_step_revisions.userid = $USERID\nelse 1=1\nend\n\nand FROM_UNIXTIME(guide_step_revisions.date) >= $__timeFrom()\nand FROM_UNIXTIME(guide_step_revisions.date) <= $__timeTo()\nand FROM_UNIXTIME(guide_meta.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(guide_meta.created_date) <= $__timeTo()"
    }
   ]
  },
  {
   "title": "New Steps in Preexisting Guides",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT -- date(FROM_UNIXTIME(user_history.date)) AS date_group,\n       count(distinct guide_step_revisions.revisionid)\nFROM guide_step_revisions\ninner join guide_meta on guide_step_revisions.guideid=guide_meta.guideid\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \n\nguide_step_revisions.type = 'CREATED'\n\n\n\nand \n\nCASE\nWHEN $USERID != 'All Users'\nTHEN \nguide_step_revisions.userid = $USERID\nelse 1=1\nend\n\nand FROM_UNIXTIME(guide_step_revisions.date) >= $__timeFrom()\nand FROM_UNIXTIME(guide_step_revisions.date) <= $__timeTo()\nand FROM_UNIXTIME(guide_meta.created_date) < $__timeFrom()"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 }, "content": "<h2>New Guides\n<hr>" },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 }, "content": "<h3>New Guides by Month" },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "locale", "label": "New Guides" }
   ],
   "targets": [
    {
     "rawSql": "SELECT user_history.date as time, \n\n \nconcat(monthname(FROM_UNIXTIME(user_history.date)),\" \",year(FROM_UNIXTIME(user_history.date))) as metric,\n       count(historyid) as value\nFROM user_history\n\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \nuser_history.event = 'new_guide'\n\nand\n\nCASE\nWHEN $USERID != 'All Users'\nTHEN user_history.userid = $USERID\nelse 1=1\nend\n\nand\n\nFROM_UNIXTIME(user_history.date) >= $__timeFrom()\n\n\nand \n\nFROM_UNIXTIME(user_history.date) <= $__timeTo()\n\nGROUP BY \n\nyear(FROM_UNIXTIME(user_history.date)), month(FROM_UNIXTIME(user_history.date))\n\n\n\n-- order by \n\n-- year(FROM_UNIXTIME(user_history.date)) asc, month(FROM_UNIXTIME(user_history.date))\n;\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 }, "content": "<hr>" },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 }, "content": "<h3>New Guides by User" },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT  \nguide_text.title as \"Guide Title\",\nguide_meta.guideid as \"Guide ID\",\nglobal_users.username as \"Author\",\nFROM_UNIXTIME(guide_meta.created_date) as \"Guide Creation Date\"\n\n      \n      -- distinct guide_meta.guideid, CURDATE(), guide_meta.created_date\nFROM guide_current\nleft join guide_revisions on guide_revisions.guide_revisionid=guide_current.guide_revisionid\nleft join guide_meta on guide_revisions.gtr_revisionid=guide_meta.revisionid\nleft join global_users on global_users.userid=guide_meta.author\nleft join guide_text on guide_text.gt_revisionid=guide_revisions.gt_revisionid\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \n\nCASE\nWHEN $USERID != 'All Users'\nTHEN guide_meta.author = $USERID\nelse 1=1\nend\n\n\n-- and FROM_UNIXTIME(guide_meta.created_date) >= date_sub(CURDATE(),interval 1 month)\nand FROM_UNIXTIME(guide_meta.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(guide_meta.created_date) <= $__timeTo()\n\n-- \ngroup by guide_meta.guideid"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 }, "content": "<h3>New Steps in New Guides" },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n\nguide_text.title,\nguide_meta.guideid, \nglobal_users.username as \"Author\",\nfrom_unixtime(guide_meta.created_date) as \"Guide Creation Date\",\n-- guide_step_revisions.revisionid,\nguide_step_revisions.stepid as \"Step ID\",\nstep_number.orderby,\nfrom_unixtime(guide_step_revisions.date) as \"Step Creation Date\"\n\n\nFROM guide_step_revisions\n\nleft join (select guide_step_order_revisions.gtr_revisionid, guide_step_order_revisions.stepid, guide_step_order_revisions.orderby\n\nfrom guide_step_order_revisions\n\ninner join (Select stepid, max(gtr_revisionid) as maxrev\nfrom guide_step_order_revisions\ngroup by guide_step_order_revisions.stepid) mrv\n\non guide_step_order_revisions.gtr_revisionid=mrv.maxrev and guide_step_order_revisions.stepid=mrv.stepid) step_number on step_number.stepid = guide_step_revisions.stepid\n\nleft join guide_meta on guide_step_revisions.guideid = guide_meta.guideid\nleft join guide_revisions on guide_step_revisions.revisionid = guide_revisions.gsr_revisionid\nleft join guide_current on guide_revisions.guideid = guide_current.guideid and guide_revisions.guide_revisionid=guide_current.guide_revisionid\n\nleft join guide_text on guide_text.gt_revisionid = guide_revisions.gt_revisionid\nleft join global_users on global_users.userid=guide_step_revisions.userid\n\n\n\nwhere\nguide_step_revisions.type = 'CREATED'\n\n\n\nand\n\nCASE\nWHEN $USERID != 'All Users'\nTHEN\nguide_step_revisions.userid = $USERID\nelse 1=1\nend\n\n\nand FROM_UNIXTIME(guide_step_revisions.date) >= $__timeFrom()\nand FROM_UNIXTIME(guide_step_revisions.date) <= $__timeTo()\nand FROM_UNIXTIME(guide_meta.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(guide_meta.created_date) <= $__timeTo()\n\ngroup by guide_step_revisions.revisionid\n\norder by  guide_step_revisions.stepid desc, guide_meta.created_date desc"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
   "content": "<h3>New Steps in Existing Guides"
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\nguide_text.title,\nguide_meta.guideid, \n global_users.username as \"Author\",\nfrom_unixtime(guide_meta.created_date) as \"Guide Creation Date\",\n-- guide_step_revisions.revisionid,\nguide_step_revisions.stepid,\nstep_number.orderby,\nfrom_unixtime(guide_step_revisions.date) as \"Step Creation Date\"\n\n\nFROM guide_step_revisions\n\nleft join (select guide_step_order_revisions.gtr_revisionid, guide_step_order_revisions.stepid, guide_step_order_revisions.orderby\n\nfrom guide_step_order_revisions\n\ninner join (Select stepid, max(gtr_revisionid) as maxrev\nfrom guide_step_order_revisions\ngroup by guide_step_order_revisions.stepid) mrv\n\non guide_step_order_revisions.gtr_revisionid=mrv.maxrev and guide_step_order_revisions.stepid=mrv.stepid) step_number on step_number.stepid = guide_step_revisions.stepid\n\nleft join guide_meta on guide_step_revisions.guideid = guide_meta.guideid\nleft join guide_revisions on guide_step_revisions.revisionid = guide_revisions.gsr_revisionid\nleft join guide_current on guide_revisions.guideid = guide_current.guideid and guide_revisions.guide_revisionid=guide_current.guide_revisionid\n\nleft join guide_text on guide_text.gt_revisionid = guide_revisions.gt_revisionid\nleft join global_users on global_users.userid=guide_step_revisions.userid\n\n\n\nwhere\nguide_step_revisions.type = 'CREATED'\n\n\n\nand\n\nCASE\nWHEN $USERID != 'All Users'\nTHEN\nguide_step_revisions.userid = $USERID\nelse 1=1\nend\n\n\nand FROM_UNIXTIME(guide_step_revisions.date) >= $__timeFrom()\nand FROM_UNIXTIME(guide_step_revisions.date) <= $__timeTo()\nand FROM_UNIXTIME(guide_meta.created_date) <= $__timeFrom()\n\ngroup by guide_step_revisions.revisionid\n\norder by guide_meta.created_date desc, guide_step_revisions.stepid desc"
    }
   ]
  }
 ]
}