{
 "title": "New Item Content",
 "description": "New guides and guide steps.",
 "tags": [
  "Content",
  "New Item Content"
 ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "GUIDE_DB", "label": "Guide Database", "query": "mysql" },
   { "name": "SITE_NAME", "label": "Site Name", "query": "onprem" },
   {
    "name": "USERID",
    "label": "User",
    "query": "select  CONCAT(global_users.username, \" — \", \"User ID:\", global_users.userid) AS __text, global_users.userid AS __value from global_users"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Filtered by date range and user.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "content": "# New Item Content\n*New items created for new and existing guides.*"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "content": "<h2>New Items Overview</h2>\n<hr>"
  },
  {
   "title": "New Items",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n      count(distinct wikis.wikiid)\n      \nFROM wikis\n\nwhere \n\nCASE\nWHEN $USERID != 'All Users'\nTHEN wikis.author = $USERID\nelse 1=1\nend\n\nand wikis.namespace='ITEM'\n\nand FROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(wikis.created_date) <= $__timeTo()"
    }
   ]
  },
  {
   "title": "New Items in New Guides",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n      count(distinct wikis.wikiid)\n      \nFROM guide_current gc\n\nleft join guide_revisions gr on gc.guide_revisionid=gr.guide_revisionid\nleft join guide_item_revisions gir on gr.gtr_revisionid=gir.gtr_revisionid\nleft join wikis on wikis.wikiid=gir.wikiid\nleft join guide_meta gm on gm.revisionid=gr.gtr_revisionid\n\nwhere \n\nCASE\nWHEN $USERID != 'All Users'\nTHEN wikis.author = $USERID\nelse 1=1\nend\n\nand wikis.namespace='ITEM'\nand FROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(wikis.created_date) <= $__timeTo()\nand FROM_UNIXTIME(gm.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(gm.created_date) <= $__timeTo()"
    }
   ]
  },
  {
   "title": "New Items in Preexisting Guides",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n      count(distinct wikis.wikiid)\n      \nFROM guide_current gc\n\nleft join guide_revisions gr on gc.guide_revisionid=gr.guide_revisionid\nleft join guide_item_revisions gir on gr.gtr_revisionid=gir.gtr_revisionid\nleft join wikis on wikis.wikiid=gir.wikiid\nleft join guide_meta gm on gm.revisionid=gr.gtr_revisionid\n\nwhere \n\nCASE\nWHEN $USERID != 'All Users'\nTHEN wikis.author = $USERID\nelse 1=1\nend\n\nand wikis.namespace='ITEM'\nand FROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(wikis.created_date) <= $__timeTo()\nand FROM_UNIXTIME(gm.created_date) < $__timeFrom()"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 }, "content": "<h2>New Items\n<hr>" },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 }, "content": "<h3>New Items by Month" },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "locale", "label": "New Guides" }
   ],
   "targets": [
    {
     "rawSql": "SELECT wikis.created_date as time, \n\nconcat(monthname(FROM_UNIXTIME(wikis.created_date)),\" \",year(FROM_UNIXTIME(wikis.created_date))) as metric,\n       count(wikis.wikiid) as value\nFROM wikis\n\n\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\n-- from guide_authors \nwhere \nwikis.namespace = 'ITEM'\n\nand\n\nCASE\nWHEN $USERID != 'All Users'\nTHEN wikis.author = $USERID\nelse 1=1\nend\n\nand\n\nFROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\n\n\nand \n\nFROM_UNIXTIME(wikis.created_date) <= $__timeTo()\n\nGROUP BY \n\nyear(FROM_UNIXTIME(wikis.created_date)), month(FROM_UNIXTIME(wikis.created_date))\n\n;\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 }, "content": "<hr>" },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 }, "content": "<h3>New Items by User" },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT \n      wikis.title, wikis.wikiid,global_users.username as \"Author\", FROM_UNIXTIME(wikis.created_date) as item_date,\n      \n      CASE\n      when wikis.text!=\" \"\n      then \"Active\"\n      Else \"Deleted\"\n      end as \"Status\"\n      \nFROM wikis\nleft join global_users on global_users.userid=wikis.author\nwhere \n\nCASE\nWHEN $USERID != 'All Users'\nTHEN wikis.author = $USERID\nelse 1=1\nend\n\nand wikis.namespace='ITEM'\n\nand FROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(wikis.created_date) <= $__timeTo()"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 }, "content": "<h3>New Items in New Guides" },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT  wikis.title, wikis.wikiid,global_users.username as \"Author\", FROM_UNIXTIME(wikis.created_date) as item_date, \n\nCASE\nwhen wikis.text!=\" \"\nthen \"Active\"\nElse \"Deleted\"\nend as \"Status\"\n      \nFROM guide_current gc\n\nleft join guide_revisions gr on gc.guide_revisionid=gr.guide_revisionid\nleft join guide_item_revisions gir on gr.gtr_revisionid=gir.gtr_revisionid\nleft join wikis on wikis.wikiid=gir.wikiid\nleft join guide_meta gm on gm.revisionid=gr.gtr_revisionid\nleft join global_users on global_users.userid=wikis.author\n\nwhere \n\nCASE\nWHEN $USERID != 'All Users'\nTHEN wikis.author = $USERID\nelse 1=1\nend\n\nand wikis.namespace='ITEM'\nand FROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(wikis.created_date) <= $__timeTo()\nand FROM_UNIXTIME(gm.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(gm.created_date) <= $__timeTo()"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
   "content": "<h3>New Items in Existing Guides"
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT wikis.title, wikis.wikiid,global_users.username as \"Author\", FROM_UNIXTIME(wikis.created_date) as item_date,\n\nCASE\nwhen wikis.text!=\" \"\nthen \"Active\"\nElse \"Deleted\"\nend as \"Status\"\n      \nFROM guide_current gc\n\nleft join guide_revisions gr on gc.guide_revisionid=gr.guide_revisionid\nleft join guide_item_revisions gir on gr.gtr_revisionid=gir.gtr_revisionid\nleft join wikis on wikis.wikiid=gir.wikiid\nleft join guide_meta gm on gm.revisionid=gr.gtr_revisionid\nleft join global_users on global_users.userid=wikis.author\nwhere \n\nCASE\nWHEN $USERID != 'All Users'\nTHEN wikis.author = $USERID\nelse 1=1\nend\n\nand wikis.namespace='ITEM'\nand FROM_UNIXTIME(wikis.created_date) >= $__timeFrom()\nand FROM_UNIXTIME(wikis.created_date) <= $__timeTo()\nand FROM_UNIXTIME(gm.created_date) < $__timeFrom()"
    }
   ]
  }
 ]
}