{
 "title": "Process Status",
 "tags": [
  "Work Orders",
  "Process Status"
 ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "GUIDE_DB", "label": "Guide Database", "query": "mysql" },
   {
    "name": "GUIDE_ID",
    "label": "Guide",
    "query": "select guide_text.guideid AS __value,  CONCAT(guide_text.title, \" — \", \"Guide ID:\", guide_text.guideid) AS __text   from (select max(gt_revisionid) as gt_revisionid, guideid from guide_text group by guideid) x  left join guide_text on guide_text.gt_revisionid=x.gt_revisionid"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "# Process Status\nSelect the process you'd like to monitor in real time."
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  { "type": "text", "gridPos": { "h": 3, "w": 23, "x": 0, "y": 3 }, "content": "<h2>Process Overview\n<hr>" },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "Select count(work_log.entryid) as metric\nfrom work_log\nWhere work_log.endtime is not null\nand work_log.cancelled!=1\nand FROM_UNIXTIME(work_log.starttime) >= $__timeFrom()\nand work_log.guideid=$GUIDE_ID\norder by work_log.starttime desc"
    }
   ]
  },
  {
   "title": "In Progress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "Select count(work_log.entryid) as metric\nfrom work_log\nWhere work_log.endtime is null\nand FROM_UNIXTIME(work_log.starttime) >= $__timeFrom()\n-- and work_log.cancelled!=1\nand work_log.guideid=$GUIDE_ID\norder by work_log.starttime desc"
    }
   ]
  },
  {
   "title": "Average Completion Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 6 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "Select avg(work_log.endtime-work_log.starttime) as av_duration_sec\nfrom work_log\nwhere work_log.endtime is not null\nand work_log.cancelled!=1\nand work_log.guideid = $GUIDE_ID\nand FROM_UNIXTIME(work_log.starttime) >= $__timeFrom()\norder by av_duration_sec desc\nlimit 1"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  { "type": "text", "gridPos": { "h": 3, "w": 23, "x": 0, "y": 10 }, "content": "<h2>Worker Performance\n<hr>" },
  {
   "title": "Slowest Worker",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "Select global_users.username, avg(work_log.endtime-work_log.starttime) as av_duration_sec\nfrom work_log\nINNER JOIN global_users on work_log.userid=global_users.userid  \n\nwhere work_log.endtime is not null\nand FROM_UNIXTIME(work_log.starttime) >= $__timeFrom()\nand work_log.cancelled!=1\nand work_log.guideid=$GUIDE_ID\ngroup by global_users.username\norder by av_duration_sec desc\nlimit 1\n"
    }
   ]
  },
  {
   "title": "Average Completion Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "Select avg(work_log.endtime-work_log.starttime) as av_duration_sec\nfrom work_log\nwhere work_log.endtime is not null\nand work_log.cancelled!=1\nand work_log.guideid = $GUIDE_ID\nand FROM_UNIXTIME(work_log.starttime) >= $__timeFrom()\ngroup by work_log.userid\norder by av_duration_sec desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Fastest Worker",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "Select global_users.username, avg(work_log.endtime-work_log.starttime) as av_duration_sec\nfrom work_log\nINNER JOIN global_users on work_log.userid=global_users.userid  \n\nwhere work_log.endtime is not null\nand FROM_UNIXTIME(work_log.starttime) >= $__timeFrom()\nand work_log.cancelled!=1\nand work_log.guideid=$GUIDE_ID\ngroup by global_users.username\norder by av_duration_sec asc\nlimit 1\n"
    }
   ]
  },
  {
   "title": "Average Completion Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 13 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "Select avg(work_log.endtime-work_log.starttime) as av_duration_sec\nfrom work_log\nwhere work_log.endtime is not null\nand work_log.cancelled!=1\nand work_log.guideid = $GUIDE_ID\nand FROM_UNIXTIME(work_log.starttime) >= $__timeFrom()\ngroup by work_log.userid\norder by av_duration_sec asc\nlimit 1"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 23, "x": 0, "y": 16 }, "content": "<hr>" },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 20 },
   "content": "<h3>Cycle Times vs Goal Times Trend"
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 1, "y": 22 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "rawSql": "select y.endingtime as time_sec, \"Median Duration\" as metric,\n-- wl.entryid, \n-- wl.guideid, \n-- wl.starttime, \n-- endtime, \n(wl.endtime - wl.starttime) as value \n-- ' (x.time_required_max -(y.endingtime - wl.starttime)) as past_due, \n-- x.time_required_max as \"Goal Time Max\", \n-- x.time_required_min as \"Goal Time Min\"    \n\nfrom work_log wl\n \njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid = $GUIDE_ID) x\nusing (guideid)\n \nJOIN (select entryid,\nCASE \n    WHEN endtime is NOT NULL \n\tthen endtime\n    ELSE 1 != 1\nEND as endingtime\nfrom work_log\nwhere guideid = $GUIDE_ID\nand work_log.cancelled!=1\nand date(from_unixtime(starttime)) >= $__timeFrom()\nand date(from_unixtime(endtime)) <= $__timeTo()\n\t ) y\nusing (entryid)\nwhere date(from_unixtime(wl.starttime)) >= $__timeFrom()\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\nand (x.time_required_max is not null or x.time_required_max != 0)\nand (x.time_required_min is not null or x.time_required_min != 0)\ngroup by date_format(FROM_UNIXTIME(y.endingtime),\"%y-%m-%d\")\norder by date_format(FROM_UNIXTIME(y.endingtime),\"%y-%m-%d\")"
    },
    {
     "rawSql": "select y.endingtime as time_sec, \n-- wl.entryid, \n-- wl.guideid, \n-- wl.starttime, \n-- endtime, \n-- (wl.endtime - wl.starttime) as duration, \n-- (x.time_required_max -(y.endingtime - wl.starttime)) as past_due, \nMax(x.time_required_max) as value,\n\"Goal Time Max\" as metric \n-- , x.time_required_min as \"Goal Time Min\"    \n\nfrom work_log wl\n \njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid = $GUIDE_ID) x\nusing (guideid)\n \nJOIN (select entryid,\nCASE \n    WHEN endtime is NOT NULL \n\tthen endtime\n    ELSE 1 != 1\nEND as endingtime\nfrom work_log\nwhere guideid = $GUIDE_ID\nand work_log.cancelled!=1\nand date(from_unixtime(starttime)) >= $__timeFrom()\nand date(from_unixtime(endtime)) <= $__timeTo()\n\t ) y\nusing (entryid)\nwhere date(from_unixtime(wl.starttime)) >= $__timeFrom()\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\nand (x.time_required_max is not null or x.time_required_max != 0)\nand (x.time_required_min is not null or x.time_required_min != 0)\ngroup by date_format(FROM_UNIXTIME(y.endingtime),\"%y-%m-%d\")\norder by date_format(FROM_UNIXTIME(y.endingtime),\"%y-%m-%d\")"
    },
    {
     "rawSql": "select y.endingtime as time_sec, \n-- wl.entryid, \n-- wl.guideid, \n-- wl.starttime, \n-- endtime, \n-- (wl.endtime - wl.starttime) as duration, \n-- (x.time_required_max -(y.endingtime - wl.starttime)) as past_due, \n-- x.time_required_max as \"Goal Time Max\", \nMIN(x.time_required_min) as value,\n\"Goal Time Min\" as metric   \n\nfrom work_log wl\n \njoin (select gc.guideid, gm.time_required_max, gm.time_required_min\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid = $GUIDE_ID) x\nusing (guideid)\n \nJOIN (select entryid,\nCASE \n    WHEN endtime is NOT NULL \n\tthen endtime\n    ELSE 1 != 1\nEND as endingtime\nfrom work_log\nwhere guideid = $GUIDE_ID\nand work_log.cancelled!=1\nand date(from_unixtime(starttime)) >= $__timeFrom()\nand date(from_unixtime(endtime)) <= $__timeTo()\n\t ) y\nusing (entryid)\nwhere date(from_unixtime(wl.starttime)) >= $__timeFrom()\nand date(from_unixtime(wl.endtime)) <= $__timeTo()\nand (x.time_required_max is not null or x.time_required_max != 0)\nand (x.time_required_min is not null or x.time_required_min != 0)\ngroup by date_format(FROM_UNIXTIME(y.endingtime),\"%y-%m-%d\")\norder by date_format(FROM_UNIXTIME(y.endingtime),\"%y-%m-%d\")"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 32 },
   "content": " \n \n<h3>Process Time Distribution (Per Step)"
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none", "label": "Step Duration" }
   ],
   "targets": [
    {
     "rawSql": "select \n-- wlt.entryid, \n-- wlt.stepid, \ncast(y.orderby AS CHAR) as metric, \nAVG((wlt.date_end - wlt.date_start)/60.00) as value, \nstarttime as time_sec\nfrom work_log_timing wlt \njoin (select entryid, userid, starttime, endtime\nfrom work_log\nwhere date(from_unixtime(starttime)) >= $__timeFrom()\nand date(from_unixtime(endtime)) <= $__timeTo()\nand guideid = $GUIDE_ID) x using (entryid)\njoin (SELECT gsor.stepid, gsor.orderby\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nJOIN guide_step_order_revisions gsor USING (gtr_revisionid)\nWHERE gc.guideid = $GUIDE_ID\nand gc.langid = 'en'\norder by gsor.orderby asc) y on (wlt.stepid = y.stepid)\nwhere wlt.stepid is not null\nand wlt.date_end is not null\nand wlt.date_start is not null\ngroup by wlt.stepid"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  { "type": "text", "gridPos": { "h": 2, "w": 23, "x": 0, "y": 43 }, "content": " \n \n<h3>Work Order Details" },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 22, "x": 1, "y": 45 },
   "targets": [
    {
     "rawSql": "Select \r\nwork_log.workorderid as \"Workorder ID\", \r\nFROM_UNIXTIME(work_log.starttime) as \"Start Time\",\r\nguide_text.title as \"Guide Name\", \r\nglobal_users.username as \"User\",\r\n(work_log.endtime-work_log.starttime)/60.00 as 'Duration',\r\nguide_meta.time_required_max/60.00 as \"Goal Time Minutes\"\r\n-- CASE \r\n    -- WHEN work_log.starttime is NULL then \"In Progress\"\r\n    -- ELSE SEC_TO_TIME(work_log.endtime - work_log.starttime)\r\n-- END as \"Duration\",\r\n\r\nFrom work_log\r\n\r\nINNER JOIN global_users on work_log.userid=global_users.userid  \r\n\r\n\r\nINNER JOIN (\r\n    SELECT gtr_revisionid, guideid, MAX(guide_revisionid) AS maxrevision FROM guide_revisions GROUP BY guideid\r\n  ) maxrev ON maxrev.guideid = work_log.guideid \r\n\r\nJOIN guide_revisions ON guide_revisions.guide_revisionid = maxrev.maxrevision\r\n\r\n\r\nJOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\r\nJOIN guide_text ON guide_text.gt_revisionid = guide_revisions.gt_revisionid\r\n\r\n\r\nwhere date(FROM_UNIXTIME(work_log.starttime)) >= $__timeFrom()\r\nand date(FROM_UNIXTIME(work_log.endtime)) <= $__timeTo()\r\nand work_log.guideid=$GUIDE_ID\r\nand work_log.cancelled!=1\r\n\r\norder by work_log.starttime desc\r\n\r\n"
    }
   ]
  }
 ]
}