{
 "title": "User Work Experience",
 "tags": [
  "Worker Training",
  "User Work Experience"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "USERID",
    "label": "User",
    "query": "select  CONCAT(global_users.username, \" — \", \"User ID:\", global_users.userid) AS __text, global_users.userid AS __value from global_users"
   },
   { "name": "GUIDE_DB", "label": "Guide Database", "query": "mysql" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "<h1>User Experience Dashboard" },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select username as \"User Name\" from global_users u where userid= $USERID;\n"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "GUIDE_DB" },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 }, "content": "<h2>User Information\n<hr>" },
  {
   "title": "email",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \n\nglobal_users.login as \"Email\"\nfrom global_users\nwhere global_users.userid= $USERID\nlimit 1;"
    }
   ]
  },
  {
   "title": "Join Date",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select date_format(FROM_UNIXTIME(global_users.join_date), \"%M %d %Y\") as \"Join Date\"\nfrom global_users\nwhere global_users.userid= $USERID\nlimit 1;"
    }
   ]
  },
  {
   "title": "Reputation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select reputation as \"Reputation\" from users  where userid= $USERID;"
    }
   ]
  },
  {
   "title": "Completed Work Orders",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "Select count(*)\nFROM work_log\n\nINNER JOIN global_users on work_log.userid=global_users.userid \n\n\n INNER JOIN (\n    SELECT gtr_revisionid, guideid, MAX(guide_revisionid) AS maxrevision FROM guide_revisions GROUP BY guideid\n  ) maxrev ON maxrev.guideid = work_log.guideid \n\nJOIN guide_revisions ON guide_revisions.guide_revisionid = maxrev.maxrevision\n\nJOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\nJOIN guide_text ON guide_text.gt_revisionid = guide_revisions.gt_revisionid\n\nWHERE work_log.userid = $USERID"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 }, "content": "<h2>Guide Experience\n<hr>" },
  {
   "title": "Completed Standard Guides",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT guide_text.title AS metric,\r\nuser_success.date as time_sec,\r\ncount(user_success.guideid) AS value\r\n\r\nFROM user_success\r\n\r\nINNER JOIN global_users on user_success.userid=global_users.userid  \r\n-- INNER JOIN guide_current ON user_success.guideid = guide_current.guideid\r\n\r\n\r\n-- JOIN guide_revisions ON guide_revisions.guideid = user_success.guideid\r\n\r\n\r\n INNER JOIN (\r\n    SELECT gtr_revisionid, guideid, MAX(guide_revisionid) AS maxrevision FROM guide_revisions GROUP BY guideid\r\n  ) maxrev ON maxrev.guideid = user_success.guideid \r\n  \r\n  -- AND maxrev.guide_revisionid = maxrevision\r\nJOIN guide_revisions ON guide_revisions.guide_revisionid = maxrev.maxrevision\r\n\r\nJOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\r\nJOIN guide_text ON guide_text.gt_revisionid = guide_revisions.gt_revisionid\r\n\r\nWHERE user_success.userid = $USERID\r\nAND user_success.date >1\r\n\r\nGROUP BY user_success.guideid\r\nLIMIT 20 ;\r\n"
    }
   ]
  },
  {
   "title": "Department Experience",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 37 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT guide_meta.device AS metric, \r\nwork_log.starttime AS time_sec,\r\ncount(work_log.workorderid) as value\r\n\r\nFROM work_log\r\n\r\nINNER JOIN global_users on work_log.userid=global_users.userid  \r\nINNER JOIN (\r\n    SELECT gtr_revisionid, guideid, MAX(guide_revisionid) AS maxrevision FROM guide_revisions GROUP BY guideid\r\n  ) maxrev ON maxrev.guideid = work_log.guideid \r\n\r\nJOIN guide_revisions ON guide_revisions.guide_revisionid = maxrev.maxrevision\r\n\r\n\r\nJOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\r\nJOIN guide_text ON guide_text.gt_revisionid = guide_revisions.gt_revisionid\r\n\r\n\r\n-- JOIN guide_meta ON work_log.guideid = guide_meta.guideid\r\n\r\nWHERE work_log.userid = $USERID\r\nAND work_log.cancelled<>1\r\nand work_log.starttime>0\r\nGROUP BY guide_meta.device\r\norder by count(work_log.workorderid) desc, guide_meta.device\r\n;\r\n"
    }
   ]
  },
  {
   "title": "Work Orders",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 37 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT guide_text.title AS metric,\r\nwork_log.endtime AS time_sec,\r\ncount(work_log.workorderid) AS value\r\nFROM work_log\r\n\r\nINNER JOIN global_users on work_log.userid=global_users.userid  \r\n\r\n\r\nINNER JOIN (SELECT gtr_revisionid, guideid, MAX(guide_revisionid) AS maxrevision FROM guide_revisions GROUP BY guideid) maxrev ON maxrev.guideid = work_log.guideid \r\n\r\nJOIN guide_revisions ON guide_revisions.guide_revisionid = maxrev.maxrevision\r\n\r\n\r\n\r\nJOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\r\nJOIN guide_text ON guide_text.gt_revisionid = guide_revisions.gt_revisionid\r\n\r\n\r\n\r\n\r\nWHERE work_log.userid = $USERID\r\nAND work_log.endtime >1\r\nGROUP BY work_log.guideid\r\norder by count(work_log.workorderid) desc\r\nlimit 7\r\n;\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 48 }, "content": "<hr>" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "content": "<h3>Views and Work Orders Over Time\n"
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT work_log.endtime AS time_sec,\r\n-- work_log.userid as metric,\r\n\"Completed Work Orders\" as metric,\r\ncount(work_log.entryid) as value\r\nFROM work_log\r\n\r\nINNER JOIN global_users on work_log.userid = global_users.userid\r\nwhere work_log.endtime >= global_users.join_date\r\n\r\nand work_log.userid= $USERID\r\n-- and work_log.endtime >0\r\nGROUP BY DATE_FORMAT(FROM_UNIXTIME(work_log.endtime),'%y-%m')\r\n;\r\n"
    },
    {
     "rawSql": "SELECT user_view_history.date AS time_sec,\n\"Guide Views\" as metric,\ncount(user_view_history.historyid) as value\nFROM user_view_history\n\n\nINNER JOIN global_users on user_view_history.userid = global_users.userid\nwhere user_view_history.date >= global_users.join_date\n\n\nand user_view_history.userid= $USERID\nand user_view_history.doc_type= 'GUIDE'\n-- and user_view_history.date >0\ngroup by date_format(FROM_UNIXTIME(user_view_history.date),'%y-%m')\norder by time_sec\n;\n"
    },
    {
     "rawSql": "SELECT user_view_history.date AS time_sec,\r\n\"Wiki Views\" as metric,\r\ncount(user_view_history.historyid) as value\r\nFROM user_view_history\r\n\r\n-- where from_unixtime(user_view_history.date, '%Y-%m-%d') > curdate() - INTERVAL 2 year\r\n\r\nINNER JOIN global_users on user_view_history.userid = global_users.userid\r\nwhere user_view_history.date >= global_users.join_date\r\n\r\n\r\nand user_view_history.userid= $USERID\r\nand user_view_history.doc_type= 'WIKI'\r\n\r\nGROUP BY date_format(FROM_UNIXTIME(user_view_history.date),'%y-%m');\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 61 }, "content": "<h3>Completed Work Orders" },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none", "label": "Completed Work Orders" }
   ],
   "targets": [
    {
     "rawSql": "SELECT guide_text.title AS metric,   \r\nwork_log.starttime as time_sec,      \r\ncount(work_log.workorderid) AS value\r\n\r\nFROM work_log\r\n\r\nINNER JOIN global_users on work_log.userid=global_users.userid \r\n\r\nINNER JOIN (\r\n    SELECT gtr_revisionid, guideid, MAX(guide_revisionid) AS maxrevision FROM guide_revisions GROUP BY guideid\r\n  ) maxrev ON maxrev.guideid = work_log.guideid \r\n\r\nJOIN guide_revisions ON guide_revisions.guide_revisionid = maxrev.maxrevision\r\n\r\n\r\n\r\nJOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\r\nJOIN guide_text ON guide_text.gt_revisionid = guide_revisions.gt_revisionid\r\n\r\nWHERE work_log.userid = $USERID\r\nand work_log.starttime >0\r\n\r\nGROUP BY guide_text.guideid\r\norder by count(work_log.workorderid) desc\r\nLIMIT 7;\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 72 }, "content": "<h3>Guide Views" },
  { "type": "text", "gridPos": { "h": 1, "w": 13, "x": 0, "y": 74 } },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short", "label": "Guide Views" }
   ],
   "targets": [
    {
     "rawSql": "SELECT guide_text.title AS metric,\r\nuser_view_history.date as time_sec,\r\n-- guide_text.guideid,\r\ncount(user_view_history.historyid) AS value\r\n\r\nFROM user_view_history\r\n\r\n-- INNER JOIN global_users on user_view_history.userid=global_users.userid  \r\n\r\n-- INNER JOIN guide_current ON user_view_history.docid = guide_current.guideid\r\n\r\n-- JOIN guide_revisions ON guide_revisions.guide_revisionid = guide_current.guide_revisionid\r\n\r\n\r\nINNER JOIN (\r\n    SELECT gtr_revisionid, guideid, MAX(guide_revisionid) AS maxrevision3 FROM guide_revisions GROUP BY guideid\r\n  ) maxrev3 ON maxrev3.guideid = user_view_history.docid \r\n  \r\nINNER JOIN guide_revisions ON guide_revisions.guide_revisionid = maxrev3.maxrevision3\r\n\r\n\r\nJOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\r\nJOIN guide_text ON guide_text.gt_revisionid = guide_revisions.gt_revisionid\r\n\r\n-- JOIN guide_meta ON work_log.guideid = guide_meta.guideid\r\n\r\nWHERE user_view_history.userid = $USERID\r\nand user_view_history.doc_type= \"GUIDE\"\r\nGROUP BY guide_text.guideid\r\norder by count(user_view_history.historyid) desc\r\nLIMIT 7;\r\n"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 84 },
   "content": "<h2>Popular Content</h2>\n<em>The most accessed content created by this user.</em>\n<hr>"
  },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 88 }, "content": "<h1>Top Guide:\n" },
  { "type": "text", "gridPos": { "h": 2, "w": 10, "x": 11, "y": 88 }, "content": "<h1>Top Question:\n" },
  {
   "type": "singlestat",
   "description": "Most viewed guide created by this user.",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 90 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \r\n\r\nconcat(guide_text.title,CONVERT(X'C2A0' USING utf8), \"  (\", \"Guide ID  \", guide_authors.guideid,\"):   \",CONVERT(X'C2A0' USING utf8),CONVERT(X'C2A0' USING utf8),CONVERT(X'C2A0' USING utf8),CONVERT(X'C2A0' USING utf8), count(user_view_history.historyid),  \" Views\") as \"Guide\"\r\n\r\n\r\nFROM user_view_history\r\n\r\n-- INNER JOIN global_users on work_log.userid=global_users.userid  \r\n\r\n\r\nINNER JOIN (\r\n    SELECT gtr_revisionid, guideid, MAX(guide_revisionid) AS auth_max_revision FROM guide_revisions GROUP BY guideid\r\n  ) auth_maxrev ON auth_maxrev.guideid = user_view_history.docid \r\n\r\nJOIN guide_revisions ON guide_revisions.guide_revisionid = auth_maxrev.auth_max_revision\r\n\r\nJOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\r\nJOIN guide_text ON guide_text.gt_revisionid = guide_revisions.gt_revisionid\r\n\r\n\r\nINNER JOIN (\r\n    SELECT percent as auth_percent, last_contribution, guideid, userid AS authorid FROM guide_authors GROUP BY guideid\r\n  ) guideauthors ON guideauthors.guideid = user_view_history.docid \r\n\r\njoin guide_authors on guide_authors.guideid = guideauthors.guideid\r\n\r\n-- JOIN guide_meta ON work_log.guideid = guide_meta.guideid\r\nWhere user_view_history.doc_type = 'Guide'\r\nand guide_authors.userid = $USERID\r\nand guide_authors.percent >= 10\r\n\r\n-- GROUP BY guide_text.title\r\nGROUP BY guide_authors.guideid\r\n\r\norder by count(user_view_history.historyid) desc\r\n\r\nlimit 1;\r\n"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Most viewed question from this user.",
   "gridPos": { "h": 3, "w": 10, "x": 11, "y": 90 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT -- postid AS `PostID`, --\r\n\r\nconcat(title,\": \",space(10),CONVERT(X'C2A0' USING utf8),CONVERT(X'C2A0' USING utf8),value,\"  Views\") as Post\r\n       -- device AS `Device`, --\r\n       -- value AS `Views` --\r\n\t   -- userid as 'User' --\r\n\tFROM stats_per_month stm\r\n\tJOIN posts p ON (stm.id = p.postid)\r\n\tWHERE stm.metric = 'hits' AND\r\n\tuserid= $USERID AND\r\n\t\t  stm.type = 'post'\r\n\tORDER BY value \t\r\n\tDESC LIMIT 1;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 93 }, "content": "<h3>Most Popular Guides" },
  {
   "type": "graph",
   "description": "The most accessed guides written by this user.",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "none", "label": "Total Guide Views" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n-- concat(guide_text.title, \"  (\", \"Guide ID: \", guide_authors.guideid, \")\") as \"name\",\nguide_text.title as metric,\nuser_view_history.date AS time_sec,\n-- guide_authors.percent as \"Percentage\",  \ncount(user_view_history.historyid) AS value\n\nFROM user_view_history\n\n-- INNER JOIN global_users on work_log.userid=global_users.userid  \n\n\nINNER JOIN (\n    SELECT gtr_revisionid, guideid, MAX(guide_revisionid) AS auth_max_revision FROM guide_revisions GROUP BY guideid\n  ) auth_maxrev ON auth_maxrev.guideid = user_view_history.docid \n\nJOIN guide_revisions ON guide_revisions.guide_revisionid = auth_maxrev.auth_max_revision\n\nJOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\nJOIN guide_text ON guide_text.gt_revisionid = guide_revisions.gt_revisionid\n\n\nINNER JOIN (\n    SELECT percent as auth_percent, last_contribution, guideid, userid AS authorid FROM guide_authors GROUP BY guideid\n  ) guideauthors ON guideauthors.guideid = user_view_history.docid \n\njoin guide_authors on guide_authors.guideid = guideauthors.guideid\n\n-- JOIN guide_meta ON work_log.guideid = guide_meta.guideid\nWhere user_view_history.doc_type = 'Guide'\nand guide_authors.userid = $USERID\nand guide_authors.percent >= 10\n\n-- GROUP BY guide_text.title\nGROUP BY guide_authors.guideid\n\norder by count(user_view_history.historyid) desc\n\nlimit 7;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 102 }, "content": "<h3>Most Used Guides" },
  {
   "type": "graph",
   "description": "Completed work orders for guides authored by this user.",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short", "label": "Completed Work Orders" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n-- concat(guide_text.title, \"  (\", \"Guide ID: \", guide_authors.guideid, \")\") as \"Guide\",\r\nguide_text.title as metric,\r\nwork_log.starttime as time_sec,\r\n-- guide_authors.percent as \"Percentage\",  \r\ncount(work_log.entryid) AS value\r\n\r\nFROM work_log\r\n\r\n-- INNER JOIN global_users on work_log.userid=global_users.userid  \r\n\r\nINNER JOIN \r\n(SELECT gtr_revisionid, guideid, MAX(guide_revisionid) AS maxrevision FROM guide_revisions GROUP BY guideid) \r\nmaxrev ON maxrev.guideid = work_log.guideid \r\n\r\nJOIN guide_revisions ON guide_revisions.guide_revisionid = maxrev.maxrevision\r\nJOIN guide_meta ON guide_revisions.gtr_revisionid = guide_meta.revisionid\r\nJOIN guide_text ON guide_text.gt_revisionid = guide_revisions.gt_revisionid\r\n\r\n\r\nINNER JOIN (\r\n    SELECT percent as auth_percent, last_contribution, guideid, userid AS authorid FROM guide_authors GROUP BY guideid\r\n  ) guideauthors ON guideauthors.guideid = work_log.guideid \r\n\r\njoin guide_authors on guide_authors.guideid = guideauthors.guideid\r\n\r\n-- JOIN guide_meta ON work_log.guideid = guide_meta.guideid\r\n\r\nWhere guide_authors.userid = $USERID\r\nand work_log.cancelled <> 1\r\nand guide_authors.percent >= 5\r\n\r\n-- GROUP BY guide_text.title\r\nGROUP BY guide_authors.guideid\r\n\r\norder by count(work_log.entryid) desc\r\n\r\nlimit 7;\r\n"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 113 },
   "content": "<h2>Contribution History</h2>\nAn overview of content created by this author.\n<hr>"
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 117 }, "content": "<h3>Recent Author Activity" },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "none", "label": "Contributions" }
   ],
   "targets": [
    {
     "rawSql": "SELECT guide_authors.last_contribution AS time_sec,\r\n\"Recent Contributions\" as metric,\r\ncount(guide_authors.guideid) as value\r\nFROM guide_authors\r\n\r\n\r\n-- SELECT guideid as \"Guide ID\", percent as \"Percentage\"\r\n-- from {GUIDE_DB.RAW}.guide_authors \r\nwhere userid= $USERID\r\n\r\nGROUP BY DATE_FORMAT(FROM_UNIXTIME(guide_authors.last_contribution),'%Y-%m')\r\n;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 125 }, "content": "<h3>Guide Releases Over Time" },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT releases.release_date AS time_sec,\n\"Guide Releases\" as metric,\ncount(releases.releaseid) as value\n\nFROM releases\n\nINNER JOIN global_users on releases.userid = global_users.userid\nwhere releases.doctype='GUIDE'\nand releases.release_date >= global_users.join_date\nand releases.userid= $USERID\n\nGROUP BY DATE_FORMAT(FROM_UNIXTIME(releases.release_date),'%y-%m-%d');\n\n"
    },
    {
     "rawSql": "SELECT guide_meta.date AS time_sec,\r\n\"Guide Edits\" as metric,\r\ncount(guide_meta.revisionid) as value\r\nFROM guide_meta\r\n\r\nINNER JOIN global_users on guide_meta.userid = global_users.userid\r\nwhere guide_meta.date >= global_users.join_date\r\n\r\nand guide_meta.userid= $USERID\r\n\r\n\r\nGROUP BY DATE_FORMAT(FROM_UNIXTIME(guide_meta.date),'%y-%m-%d')\r\n\r\n;\r\n"
    },
    {
     "rawSql": "SELECT guide_authors.last_contribution AS time_sec,\r\n\"Authorship\" as metric,\r\ncount(guide_authors.guideid) as value\r\nFROM guide_authors\r\n\r\nINNER JOIN global_users on guide_authors.userid = global_users.userid\r\nwhere guide_authors.last_contribution >= global_users.join_date\r\nand guide_authors.percent >= 10\r\n\r\nand guide_authors.userid= $USERID\r\n\r\nGROUP BY DATE_FORMAT(FROM_UNIXTIME(guide_authors.last_contribution),'%y-%m-%d');\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 133 }, "content": "<h3>Guide Edits Over Time" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short", "label": "Recent Edits to Guides" }
   ],
   "targets": [
    {
     "rawSql": "SELECT guide_meta.date AS time_sec,\r\n\"Recent Edits\" as metric,\r\ncount(guide_meta.revisionid) as value\r\nFROM guide_meta\r\n\r\nINNER JOIN global_users on guide_meta.userid = global_users.userid\r\nwhere guide_meta.date >= global_users.join_date\r\n\r\nand guide_meta.userid= $USERID\r\n\r\n-- GROUP BY guide_meta.date\r\nGROUP BY DATE_FORMAT(FROM_UNIXTIME(guide_meta.date),'%y-%m-%d');"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 142 }, "content": "<h3>Reputation" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT user_history.date AS time_sec,\r\n\"Reputation\" as metric,\r\nSum(\r\nuser_history.rewarded\r\n\t   ) as value\r\nFROM user_history\r\n\r\n\r\nINNER JOIN global_users on user_history.userid = global_users.userid\r\n\r\nwhere from_unixtime(user_history.date) > from_unixtime(global_users.join_date)\r\n\r\nand user_history.userid= $USERID\r\nand user_history.rewarded >= 0\r\nGROUP BY \r\nDATE(FROM_UNIXTIME(user_history.date))\r\n-- YEARWEEK(FROM_UNIXTIME(user_history.date))\r\n;\r\n"
    },
    {
     "rawSql": "SELECT user_history.date AS time_sec,\n\"Total Reputation\" as metric,\n\t   \n\t   \n\t      -- (@runtot := @runtot + user_history.rewarded) AS \"Total Reputation\"\n(SELECT SUM(h.rewarded)\nFROM user_history as h\nWHERE h.userid = user_history.userid\nAND DATE(FROM_UNIXTIME(user_history.date)) >= DATE(FROM_UNIXTIME(h.date)) \n)\nAS value\n\t   \nFROM user_history\nINNER JOIN global_users on user_history.userid = global_users.userid\nwhere user_history.date >= global_users.join_date\nand user_history.userid= $USERID\nand user_history.rewarded > 0\nGROUP BY DATE(FROM_UNIXTIME(user_history.date))\n-- GROUP BY DATE_FORMAT(FROM_UNIXTIME(user_history.date),'%y-%m-d%')\n-- GROUP BY YEARWEEK(FROM_UNIXTIME(user_history.date))\n;\n\n"
    }
   ]
  }
 ]
}