{
 "title": "Work Order Signoff Status",
 "tags": [
  "Work Orders",
  "Work Order Signoff Status"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "GUIDE_DB", "label": "Guide Database", "query": "mysql" },
   {
    "name": "WORKORDERID",
    "label": "Work Order ID",
    "query": "select  work_log.workorderid  from work_log"
   },
   {
    "name": "CATEGORYID",
    "label": "Category",
    "query": "select  list.title as \"Category\" from (select distinct title from wikis where wikis.namespace=\"TOPIC\") list order by 'All Categories', title ASC"
   },
   {
    "name": "GUIDE_ID",
    "label": "Guide",
    "query": "select guide_text.guideid AS __value,  CONCAT(guide_text.title, \" — \", \"Guide ID:\", guide_text.guideid) AS __text   from (select max(gt_revisionid) as gt_revisionid, guideid from guide_text group by guideid) x  left join guide_text on guide_text.gt_revisionid=x.gt_revisionid"
   },
   { "name": "SITE_NAME", "label": "Site Name", "query": "onprem" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 0 },
   "options": {
    "content": "# Work Order Signoff Status\nLook up the current \"route\" and signoff status of a given work order."
   },
   "content": "# Work Order Signoff Status\nLook up the current \"route\" and signoff status of a given work order."
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "<h1>Current Route Selected\n<hr>"
   },
   "content": "<h1>Current Route Selected\n<hr>"
  },
  {
   "title": "Work Order Route",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT  \r\n       @rownum := @rownum + 1 AS \"Route Step\", t.*\r\n  FROM (SELECT DISTINCT  `gt`.`title`  As \"Guide Title\", `gm`.`device` as \"Category\", `gc`.`guideid` As \"Guide ID\" ,\r\n\t\tCASE\r\n\t\t WHEN gm.time_required_min is not null \r\n\t\t THEN SEC_TO_TIME(gm.time_required_min) \r\n\t\t ELSE 0\r\n\t\tEND as \"Minimum Time\", \r\n\t\tCASE\r\n\t\t WHEN gm.time_required_max is not null \r\n\t\t THEN SEC_TO_TIME(gm.time_required_max) \r\n\t\t ELSE 0\r\n\t\tEND as \"Maximum Time\"\r\nFROM `guide_current` `gc`\r\nJOIN `guide_revisions` `gr` USING (`guide_revisionid`)\r\nJOIN `guide_meta` `gm` ON `gm`.`revisionid` = `gr`.`gtr_revisionid`\r\nJOIN `guide_text` `gt` ON `gr`.`gt_revisionid` = `gt`.`gt_revisionid`\r\nLEFT JOIN `work_log` `wl` ON `gc`.`guideid` = `wl`.`guideid`\r\n\r\nWHERE \r\nCASE \r\n\tWHEN $WORKORDERID = 'All Work Orders' AND $CATEGORYID = 'All Categories'\r\n\tTHEN 1 = 1\r\n\t\r\n\tWHEN $WORKORDERID = 'All Work Orders' AND $CATEGORYID != 'All Categories'\r\n\tTHEN gm.device = $CATEGORYID\r\n\t\r\n\tWHEN $WORKORDERID != 'All Work Orders' AND $CATEGORYID = 'All Categories'\r\n\tTHEN wl.workorderid = $WORKORDERID\r\n\t\t  \r\n\tWHEN $WORKORDERID != 'All Work Orders' AND $CATEGORYID != 'All Categories'\r\n\tTHEN gm.device = $CATEGORYID\r\n\r\nEND\r\n\r\nORDER BY `gc`.`guideid` ASC) t, \r\n       (SELECT @rownum := 0) r\r\norder by \"Route Step\" asc"
    }
   ]
  },
  {
   "title": "Minimum Route Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 7 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select \nCASE\n\tWHEN SUM(gm.time_required_min) <= 3020400\n\tTHEN SEC_TO_TIME(SUM(gm.time_required_min)) \t\n\tWHEN SUM(gm.time_required_min) > 3020400\n\tTHEN \"838:59:59+\"\n\tELSE \"None\"\nEND as \"Minimum Time\"\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid in (SELECT DISTINCT `gc`.`guideid` As \"Guide ID\"\nFROM `guide_current` `gc`\nJOIN `guide_revisions` `gr` USING (`guide_revisionid`)\nJOIN `guide_meta` `gm` ON `gm`.`revisionid` = `gr`.`gtr_revisionid`\nJOIN `guide_text` `gt` ON `gr`.`gt_revisionid` = `gt`.`gt_revisionid`\nLEFT JOIN `work_log` `wl` ON `gc`.`guideid` = `wl`.`guideid`\nWHERE \nCASE \n\tWHEN $WORKORDERID = 'All Work Orders' AND $CATEGORYID = 'All Categories'\n\tTHEN 1 = 1\n\t\n\tWHEN $WORKORDERID = 'All Work Orders' AND $CATEGORYID != 'All Categories'\n\tTHEN gm.device = $CATEGORYID\n\t\n\tWHEN $WORKORDERID != 'All Work Orders' AND $CATEGORYID = 'All Categories'\n\tTHEN wl.workorderid = $WORKORDERID\n\t\t  \n\tWHEN $WORKORDERID != 'All Work Orders' AND $CATEGORYID != 'All Categories'\n\tTHEN gm.device = $CATEGORYID\n\nEND\nORDER BY `gc`.`guideid` ASC)\n"
    }
   ]
  },
  {
   "title": "# of Route Steps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select max(x.Route_Step) as \"Step Count\"\nFROM (SELECT  \n       @rownum := @rownum + 1 AS \"Route_Step\", t.*\n  FROM (SELECT DISTINCT  `gt`.`title`  As \"Guide Title\", `gm`.`device` as \"Category\", `gc`.`guideid` As \"Guide ID\"\nFROM `guide_current` `gc`\nJOIN `guide_revisions` `gr` USING (`guide_revisionid`)\nJOIN `guide_meta` `gm` ON `gm`.`revisionid` = `gr`.`gtr_revisionid`\nJOIN `guide_text` `gt` ON `gr`.`gt_revisionid` = `gt`.`gt_revisionid`\nLEFT JOIN `work_log` `wl` ON `gc`.`guideid` = `wl`.`guideid`\nWHERE \nCASE \n\tWHEN $WORKORDERID = 'All Work Orders' AND $CATEGORYID = 'All Categories'\n\tTHEN 1 = 1\n\t\n\tWHEN $WORKORDERID = 'All Work Orders' AND $CATEGORYID != 'All Categories'\n\tTHEN gm.device = $CATEGORYID\n\t\n\tWHEN $WORKORDERID != 'All Work Orders' AND $CATEGORYID = 'All Categories'\n\tTHEN wl.workorderid = $WORKORDERID\n\t\t  \n\tWHEN $WORKORDERID != 'All Work Orders' AND $CATEGORYID != 'All Categories'\n\tTHEN gm.device = $CATEGORYID\n\nEND\nORDER BY `gc`.`guideid` ASC) t, \n       (SELECT @rownum := 0) r) x\n"
    }
   ]
  },
  {
   "title": "Maximum Route Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 11 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select CASE\n\tWHEN SUM(gm.time_required_max) <= 3020400\n\tTHEN SEC_TO_TIME(SUM(gm.time_required_max)) \t\n\tWHEN SUM(gm.time_required_max) > 3020400\n\tTHEN \"838:59:59+\"\n\tELSE \"None\"\nEND as \"Maximum Time\"\nFROM guide_current gc\nJOIN guide_revisions gr USING (guide_revisionid)\nJOIN guide_meta gm ON (gr.gtr_revisionid = gm.revisionid)\nwhere gc.guideid in (SELECT DISTINCT `gc`.`guideid` As \"Guide ID\"\nFROM `guide_current` `gc`\nJOIN `guide_revisions` `gr` USING (`guide_revisionid`)\nJOIN `guide_meta` `gm` ON `gm`.`revisionid` = `gr`.`gtr_revisionid`\nJOIN `guide_text` `gt` ON `gr`.`gt_revisionid` = `gt`.`gt_revisionid`\nLEFT JOIN `work_log` `wl` ON `gc`.`guideid` = `wl`.`guideid`\nWHERE \nCASE \n\tWHEN $WORKORDERID = 'All Work Orders' AND $CATEGORYID = 'All Categories'\n\tTHEN 1 = 1\n\t\n\tWHEN $WORKORDERID = 'All Work Orders' AND $CATEGORYID != 'All Categories'\n\tTHEN gm.device = $CATEGORYID\n\t\n\tWHEN $WORKORDERID != 'All Work Orders' AND $CATEGORYID = 'All Categories'\n\tTHEN wl.workorderid = $WORKORDERID\n\t\t  \n\tWHEN $WORKORDERID != 'All Work Orders' AND $CATEGORYID != 'All Categories'\n\tTHEN gm.device = $CATEGORYID\n\nEND\n\nORDER BY `gc`.`guideid` ASC)\n"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "options": { "content": "<h1>Work Order Signoffs\n<hr>" },
   "content": "<h1>Work Order Signoffs\n<hr>"
  },
  {
   "title": " ",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT wl.workorderid, \nwl.guideid, \ngt.title, \nso.entryid, \n-- wl.userid, \nu.username, \n-- so.signoffid, \n-- so.stepid, \n-- gr.guide_revisionid, \n-- gr.gst_revisionid, \n-- gstt.newest_gst_revisionid, \ngtr.orderby, \ngst.title as \"Step Title\", \n\nCONVERT_TZ(from_unixtime(so.date), @@session.time_zone, '+00:00') as \"Date\", \n\n\nCASE \n  WHEN so.status = \"approved\" THEN \"1\"\n  WHEN so.status = \"pending\"  THEN \"0\"\n  WHEN so.status = \"rejected\" THEN \"-1\"\nEND as \"Status\", \n\n-- so.status, \n\n\nso.type, \n-- su.so_userid, \nsu.so_username,  \n-- gm.device, \n\"PDF Log\" as \"PDF Log\"\n\nfrom supervisor_signoffs so\nleft join work_log wl on wl.entryid=so.entryid \n\n\nleft join guide_revisions gr on gr.guide_revisionid=wl.guide_revisionid\n\nleft join guide_meta gm on gm.revisionid=gr.gtr_revisionid\nleft join guide_text gt on gt.gt_revisionid=gr.gt_revisionid\n\n-- Add step titles\n\n\n\nleft JOIN (SELECT stepid, max(gst_revisionid) as newest_gst_revisionid\nFROM guide_step_text\ngroup by stepid order by newest_gst_revisionid) gstt on gstt.stepid=so.stepid\n\nleft JOIN guide_step_text gst on gst.gst_revisionid=gstt.newest_gst_revisionid\n\n\n-- Add user IDs\n\nleft join global_users u on u.userid=wl.userid \n\n-- Add user names\n\nLEFT join (select sso.userid  as so_userid, ssu.username as so_username, sso.signoffid as so_signoffid \n  from supervisor_signoffs sso\n  left join global_users ssu on sso.userid=ssu.userid ) su on so.signoffid=su.so_signoffid\n\n-- Add step numbers\n\n\n\n\n\nLEFT JOIN (SELECT orderby, stepid, max(gtr_revisionid) as newest_gtr_revisionid\n\nFROM guide_step_order_revisions\n\t\t   \ngroup by stepid order by newest_gtr_revisionid ) gsor on gsor.stepid=so.stepid \n\nleft JOIN guide_step_order_revisions gtr on gtr.gtr_revisionid =gsor.newest_gtr_revisionid and gtr.stepid=gsor.stepid \n\n\n  \n-- Conditions for filters\n\nWHERE\n($WORKORDERID = 'All Work Orders' OR wl.workorderid = $WORKORDERID)\n\t\nAND\n($GUIDE_ID = 'All Guides' OR gm.guideid = $GUIDE_ID)\n\n\n-- group by so.signoffid"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 33 },
   "options": {
    "content": "<h1>Work Order Route Details\n<hr>"
   },
   "content": "<h1>Work Order Route Details\n<hr>"
  },
  {
   "title": " ",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT \r\nb.Category,\r\nb.guideid as \"Guide ID\", \r\nb.title as \"Guide Title\",\r\nwl.entryid,\r\n\r\n\r\n-- CASE \r\n  -- WHEN wl.workorderid is NOT NULL THEN wl.workorderid\r\n --  ELSE '--'\r\n-- END \r\nwl.workorderid,\r\n\r\nwl.userid as \"User ID\",\r\n \r\nCONVERT_TZ(from_unixtime(wl.starttime), @@session.time_zone, '+00:00')  as \"Started\", \r\n\r\nCONVERT_TZ(from_unixtime(wl.endtime), @@session.time_zone, '+00:00') as \"Ended\", \r\n\r\nCASE \r\n  WHEN wl.cancelled = 0 AND endtime is NOT NULL THEN '2'\r\n  WHEN wl.cancelled = 0 AND endtime is NULL THEN '1'\r\n  WHEN wl.cancelled = 1 THEN '-1'\r\n  WHEN wl.starttime IS NULL THEN '0'\r\nEND as \"Status\", \r\n\r\nCASE \r\n    WHEN wl.endtime is NULL and wl.starttime is not NULL then \"In Progress\"\r\n    WHEN wl.endtime is NULL and wl.starttime is NULL then \"--\"\r\n    ELSE SEC_TO_TIME(wl.endtime - wl.starttime) \r\nEND as Duration\r\n\r\n, \"PDF Log\" as \"PDF Log\"\r\n\r\nFROM work_log wl\r\n\r\nleft JOIN \r\n\r\n(SELECT DISTINCT gc.guideid, gt.title, gm.device as \"Category\", gr.gsr_revisionid\r\nFROM guide_current gc\r\nJOIN guide_revisions gr USING (guide_revisionid)\r\nJOIN guide_meta gm ON gm.revisionid = gr.gtr_revisionid\r\nJOIN guide_text gt ON gr.gt_revisionid = gt.gt_revisionid\r\n\r\nORDER BY gc.guideid ASC) b\r\n\r\nON wl.guideid = b.guideid \r\n\r\n\r\n-- Find Current Step\r\nleft join guide_step_revisions gsr on gsr.revisionid=b.gsr_revisionid\t\t\t\r\nleft join (select work_log_timing.timingid, work_log_timing.stepid, work_log_timing.entryid \r\n\t\t   from work_log_timing\r\n\t\t   inner join (select stepid, entryid, max(timingid) as maxtime\r\n\t\t\t\t\t   from work_log_timing\r\n\t\t\t\t\t   group by work_log_timing.entryid) maxt\r\n\t\t   on work_log_timing.timingid=maxt.maxtime and work_log_timing.entryid=maxt.entryid) current_step\r\n\t\t\t\r\n\t\t\ton current_step.entryid=wl.entryid\r\n\r\n-- Find step number\r\nleft join (select guide_step_order_revisions.gtr_revisionid, guide_step_order_revisions.stepid, guide_step_order_revisions.orderby\r\n\r\nfrom guide_step_order_revisions\r\n\r\ninner join (Select stepid, max(gtr_revisionid) as maxrev\r\nfrom guide_step_order_revisions\r\ngroup by guide_step_order_revisions.stepid) mrv\r\n\r\non guide_step_order_revisions.gtr_revisionid=mrv.maxrev and guide_step_order_revisions.stepid=mrv.stepid) step_number on step_number.stepid = current_step.stepid\r\n\r\n-- \t\t\t\r\n\r\n\r\n\r\nWHERE \r\n\r\n/* Case statement to use WHERE clause appropriate to which filters were selected  */\r\n\r\n\r\n($WORKORDERID = 'All Work Orders' OR wl.workorderid = $WORKORDERID)\r\n\r\nAND ($CATEGORYID = 'All Categories' OR b.category = $CATEGORYID)\r\n\r\n\t\r\n\tgroup by wl.entryid"
    }
   ]
  }
 ]
}