apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secret
  labels:
  {{- include "api-gateway.labels" . | nindent 4 }}
data:
  {{- with .Values.frontegg }}
  FRONTEGG_AUTH_PUBLIC_KEY: {{ required "A valid .Values.frontegg.authenticationPublicKey entry required!" .authenticationPublicKey | b64enc | quote  }}
  FRONTEGG_CLOUD_API_GATEWAY_URL: {{ required "A valid .Values.frontegg.apiGatewayUrl entry required!" .apiGatewayUrl | b64enc | quote  }}
  FRONTEGG_AUTHENTICATION_SERVICE_URL: {{ required "A valid .Values.frontegg.authenticationServiceUrl entry required!" .authenticationServiceUrl | b64enc | quote  }}
  FRONTEGG_METADATA_SERVICE_URL: {{ required "A valid .Values.frontegg.metadataServiceUrl entry required!" .metadataServiceUrl | b64enc | quote  }}
  FRONTEGG_HYBRID_SERVICES: {{ required "A valid .Values.frontegg.hybridServices entry required!" .hybridServices | b64enc | quote  }}
  {{- end }}
