# --- BEGIN General Configuration --- #

variable "customer" {
  description = "The customer name for resource names and tagging. This will also be the autogenerated subdomain."
  type        = string
  default     = ""

  validation {
    condition = (
      length(var.customer) == 0 ||
      (length(var.customer) <= 10 &&
        can(regex("^[a-z0-9]", var.customer)) &&
        can(regex("[a-z0-9-]+", var.customer)) &&
        can(regex("[a-z0-9]$", var.customer))
    ))
    error_message = "Subdomain must be empty or between 1 and 10 characters long, start with a letter or digit, contain only lowercase letters, digits, or hyphens, and end with a letter or digit."
  }
}

variable "environment" {
  description = "Environment of the application"
  type        = string
  default     = "dev"

  validation {
    condition     = length(var.environment) <= 5
    error_message = "The length of the Environment must be less than 6 characters."
  }
}

variable "aws_profile" {
  description = "If running terraform from a workstation, which AWS CLI profile should we use for asset provisioning."
  type        = string
  default     = ""
}
# --- END General Configuration --- #

# --- BEGIN App Configuration --- #

variable "enable_webhooks" {
  description = "This option will spin up a managed Kafka & Redis cluster to support private webhooks."
  type        = bool
  default     = false
}

variable "enable_bi" {
  description = "Whether to deploy resources for BI, a replica database, a DMS task, and a Kafka cluster"
  type        = bool
  default     = false
}

variable "google_translate_api_token" {
  description = "If using machine translation, enter your google translate API token here."
  type        = string
  default     = ""
  sensitive   = true
}

variable "grafana_subpath" {
  description = "Subpath to serve Grafana from"
  type        = string
  default     = "dashboards"

  validation {
    condition     = can(regex("^[^/\\\\].*[^/\\\\]$", var.grafana_subpath))
    error_message = "The grafana_subpath must not start or end with a forward or backward slash."
  }
}

variable "devops_secret_name" {
  description = "Name of the secret which houses app configuration"
  type        = string
  default     = "devops/app/config"
}

variable "enable_vault" {
  description = "Use HashiCorp Vault for secret management via External Secrets Operator instead of Terraform-managed Kubernetes secrets."
  type        = bool
  default     = false
}

variable "image_tag" {
  description = "Docker image tag for the main Dozuki app container. Changes with every deploy."
  type        = string
}

variable "nextjs_tag" {
  description = "Docker image tag for the Next.js frontend container. Changes with every deploy."
  type        = string
}

variable "image_repository" {
  description = "Docker image repository (ECR) for app containers."
  type        = string
  default     = "069174876992.dkr.ecr.us-east-1.amazonaws.com"
}

variable "smtp_enabled" {
  description = "Whether to enable SMTP email sending."
  type        = bool
  default     = true
}

variable "smtp_host" {
  description = "SMTP server hostname."
  type        = string
  default     = "smtp.sendgrid.net"
}

variable "smtp_from_address" {
  description = "SMTP from email address."
  type        = string
  default     = "noreply@dozuki.com"
}

variable "smtp_auth_enabled" {
  description = "Whether to use SMTP authentication."
  type        = bool
  default     = true
}

variable "smtp_username" {
  description = "SMTP authentication username."
  type        = string
  default     = "apikey"
}

#tfsec:ignore:general-secrets-no-plaintext-exposure
variable "smtp_password" {
  description = "SMTP authentication password."
  type        = string
  default     = ""
  sensitive   = true
}

variable "protect_resources" {
  description = "When true, retain Vault secrets on destroy (soft delete). When false, permanently purge all versions."
  type        = bool
  default     = true
}

# --- END App Configuration --- #

# --- BEGIN Physical Module Passthrough Configuration (do not set or modify) --- #

variable "eks_cluster_id" {
  description = "ID of EKS cluster for app provisioning"
  type        = string
}

variable "primary_db_secret" {
  description = "ARN to secret containing primary db credentials"
  type        = string
}

variable "bi_database_credential_secret" {
  description = "ARN to secret containing bi db credentials"
  type        = string
  default     = ""
}

variable "dns_domain_name" {
  type        = string
  description = "Auto-provisioned subdomain for this environment"
}

variable "memcached_cluster_address" {
  type        = string
  description = "Address of the deployed memcached cluster"
}

variable "s3_kms_key_id" {
  description = "AWS KMS key identifier for S3 encryption. The identifier can be one of the following format: Key id, key ARN, alias name or alias ARN"
  type        = string
  default     = ""
}

variable "s3_objects_bucket" {
  description = "Name of the bucket to store guide objects. Use with 'create_s3_buckets' = false."
  type        = string
  default     = ""
}

variable "s3_images_bucket" {
  description = "Name of the bucket to store guide images. Use with 'create_s3_buckets' = false."
  type        = string
  default     = ""
}

variable "s3_documents_bucket" {
  description = "Name of the bucket to store documents. Use with 'create_s3_buckets' = false."
  type        = string
  default     = ""
}

variable "s3_pdfs_bucket" {
  description = "Name of the bucket to store guide pdfs. Use with 'create_s3_buckets' = false."
  type        = string
  default     = ""
}

variable "s3_replicate_buckets" {
  description = "Whether or not we are replicating objects from existing S3 buckets."
  type        = bool
  default     = false
}

# This needs to have no type due to terraform's weird handling of string lists. If you set a type it will convert it to
# a format we can't feed into helm
# tflint-ignore: terraform_typed_variables
variable "msk_bootstrap_brokers" {
  description = "Kafka bootstrap broker list"
}

variable "dms_task_arn" {
  type        = string
  description = "If BI is enabled, the DMS replication task arn."
}

variable "dms_enabled" {
  description = "If BI is enabled, whether or not to use DMS for conditional replication if true or a basic RDS read replica if false."
  type        = bool
  default     = false
}
variable "vault_address" {
  description = "Vault server address accessible from within the cluster (e.g. http://vault.internal.dozuki.com:8200)"
  type        = string
  default     = ""
}

variable "nlb_https_target_group_arn" {
  description = "NLB HTTPS target group ARN for TargetGroupBinding"
  type        = string
}

variable "nlb_http_target_group_arn" {
  description = "NLB HTTP target group ARN for TargetGroupBinding"
  type        = string
}

# --- END Physical Module Passthrough Configuration (do not set or modify) --- #