#cloud-config
repo_update: true
repo_upgrade: all

packages:
- jq
- mariadb

write_files:
- path: /home/ssm-user/.my.cnf
  permissions: '604'
  content: |
    [client]
    host=${database_hostname}
- path: /tmp/populate-mysql-credentials.sh
  permissions: '700'
  content: |
    #!/bin/bash -xe
    set -o xtrace

    aws secretsmanager get-secret-value --region "${aws_region}" \
          --secret-id "${database_credentials_secret_id}" | \
          jq -r .SecretString | \
          jq --raw-output '"user=\(.username)\npassword=\(.password)"' >> /home/ssm-user/.my.cnf
- path: /tmp/setup-k8.sh
  permissions: '700'
  content: |
    #!/bin/bash -xe
    set -o xtrace

    curl -L https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl \
    > /usr/local/bin/kubectl
    chmod 755 /usr/local/bin/kubectl
    
    curl -L https://get.helm.sh/helm-v3.8.1-linux-amd64.tar.gz > /tmp/helm.tar.gz
    tar -xzvf /tmp/helm.tar.gz
    cp /tmp/linux-amd64/helm /usr/local/bin/helm
    chmod 755 /usr/local/bin/helm

    mkdir -p /home/ssm-user/.kube

    aws eks update-kubeconfig --name "${eks_cluster_name}" --role-arn "${eks_cluster_access_role}" --kubeconfig /home/ssm-user/.kube/config --region ${aws_region}
    chown ssm-user:ssm-user /home/ssm-user/.kube -R

runcmd:
- /tmp/populate-mysql-credentials.sh
- /tmp/setup-k8.sh
