kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "integrations-service.fullname" . }}-configmap
  labels:
  {{- include "integrations-service.labels" . | nindent 4 }}
data:
  CLOUD_ENVIRONMENT: prod
  NODE_ENV: production
  PORT: "3014"
  FRONTEGG_SERVICE_NAME: integrations-service
  FRONTEGG_INTEGRATIONS_SERVICE_API_KEY: "frontegg-api-key"
