apiVersion: v1
kind: Secret
metadata:
  name: {{ include "integrations-service.fullname" . }}-secret
  labels:
  {{- include "integrations-service.labels" . | nindent 4 }}
data:
  FRONTEGG_INTEGRATIONS_SERVICE_MONGODB_URL:  {{ required "A valid .Values.mongo.connectionString entry required!" .Values.mongo.connectionString | b64enc | quote  }}
  FRONTEGG_INTEGRATIONS_SERVICE_SLACK_ENCRYPTION_SECRET:  {{ required "A valid .Values.frontegg.slack.encryptionKey entry required!" .Values.frontegg.slack.encryptionKey | b64enc | quote  }}
  {{- with .Values.messageBroker }}
  FRONTEGG_INTEGRATION_SERVICE_SLACK_CONFIG_UPDATE_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_INTEGRATION_SERVICE_SLACK_CONFIG_UPDATE_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote }}
  FRONTEGG_INTEGRATION_SERVICE_EMAIL_CONFIG_UPDATE_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_INTEGRATION_SERVICE_EMAIL_CONFIG_UPDATE_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote }}
  FRONTEGG_INTEGRATION_SERVICE_SMS_CONFIG_UPDATE_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_INTEGRATION_SERVICE_SMS_CONFIG_UPDATE_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote }}
  {{- end }}



